matter-labs/zksync-era

core/bin/circuit_synthesizer/Cargo.lock, core/bin/prover/Cargo.lock, core/bin/setup_key_generator_and_server/Cargo.lock
```
error[E0412]: cannot find type `OldWorker` in this scope
--> /home/a_chandrakar_matterlabs_dev/.cargo/git/checkouts/era-heavy-ops-service-54439bd555659c38/ce5ba80/api/src/legacy.rs:7:13
|
7  |     worker: OldWorker,
|             ^^^^^^^^^ help: a struct with a similar name exists: `Worker`
|
::: /home/a_chandrakar_matterlabs_dev/.cargo/git/checkouts/bellman-7a75f3b44e91e034/3aa6226/src/multicore.rs:23:1
```
=> update heavy-ops to fix building circuit-synthesizer

.gitmodules
Switching to use https instead of ssh for submodules - as many people might not have ssh access configured.
Also removed the binaryen dependency that was not used.
=> Update .gitmodules to use https instead of ssh and removed the binaryen dependency

prover/prover/Cargo.toml, prover/setup_key_generator_and_server/Cargo.toml
This PR modifies more indirect clients of zk_evm branch v1.3.3 which are dependencies of zksync-era to use it at the v1.3.3-rc0 tag.
=> Update More zk_evm Dependencies

Cargo.lock, prover/Cargo.lock
Bumps webpki to 0.22.2 due to RUSTSEC-2023-0052.
To fix vulnerability.
=> fix: Bumps webpki to fix RUSTSEC-2023-0052.

core/lib/mini_merkle_tree/benches/tree.rs, core/lib/mini_merkle_tree/src/lib.rs, core/lib/mini_merkle_tree/src/tests.rs, core/lib/types/src/commitment.rs, core/lib/types/src/l2_to_l1_log.rs, core/lib/zksync_core/src/api_server/web3/namespaces/zks.rs
Implements dynamic depth of the in-memory L2-to-L1 log Merkle tree. Previously, this tree always had 512 items (if necessary, additional zero items were added at the end). With these changes, the tree has *at least* 512 items (with padding); the actual number of items is `max(512, items.len().next_power_of_two())`. This makes the change backward-compatible without needing any logic tied to L1 batch number etc.
We want to allow larger Merkle tree depths than previously.
=> feat: Implement dynamic L2-to-L1 log tree depth

CODEOWNERS
This PR replaces the core team in codeowners with the newly created era-reviewers team.
To tighten who can approve PRs and not spam the rest.
=> chore(codeowners): Update Owner Team

.github/workflows/build-prover-template.yml, .github/workflows/ci-prover-reusable.yml, bin/ci_run, docker-compose-runner-nightly.yml
Switch default rust target to nightly for prover builds.
=> ci: switch default rust to nightly for prover builds

infrastructure/zk/package.json, infrastructure/zk/src/index.ts, infrastructure/zk/src/status.ts
* Adding zk status prover command to see the current state of FRI prover
* mostly focused on local deployments (might require some changes before we run it on boojnet)
* to better see what's going on in the prover pipeline
```shell
zk status prover
```
=> feat(boojum): Adding `zk status prover` command

core/lib/types/src/aggregated_operations.rs
* We were passing incorrect argument to the prover
* to make prover work, the original problem was a simple bug/typo.
=> fix(boojum): Don't pass aggregation_results as recursive aggregation inputs

core/lib/config/src/configs/contracts.rs, core/lib/zksync_core/src/lib.rs, etc/env/base/contracts.toml, infrastructure/zk/src/status.ts
* Added CONTRACTS_PROVER_AT_GENESIS flag to control which prover should be used during genesis
* Updated zk status command to compare the keys in the database and in the contracts
* without this flag, we were pushing the old keys to the contracts, which resulted in failed proofs.
=> feat(boojum): added flag to control prover selection at genesis

.github/workflows/release-please.yml
Uses PAT token for release please.
To allow other workflows to be triggered by tags creation.
=> ci: Uses PAT token for release please

core/lib/vm/src/lib.rs
* TracerExecutionStatus and TracerExecutionStopReason are part of the ExecutionEndTracer trait, but they were not publicly available.
* This breaks external implementations of the ExecutionEndTracer
=> fix(vm): Make execution status and stop reason public

docker/external-node/entrypoint.sh, docker/local-node/entrypoint.sh
Replaces container shell with EN and local-env executables in corresponding Docker images to eg. properly handle termination signals.
More details in original PR: https://github.com/matter-labs/zksync-era/pull/76
Courtesy of https://github.com/voron
Thanks for the contribution, and sorry it took so long to review - we've been busy with FOSS'ing our repos.
https://github.com/matter-labs/zksync-era/pull/76#issue-1849818996
=> fix: Add exec to replace shell inside entrypoint with the actual binary

core/lib/zksync_core/src/proof_data_handler/mod.rs
Use SNARK wrapper VK instead of FRI scheduler VK in proof_data_handler
It will be saved to `prover_fri_protocol_versions`, and we need them consistent with `protocol_versions`.
=> fix(boojum): Fix VK in prover_fri_protocol_versions

core/lib/dal/migrations/20231009073918_drop-prover_jobs_fri_l1_batch_number_fkey.down.sql, core/lib/dal/migrations/20231009073918_drop-prover_jobs_fri_l1_batch_number_fkey.up.sql
`prover_jobs_fri_l1_batch_number_fkey` is dropped.
`prover_jobs_fri` is filled only in prover DB, while `l1_batches` -- only in core DB, so we can't have the constraint.
=> fix(db): drop constraint prover_jobs_fri_l1_batch_number_fkey

core/lib/dal/sqlx-data.json, core/lib/dal/src/models/storage_sync.rs, core/lib/dal/src/sync_dal.rs, core/lib/types/src/api/en.rs
Removed unused fields from SyncBlock.
It is a backward compatible change, because the removed fields were optional.
We decrease the public api surface this way.
=> refactor: Removed unused fields from SyncBlock

core/bin/external_node/src/config/mod.rs
`default_enum_index_migration_chunk_size` is updated, so migration speed is acceptable with default settings.
Migration speed should be acceptable with default settings.
=> chore(en): Update `default_enum_index_migration_chunk_size`

prover/README.md
* Adding README to prover directory to describe the high level layout of the code
* to improve the knowledge and understanding of prover components
=> feat(boojum): Adding README to prover directory

core/lib/dal/sqlx-data.json, core/lib/dal/src/prover_dal.rs
Fix extremly expensive query
It could overload our database
=> fix(prover): Fix statistic query

core/lib/zksync_core/src/state_keeper/seal_criteria/conditional_sealer.rs, core/lib/zksync_core/src/state_keeper/seal_criteria/criteria/geometry_seal_criteria.rs, core/lib/zksync_core/src/state_keeper/seal_criteria/criteria/mod.rs
Added L1 batch seal criterion for number of L2 to L1 logs
Number of logs must be <= 512 per batch.
=> fix(state-keeper): Add L2ToL1LogsCriterion

.github/workflows/build-core-template.yml, .github/workflows/build-prover-template.yml
Conditional Docker login in CI only on push to main branch or against tag
- We should be logging in to Docker registries only when we intend to push images
- Secrets will not be available for workflows triggered against PRs created from works, so the current approach is not working anyway
=> ci: Docker login only on push to main or tag

docs/external-node/03_running.md
Increase RAM requirements for External Node
We have evidence that our tree requires more than 32 GB of RAM.
=> docs(en): Increase RAM requirement for en

.github/workflows/ci-docs-reusable.yml, .github/workflows/ci.yml, .github/workflows/coverage.yml, SECURITY.md
- Trigger lightweight CI if only markdown is changed in PR
- Improve "fallback" to running "all" CI
- More granular conditions to run core and prover CI
Faster CI, less runner time
=> ci: Separate CI for docs, more granular CI triggers for core/prover

.github/workflows/ci.yml
Current regex only triggers Docs CI if markdown file is changed in root of the repo, this change fixes that behaviour
=> ci: Trigger docs CI on markdown files in any dir

core/lib/state/Cargo.toml, core/lib/state/src/in_memory.rs, core/lib/state/src/rocksdb/mod.rs
- Removes some code that is not needed anymore.
- RocksDB enum_index migration is run till the end when storage is initializing. 
- Remove not needed code
- Ensure RocksDB has enum indices on boojnet before they are actually used
=> fix(boojum): remove extra code from state crate

.github/workflows/ci.yml, .github/workflows/coverage.yml
Run all CI jobs when some global dependencies change
When want to validate all CI jobs when dependencies for everything change
=> ci: Add all CI condition trigger

.github/workflows/build-prover-template.yml, .github/workflows/ci.yml
Subj
We don't need to call APi when env `ERA_BELLMAN_CUDA_RELEASE` is available and it's always available for internal contributors
=> ci: Run rate limit waiter script in Prover CI only from forks

prover/witness_generator/src/main.rs
* When running witness in continuous mode, panic when you cannot load the matching protocol version.
* Witness is running with a given commitment key. At startup, it checks if there is a matching protocol version for this key, and later uses this protocol version to fetch its task.
* We are running witness in 2 modes: either 'batch' (where it runs up to X tasks and quits) or continuous. Batch is mostly used in production, while continuous is used in local deployments.
* And if in the local deployment, the database was not updated - and protocol version is missing - then the job would get stuck forever (as it will try to pickup job for non-existing protocol). So instead, let's panic explicitly.
=> feat(fri-prover): In witness - panic if protocol version is not available

Cargo.lock, core/lib/multivm/src/glue/init_vm.rs, core/lib/multivm/src/vm_instance.rs, core/lib/zksync_core/src/api_server/execution_sandbox/apply.rs, core/lib/zksync_core/src/state_keeper/batch_executor/mod.rs, core/multivm_deps/vm_m5/Cargo.toml, core/multivm_deps/vm_m5/src/pubdata_utils.rs, core/multivm_deps/vm_m5/src/refunds.rs, core/multivm_deps/vm_m5/src/test_utils.rs, core/multivm_deps/vm_m5/src/vm.rs, core/multivm_deps/vm_m5/src/vm_with_bootloader.rs, core/multivm_deps/vm_m6/Cargo.toml, core/multivm_deps/vm_m6/src/pubdata_utils.rs, core/multivm_deps/vm_m6/src/refunds.rs, core/multivm_deps/vm_m6/src/test_utils.rs, core/multivm_deps/vm_m6/src/utils.rs, core/multivm_deps/vm_m6/src/vm.rs, core/multivm_deps/vm_m6/src/vm_with_bootloader.rs
Remove lifetime from multivm. Update zk_evm 1.3.1 to the version without lifetime
For better compatibility with the new VM versions, i've updated zk-evm by removing lifetime from vm state
=> feat(multivm): Remove lifetime from multivm

core/lib/multivm/src/glue/init_vm.rs, core/lib/multivm/src/lib.rs, core/lib/multivm/src/vm_instance.rs, core/lib/zksync_core/src/api_server/execution_sandbox/apply.rs, core/lib/zksync_core/src/state_keeper/batch_executor/mod.rs
Remove necessary data struct from multivm.
We've managed to remove lifetime and now VM instance can create all necessary types just inside VMInstance
=> refactor(multivm): remove necessary data

.github/workflows/label-extenal-contributions.yml
Subj
To be able to filter out all externally contributed PRs to then have filtering/notifications for them
=> ci: Worklow to mark PRs from forks with external-contribution label

.github/workflows/label-extenal-contributions.yml
=> ci: Fix permissions for Workflow to label external contributions

core/bin/merkle_tree_consistency_checker/src/main.rs, core/lib/merkle_tree/examples/loadtest/main.rs, core/lib/merkle_tree/src/storage/rocksdb.rs, core/lib/merkle_tree/tests/integration/domain.rs, core/lib/state/src/rocksdb/mod.rs, core/lib/storage/src/db.rs, core/lib/zksync_core/src/block_reverter/mod.rs, core/lib/zksync_core/src/metadata_calculator/helpers.rs
Fixes write stalls in RocksDB by configuring related DB options and retrying batch writes on stall.
Currently, write stalls lead to panics and maybe even to crash loops.
=> fix(db): Fix write stalls in RocksDB

core/lib/config/src/configs/contracts.rs, core/lib/contracts/src/lib.rs, core/lib/types/src/protocol_version.rs, core/lib/zksync_core/src/eth_watch/client.rs, core/lib/zksync_core/src/eth_watch/event_processors/governance_upgrades.rs, core/lib/zksync_core/src/eth_watch/event_processors/mod.rs, core/lib/zksync_core/src/eth_watch/mod.rs, core/lib/zksync_core/src/eth_watch/tests.rs, core/lib/zksync_core/src/lib.rs
With boojum upgrades will go through governor. PR adds functionality to process such upgrades while leaving old processor as well.
Prepare for boojum upgrade
=> feat(eth-watch): process governor upgrades

Cargo.lock
Updated the era-zkevm_opcode_defs dependency and minimal set of other dependencies which required update to a compatible version. This unlocked updated sha2 and sha3 dependencies to 0.10.8.
Prover integration test run for extra safety: https://github.com/matter-labs/zksync-era-workflows/actions/runs/6612607366
To include https://github.com/matter-labs/era-zkevm_opcode_defs/pull/16 which in turn allows us to depend on up-to-date versions of sha2 and sha3.
=> chore: updated era-zkevm_opcode_defs dependency

core/bin/external_node/src/config/mod.rs, core/bin/external_node/src/main.rs, core/lib/config/src/configs/database.rs, core/lib/storage/src/db.rs, core/lib/storage/src/lib.rs, core/lib/zksync_core/src/metadata_calculator/helpers.rs, core/lib/zksync_core/src/metadata_calculator/mod.rs, core/lib/zksync_core/src/metadata_calculator/updater.rs
[A previous fix](https://github.com/matter-labs/zksync-era/pull/265) didn't really work judging by Merkle tree behavior on the stage env. This PR makes the initialization timeout configurable (and increases the default value from 10s to 30s; 30s is approximately equal to the compaction duration) and slightly increases the number of retries on stalled writes.
Having write stalls leads to panics and is obviously bad.
=> fix(db): Fix write stalls in RocksDB (for real this time)

.github/workflows/zk-environment.publish.yml
Pre-pulling Docker manifests before trying to glue multi-arch image from them
=> ci: Fix zk-env Docker images publishing, take 2

docker/zk-environment/Dockerfile
Subj
All of our JS machinery is now expecting Node 18, so this aligns Node version with what's considered being "our" version
=> ci: Downgrade node to 18 in zk-env

docs/advanced/gas_and_fees.md
fix: fix the broken link for get_txs_fee_in_wei
- fix the broken link for get_txs_fee_in_wei
- Documentation error
=> fix: fix the broken link for get_txs_fee_in_wei

.github/workflows/build-prover-fri-gpu-gar.yml
push FRI docker image to Asia and Europe
ability to spawn FRI provers in other region
- [ *] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ *] Tests for the changes have been added / updated.
- [ *] Documentation comments have been added / updated.
- [* ] Code has been formatted via `zk fmt` and `zk lint`.
=> fix(CI): push FRI docker image to asia + europe

.github/workflows/zk-environment-old-publish.yml, .github/workflows/zk-environment-publish.yml, docker-compose-runner.yml, docker/zk-environment/20.04_amd64_old.Dockerfile
Subj
We need to debug recent load test performance degradation. As a first step, we're going to try switching back to using previous iteration of CI runner image
=> ci: Temp switch CI to use old zk-env Ubuntu 20.04 based image

core/lib/storage/src/db.rs, core/lib/storage/src/metrics.rs
Fixes (hopefully) the root cause of recent RocksDB misbehavior. After recent refactoring, it improperly cancels background compactions / flushes each time a `RocksDB` instance is dropped, which leads to compactions / flushes being constantly interrupted. (After refactoring, `RocksDB` instances are `Clone`eable and act essentially as `Arc` wrappers; a new instance is created and dropped, in particular, [when processing](https://github.com/matter-labs/zksync-era/blob/ec41692063909742005acd656694a8f0838fcf33/core/lib/zksync_core/src/metadata_calculator/updater.rs#L385) each chunk of L1 batches.) A proper solution, implemented by this PR, is to cancel background work when dropping an internal, non-`Arc`'d DB instance.
That's a bug that makes RocksDB behave *very* unstably, as witnessed by …
=> fix(db): Fix root cause of RocksDB misbehavior

docs/advanced/02_deposits.md, docs/advanced/03_withdrawals.md
Update examples of using zkSync CLI according to the command restructure from https://github.com/matter-labs/zksync-cli/pull/64
Make examples up-to-date with latest version of zkSync CLI
=> fix: zksync-cli commands restructure

docs/advanced/02_deposits.md
Change link for Contract docs in 02_deposit.md.
The previous link is 404'ing
- [X ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ X] Tests for the changes have been added / updated.
- [ X] Documentation comments have been added / updated.
- [ X] Code has been formatted via `zk fmt` and `zk lint`.
=> docs: incorrect link reference in 02_deposit.md

docker-compose-cpu-runner.yml
Subj
Prover FRI is currently running on nightly Rust hence requires using zk-env Rust nigtly image
=> ci: Fix image in docker-compose-cpu-runner.yml

.github/workflows/ci-core-reusable.yml, core/CHANGELOG.md, core/tests/ts-integration/hardhat.config.ts, core/tests/ts-integration/scripts/compile-yul.ts, core/tests/ts-integration/tests/api/contract-verification.test.ts, docker/contract-verifier/Dockerfile, docker/zk-environment/Dockerfile, docs/advanced/01_initialization.md
Bumps the zksolc version to 1.3.16 because 1.3.15 was being used. Assuming this is a more involved process than just bumping this, but figured I'd PR in anyway in case it helped speed anything up. Also, couldn't quickly figure out how to test `docker/contract-verifier/Dockerfile` as it's broken for me for unrelated parts.
Also fixes a typo in the init docs, I can separate it if wanted.
Broken on a fresh install because of yanked version https://github.com/matter-labs/zksolc-bin/commit/2a29ad1d8920550d9aeef195f22c8f0ca14e5626
=> fix: bump zksolc from yanked version to 1.3.16

.github/workflows/build-prover-fri-gpu-gar.yml
Use public setup-data bucket in backed-in prover images
=> fix(ci): Use public setup-data bucket in building prover images

docs/setup-dev.md
- incorrect path reference in setup-dev.md
- zksync-era is more appropriate
=> chore: incorrect path reference in `setup-dev.md`

core/lib/dal/sqlx-data.json, core/lib/dal/src/fri_prover_dal.rs
use join instead of nested query for FRI prover extracting jobs
This is expected to make the `SELECT` faster as per discussion with DBA.
- [* ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ *] Tests for the changes have been added / updated.
- [ *] Documentation comments have been added / updated.
- [ *] Code has been formatted via `zk fmt` and `zk lint`.
=> fix(db-query): use join instead of nested query for FRI prover extracting

core/lib/multivm/src/glue/types/vm/vm_block_result.rs, core/lib/multivm/src/glue/types/vm/vm_partial_execution_result.rs, core/lib/multivm/src/interface/types/outputs/execution_result.rs, core/lib/multivm/src/interface/types/outputs/statistic.rs, core/lib/multivm/src/versions/vm_latest/implementation/execution.rs, core/lib/multivm/src/versions/vm_latest/implementation/statistics.rs, core/lib/multivm/src/versions/vm_latest/tracers/refunds.rs, core/lib/multivm/src/versions/vm_virtual_blocks/implementation/statistics.rs, core/lib/multivm/src/versions/vm_virtual_blocks/tracers/refunds.rs, core/lib/types/src/fee.rs, core/lib/types/src/tx/tx_execution_info.rs, core/lib/zksync_core/src/api_server/execution_sandbox/vm_metrics.rs, core/lib/zksync_core/src/state_keeper/seal_criteria/criteria/pubdata_bytes.rs, core/lib/zksync_core/src/state_keeper/tests/mod.rs
Calculate pubdata published only once for tx 
For boojum pubdata calculation is getting more complicated in terms of tx size and for keeping everything precise we can calculate pubdata only once
=> feat(vm): Make calculation for pubdata a bit more percise

core/lib/constants/src/ethereum.rs, core/lib/types/src/storage/writes/mod.rs, core/lib/zksync_core/src/api_server/tx_sender/mod.rs, core/lib/zksync_core/src/gas_tracker/mod.rs, core/lib/zksync_core/src/state_keeper/keeper.rs, core/lib/zksync_core/src/state_keeper/seal_criteria/conditional_sealer.rs, core/lib/zksync_core/src/state_keeper/seal_criteria/criteria/gas.rs, core/lib/zksync_core/src/state_keeper/seal_criteria/criteria/geometry_seal_criteria.rs, core/lib/zksync_core/src/state_keeper/seal_criteria/criteria/pubdata_bytes.rs, core/lib/zksync_core/src/state_keeper/seal_criteria/criteria/slots.rs, core/lib/zksync_core/src/state_keeper/seal_criteria/criteria/tx_encoding_size.rs, core/lib/zksync_core/src/state_keeper/seal_criteria/mod.rs
Disables `InitialWritesCriterion`, `RepeatedWritesCriterion`, `L2ToL1LogsCriterion` for post-boojum blocks by setting limit to `usize::max`.
Some circuits are no longer single-instance in boojum
=> feat(state-keeper): Disable some seal criteria for boojum

core/lib/dal/sqlx-data.json, core/lib/dal/src/fri_prover_dal.rs
use nested query for re-queuing jobs FRI prover
* This is expected to make the UPDATE faster as per discussion with DBA.
* The concurrent updates to db would be faster.
- [* ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [* ] Tests for the changes have been added / updated.
- [ *] Documentation comments have been added / updated.
- [ *] Code has been formatted via `zk fmt` and `zk lint`.
=> fix(db-query): use nested query for requeuing FRI prover jobs

core/lib/zksync_core/src/sync_layer/client.rs, core/lib/zksync_core/src/sync_layer/external_io.rs
- `fetch_l2_block` saves blocks in cache
- fixed log in `ExternalIO:: seal_miniblock`
Making cache client to behave traditional way, i.e. cache results got from server. This will also fix invariant that previous block is always (except for first iteration after start) kept in cache and fix sporadic panics caused by inconsistent API responses
=> feat(en): Cache blocks in `fetch_l2_block`

.github/workflows/build-docker-from-tag.yml, .github/workflows/ci.yml, .github/workflows/release-test-stage.yml
This complements recent addition and automatic post-generation update of [JSON file with current setup data keys commit SHA GCS directory](https://github.com/matter-labs/zksync-era/blob/main/prover/setup-data-gpu-keys.json)
We will now dynamically fetch setup keys commit for specific code commit we're building against, instead of manually creating PRs with setup data key bumps.
=> ci: Automatically extract Prover FRI GPU keys ids from JSONs

core/lib/multivm/src/interface/types/outputs/execution_state.rs
Making the branch use the latest contracts from the `main` branch
=> chore: Use contracts from main

.github/workflows/build-docker-from-tag.yml, .github/workflows/release-test-stage.yml
This complements recent addition and automatic post-generation update of [JSON file with current setup data keys commit SHA GCS directory](https://github.com/matter-labs/zksync-era/blob/main/prover/setup-data-gpu-keys.json)
We will now dynamically fetch setup keys commit for specific code commit we're building against, instead of manually creating PRs with setup data key bumps.
=> chore: Sync boojum integration with main

.github/workflows/build-core-template.yml
=> ci: Login to Docker registries only when actually pushing images

core/lib/zksync_core/src/eth_sender/eth_tx_aggregator.rs
Use correct contract ABI with `get_verification_key` function
Fix eth-sender for pre-boojum
=> fix(eth-sender): Correct ABI for get_verification_key

core/lib/types/src/commitment.rs, core/lib/types/src/l2_to_l1_log.rs, core/lib/zksync_core/src/genesis.rs, core/lib/zksync_core/src/metadata_calculator/mod.rs
L1 batch metadata is calculated differently for pre-boojum and post-boojum batches.
L1 batch metadata backward compatibility
=> fix: Versioned L1 batch metadata

prover/setup-data-gpu-keys.json
update gpu prover setup data path to remove extra gpu suffix until automation is fixed.
* required for building GPU fri prover
- [* ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ *] Tests for the changes have been added / updated.
- [ *] Documentation comments have been added / updated.
- [ *] Code has been formatted via `zk fmt` and `zk lint`.
=> fix(path): update gpu prover setup data path to remove extra gpu suffix

core/tests/ts-integration/tests/custom-erc20-bridge.test.ts
Waits for l2 bridge init in custom bridge test.
Previously we just waited 2 seconds which may be not enough in some cases.
=> chore(tests): Wait for l2 bridge init in test

core/lib/queued_job_processor/src/lib.rs
Label `service` renamed to `service_name`.
Our metrics scraping agent overwrites `service` with different value.
=> chore(metrics): Rename job attempts label

core/lib/dal/src/blocks_dal.rs, core/lib/zksync_core/src/eth_sender/tests.rs, core/lib/zksync_core/src/metadata_calculator/updater.rs, core/lib/zksync_core/src/state_keeper/io/tests/mod.rs, core/lib/zksync_core/src/sync_layer/tests.rs
Saves commitment for pre-boojum batches unconditionally
They don't have `events_queue_commitment` but `commitment` should be saved anyway
=> fix(metadata-calculator): Save commitment for pre-boojum

core/lib/commitment_utils/src/lib.rs, core/lib/dal/src/blocks_dal.rs, core/lib/types/src/commitment.rs, core/lib/zksync_core/src/eth_sender/tests.rs, core/lib/zksync_core/src/gas_tracker/mod.rs, core/lib/zksync_core/src/genesis.rs, core/lib/zksync_core/src/metadata_calculator/mod.rs, core/lib/zksync_core/src/metadata_calculator/updater.rs, core/lib/zksync_core/src/state_keeper/io/tests/mod.rs, core/lib/zksync_core/src/sync_layer/tests.rs
- `events_queue_commitment` is not calculated if `events_queue` is missing
- `metadata_calculator` doesn't require `header.protocol_version` is present
`events_queue` is missing for old batches, `header.protocol_version` is none for old batches in ENs databases
=> fix(metadata-calculator): Do not require events_queue for old batches

core/lib/zksync_core/src/proof_data_handler/request_processor.rs
`events_queue_commitment`, `bootloader_initial_content_commitment` are checked in proof-data-handler only for post-boojum batches.
These values are not present for pre-boojum batches.
=> fix(proof-data-handler): Check commitments only for post-boojum

core/lib/merkle_tree/src/consistency.rs, core/lib/zksync_core/src/metadata_calculator/tests.rs
Fix duplicate_leaf_index_error test, which [sometimes fails in CI](https://github.com/matter-labs/zksync-era/actions/runs/6848926146/job/18620092974?pr=432).
Failing CI costs time and money.
=> test(merkle tree): Fix flaky `MerkleTree` consistency test

core/lib/merkle_tree/examples/recovery.rs, core/lib/merkle_tree/src/recovery.rs, core/lib/merkle_tree/src/storage/mod.rs, core/lib/merkle_tree/src/storage/tests.rs, core/lib/merkle_tree/tests/integration/recovery.rs, prover/Cargo.lock
Allow recovery the Merkle tree from entries provided in an arbitrary order.
This is necessary to implement the snapshot recovery PoC and could be beneficial in the long run.
=> feat(merkle tree): Allow random-order tree recovery

core/lib/zksync_core/src/house_keeper/fri_prover_queue_monitor.rs
Fixes panic on unknown FRI prover group id.
=> fix: Fixes panic on unknown FRI prover group id

core/lib/dal/sqlx-data.json, core/lib/dal/src/fri_prover_dal.rs
Change the query we use to get the next job for FRI prover. The new query should be equivalent
The old one was evidently slow. Our DBA did some research and came up with the new version.
=> fix(prover): use a more performant query to get next job for FRI prover

core/lib/zksync_core/src/state_keeper/seal_criteria/criteria/geometry_seal_criteria.rs
**What**
Removes `ComputationalGasCriterion` from post-Boojum versions
**Why**
* There is no limit on total number of circuits in post-Boojum
* We want to test proving logic when we spend a lot of comp. gas in one l1 batch (this will result in tens of thousands of prover jobs - we want to test the system under that circumstances)
Safety: we do need to properly test this on stage before we upgrade mainnet. We should also discuss if want to introduce _some_ limit - even though there is no hard limit
=> feat(state-keeper): Remove computational gas limit from boojum protocol version

core/lib/zksync_core/src/api_server/web3/namespaces/zks.rs
Fixes proofs L2ToL1Logs for pre-boojum blocks.
=> fix(core): differentiate l2 to l1 logs tree size for pre and post boojum batches

core/lib/zksync_core/src/state_keeper/seal_criteria/criteria/geometry_seal_criteria.rs
for safety reason we want to rllback the removal of comp. gas limit
=> feat(state-keeper): reapply computational gas limit

docker/prover-gpu-fri/Dockerfile
- Adds the ability to build prover-gpu-fri Docker image for running on Nvidia GPUs that are not L4 (arch 89)
- Uses lightweight CUDA runtime image for running the binary
=> chore: Ability to override default CUDA arch for prover-gpu-fri

core/lib/zksync_core/src/sync_layer/batch_status_updater.rs
ENs are broken due to tx mismatch. This PR will allow ENs to restart and hopefully update the state. More information [here](https://www.notion.so/matterlabs/EN-is-broken-on-testnet-due-to-mismatched-txs-11c68bca2a4047cb8730e21e21f4ac41).
This was discussed with @danil.
=> fix(external-node): Check txs at insert time instead of read time

core/lib/zksync_core/src/sync_layer/batch_status_updater.rs, deny.toml
=> fix: Update comments post-hotfix

docs/repositories.md
Hello, 
This change is made to ensure that developers, contributors can access the correct documentation. 
This pull request fixes a broken link.   
The broken link was causing confusion and potentially preventing developers, contributors from accessing the zksync-cli. 
Correct link: https://github.com/matter-labs/zksync-cli
- Manually reviewed the documentation and verified the correct link. 
- No additional dependencies or changes are required.
- This fix is straightforward and does not impact any other functionalities.
Thank you.
=> chore: Fix broken link in repositories.md

core/lib/types/src/block.rs, core/lib/zksync_core/src/consensus/payload.rs, core/lib/zksync_core/src/sync_layer/external_io.rs, core/lib/zksync_core/src/sync_layer/fetcher.rs, core/lib/zksync_core/src/sync_layer/gossip/buffered/tests.rs, core/lib/zksync_core/src/sync_layer/gossip/conversions.rs, core/lib/zksync_core/src/sync_layer/gossip/mod.rs, core/lib/zksync_core/src/sync_layer/gossip/storage/mod.rs, core/lib/zksync_core/src/sync_layer/gossip/storage/tests.rs, core/lib/zksync_core/src/sync_layer/gossip/tests.rs, core/lib/zksync_core/src/sync_layer/sync_action.rs, core/lib/zksync_core/src/sync_layer/tests.rs
Support non-zero genesis block specified in executor configuration. Check whether this block exists on initialization; validate its correspondence if it does, and persist consensus fields if it doesn't.
This is necessary to support gossip-based syncing in practice; we likely won't back-sign all blocks in all envs.
=> feat(en): Support arbitrary genesis block for external nodes

core/lib/dal/sqlx-data.json, core/lib/dal/src/witness_generator_dal.rs, spellcheck/era.dic
This revert is done to facilitate boojum upgrade on mainnet2. Without this, old provers would be halt and boojum upgrade could take longer than anticipated.
`waiting_for_artifacts` forced witness to wait on BWIP run. `queued` makes them run instantly.
=> fix(witness_generator): Disable BWIP dependency

.github/workflows/ci-core-reusable.yml, core/tests/ts-integration/hardhat.config.ts, core/tests/ts-integration/scripts/compile-yul.ts, core/tests/ts-integration/tests/api/contract-verification.test.ts, docker/contract-verifier/Dockerfile
Adds support for zksolc v1.3.17 to contract-verifier.
Contract-verifier should support latest version
=> feat(contract-verifier): Support verification for zksolc v1.3.17

CODEOWNERS
Removes era-reviewers group from codeowners.
- Too noisy.
- We have internal processes for that anyways.
=> chore: Remove era-reviewers from codeowners

docs/launch.md, infrastructure/zk/src/hyperchain_wizard.ts, infrastructure/zk/src/init.ts, infrastructure/zk/src/run/run.ts
* Removed plonk setup (where we downloaded the CRS keys)
* It is needed only for prover setup (and then this is handled within the prover_setup.ts directly)
* it will save a lot of network bandwidth and time during zk stack setup
=> chore(zk init): Removed plonk setup

infrastructure/zk/src/docker.ts, infrastructure/zk/src/init.ts
* replaced docker-compose with docker compose 
* we moved to use docker compose (instead of docker-compose) - which is a newer version
=> chore(zk): finishing migration to docker compose

core/lib/dal/sqlx-data.json, core/lib/dal/src/models/storage_sync.rs, core/lib/dal/src/sync_dal.rs, core/lib/types/src/api/en.rs, core/lib/zksync_core/src/sync_layer/tests.rs
Removes `root_hash` field from `SyncBlock`.
It's not used anywhere, set to a dummy value (miniblock hash) and doesn't make sense in general (state hashes are computed on L1 batch level, not miniblock level).
=> feat(en): Remove `SyncBlock.root_hash`

.github/workflows/build-core-template.yml, .github/workflows/build-external-node-docker.yml, .github/workflows/build-local-node-docker.yml, .github/workflows/ci-core-reusable.yml
Pre-download one more version of viper compiler
Workaround for rate limiting
=> chore(ci): Pre-download one more version of viper compiler

.github/workflows/build-core-template.yml, .github/workflows/build-external-node-docker.yml, .github/workflows/build-local-node-docker.yml, .github/workflows/ci-core-reusable.yml, core/tests/ts-integration/hardhat.config.ts, core/tests/ts-integration/scripts/compile-yul.ts, core/tests/ts-integration/tests/api/contract-verification.test.ts, docker/contract-verifier/Dockerfile
Adds zksolc v1.3.18 to contract verifier
Adds zksolc v1.3.18 to contract verifier
=> feat(contract-verifier): Add zksolc v1.3.18

core/lib/dal/sqlx-data.json, core/lib/dal/src/proof_generation_dal.rs, core/lib/zksync_core/src/house_keeper/fri_prover_queue_monitor.rs
Fix oldest not generated batch query
For metrics to work correctly
=> fix: Follow up metrics fixes vol.2

.githooks/pre-push
Removing this check for now, I will re-add is as an opt-in check, probably with other checks bundled in. It's best not to require built project on every push.
=> fix: removing sqlx check from pre-push

docs/guides/external-node/02_configuration.md, docs/guides/external-node/prepared_configs/testnet-goerli-config-deprecated.env, docs/guides/external-node/prepared_configs/testnet-sepolia-config.env
- marks goerli testnet EN config as deprecated
- adds sepolia testnet EN config
- removes `EN_BOOTLOADER_HASH`, `EN_DEFAULT_AA_HASH` from configs as these vars are not used anymore
Prepare docs for sepolia testnet EN launch
=> chore(en): Add sepolia en config

core/lib/dal/src/connection/mod.rs
Removes lifetime in the ConnectionPoolBuilder
To make it easier to store the builder in long-living structures.
=> feat(dal): Make ConnectionPoolBuilder owned

infrastructure/zk/src/down.ts
Currently zk init may fail on linux due to docker creating files with root permissions.
=> chore(zk): clean volumes directory from container to fix permissions on linux

core/lib/zksync_core/src/sync_layer/fetcher.rs
Subject.
There is a valid scenario in which we might get miniblock hash mismatch, namely after a reorg.
=> fix(en): Downgrade miniblock hash equality assertion to warning

Cargo.lock, core/lib/utils/src/misc.rs
Remove unnecessary method call
It might improve performance but probably not. Better to not have it anyway.
=> perf: remove unnecessary to_vec

infrastructure/zk/src/format_sql.ts
Change that makes format_sql.ts script only override file if there was some formatting to do. This change is needed to prevent rust build system from dropping build caches when files did not change
=> fix: override file only needed in format_sql.ts

.github/workflows/ci-core-reusable.yml, core/lib/dal/sqlx-data.json, core/lib/dal/src/transactions_web3_dal.rs, core/lib/types/src/api/mod.rs, core/lib/zksync_core/src/api_server/tx_sender/proxy.rs, core/lib/zksync_core/src/api_server/web3/namespaces/eth.rs, core/lib/zksync_core/src/sync_layer/tests.rs, core/tests/loadnext/src/account/mod.rs, core/tests/loadnext/src/account/tx_command_executor.rs, core/tests/loadnext/src/executor.rs, core/tests/revert-test/tests/revert-and-restart.test.ts, core/tests/ts-integration/tests/api/web3.test.ts, core/tests/ts-integration/tests/custom-account.test.ts, core/tests/ts-integration/tests/mempool.test.ts, sdk/zksync-rs/src/operations/mod.rs
For compatibility with Ethereum, we have to return `Receipt` only if tx is included in the miniblock. Block hash is not null null. 
For compatibility with Ethereum and for not breaking external clients, such as Metemask, they do not expect that block hash could be null
=> feat(api): Do not return receipt if tx was not included to the batch

docker-compose.yml
PostgreSQL should only be accessible from the localhost interface, otherwise malicious actors can change or delete the database.
Bringing the `zk init` settings in line with `zk stack init` settings: https://github.com/matter-labs/zksync-era/blob/main/docker-compose-zkstack-common.yml#L28
=> fix: close Docker PostgreSQL to external connections

prover/witness_vector_generator/src/generator.rs
Prover DB is under heavy load. 
The query that witness vectors generators run to get a new prover job is slow. In theory we shouldn't be running any witness vectors gens for circuits that don't have any jobs queued, but query insights suggest otherwise.
This increases the polling interval - so that even if there are no jobs, we don't perform the query too often
=> fix(prover): increase DB polling interval for witness vector generators

core/lib/zksync_core/src/api_server/web3/metrics.rs, core/lib/zksync_core/src/api_server/web3/mod.rs, core/lib/zksync_core/src/api_server/web3/pubsub.rs, core/lib/zksync_core/src/api_server/web3/tests/mod.rs
A small follow-up PR for #693 that introduces some metrics allowing to track the health of the new approach. Also, does minor refactoring for the API server builder so it's more typesafe.
Observability and maintainability.
=> feat(api): Add metrics for `jsonrpsee` subscriptions

.github/workflows/ci-core-reusable.yml
Silencing errors like:
```
Run ci_run cat server.log
cat: server.log: No such file or directory
Error: Process completed with exit code 1.
```
That imo are just an additional needless noise that decrease the UX of development.
=> fix: silence cat errors on Show Logs step

core/bin/snapshots_creator/src/main.rs
added waiting for prometheus task to finish.
We need to wait for prometheus to push one last 'batch of metrics'
=> fix: added waiting for prometheus to finish

docker-compose-cpu-runner.yml, docker-compose-gpu-runner-cuda-12-0.yml, docker-compose-gpu-runner.yml
PostgreSQL should only be accessible from the localhost interface, otherwise malicious actors can change or delete the database.
Per discussion with Shahar, fixing all the remaining configs.
Related: https://github.com/matter-labs/zksync-era/pull/741
=> fix: all Docker configs no longer expose PostgreSQL externally

core/lib/types/src/commitment.rs
Solve panics on nonexistent calldata.
=> fix(core): do not unwrap unexisting calldata in commitment and regenerate it

core/lib/eth_client/src/clients/mock.rs, core/lib/eth_client/src/lib.rs, core/lib/eth_signer/src/lib.rs, core/lib/zksync_core/src/api_server/tx_sender/mod.rs, core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/namespaces/en.rs, core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/namespaces/eth.rs, core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/namespaces/snapshots.rs, core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/mod.rs, core/lib/zksync_core/src/api_server/web3/namespaces/debug.rs, core/lib/zksync_core/src/api_server/web3/namespaces/en.rs, core/lib/zksync_core/src/api_server/web3/namespaces/eth.rs, core/lib/zksync_core/src/api_server/web3/namespaces/snapshots.rs, core/lib/zksync_core/src/api_server/web3/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/state.rs, core/lib/zksync_core/src/api_server/web3/tests/mod.rs, core/lib/zksync_core/src/l1_gas_price/mod.rs, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/state_keeper/io/mempool.rs, core/lib/zksync_core/src/state_keeper/io/tests/tester.rs, core/lib/zksync_core/src/state_keeper/mempool_actor.rs, core/lib/zksync_core/src/state_keeper/mod.rs
- Replaces uses of `G: L1GasPriceProvider` with `dyn L1GasPriceProvider`.
- ...as a result, `StateKeeper` and `TxSender` (and thus all the API structures) are now generic-free.
- Prerequisite for modular system (generic types are hard for dynamically-configured setup).
- Invoking `L1GasPriceProvider` is not related to any hot loops where dynamic dispatch would be noticeable, so having it as a generic is kinda meaningless anyways.
=> feat: Remove generic bounds on L1GasPriceProvider

infrastructure/zk/src/status.ts
This PR changes the wizard to not return from `zk status prover` if there is a lag between blocks committed by eth sender and blocks sealed by the state keeper.
Before this PR, if there was a lag, users couldn't see prover stats. Without this `return` they now can.
=> fix(hyperchain wizard): Do Not Return Upon EthSender Lag

core/bin/external_node/src/config/mod.rs, core/bin/external_node/src/main.rs, core/lib/config/src/configs/api.rs, core/lib/env_config/src/api.rs, core/lib/zksync_core/src/api_server/tx_sender/mod.rs, core/lib/zksync_core/src/lib.rs
Removes TPS Limiter from TX Sender component.
- It didn't work properly: limit is applied per API server, and API servers are horizontally scalable.
- It doesn't seem to be configured in any of our envs.
- It doesn't really make sense in context of ENs.
- We have other mempool protection measures anyways (tx dry-run, nonce limits, etc).
=> feat: Remove TPS limiter from TX Sender

core/lib/zksync_core/src/eth_sender/eth_tx_aggregator.rs, core/lib/zksync_core/src/eth_sender/eth_tx_manager.rs, core/lib/zksync_core/src/eth_sender/tests.rs, core/lib/zksync_core/src/lib.rs
Follow-up to https://github.com/matter-labs/zksync-era/pull/792 
Same reasons
=> feat(eth_sender): Remove generic bounds on L1TxParamsProvider in EthSender

core/bin/external_node/src/main.rs, core/lib/zksync_core/src/api_server/tx_sender/mod.rs, core/lib/zksync_core/src/consensus/testonly.rs, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/state_keeper/keeper.rs, core/lib/zksync_core/src/state_keeper/mod.rs, core/lib/zksync_core/src/state_keeper/seal_criteria/conditional_sealer.rs, core/lib/zksync_core/src/state_keeper/seal_criteria/mod.rs, core/lib/zksync_core/src/state_keeper/tests/mod.rs, core/lib/zksync_core/src/state_keeper/tests/tester.rs, core/lib/zksync_core/src/sync_layer/tests.rs, spellcheck/era.dic
Defines a new trait: `ConditionalSealer` and provides two implementations: `SequencerSealer` and `NoopSealer`.
- Prerequisite for ZK Stack configuration system.
- Leaves a single constructor for the state keeper.
- Removes `StateKeeperConfig` use from `TxSender`.
- Potentially makes it possible to create `ConditionalSealer` that contains some kind of sealing logic but does not rely on `StateKeeperConfig`.
=> refactor(state_keeper): Abstract ConditionalSealer

core/bin/external_node/src/main.rs, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/metadata_calculator/mod.rs, core/lib/zksync_core/src/metadata_calculator/recovery/tests.rs, core/lib/zksync_core/src/metadata_calculator/tests.rs
Makes metadata calculator config owned + makes it use `Box<dyn ObjectStore>` instead of `ObjectStoreFactory`.
- Prerequisite for ZK Stack modular thingy.
- Makes it easy to store the config object in a dynamic context.
- Makes it more abstract w.r.t. resources required for instantiation.
=> refactor(metadata_calculator): Make config owned

core/bin/external_node/src/main.rs, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/metadata_calculator/mod.rs, core/lib/zksync_core/src/metadata_calculator/recovery/tests.rs, core/lib/zksync_core/src/metadata_calculator/tests.rs
title
- There was some clunky back-and-forth for `MetadataCalculatorModeConfig` <->`MerkleTreeMode` because of the old component confuguration.
- ObjectStore may not be available at time when `MetadataCalculatorModeConfig ` is created (prerequisite for ZK Stack thing).
- Less code!
=> refactor(metadata_calculator): Move ObjectStore out from MetadataCalculatorConfig

core/bin/snapshots_creator/src/creator.rs, core/bin/snapshots_creator/src/tests.rs, core/lib/object_store/src/raw.rs, core/lib/zksync_core/src/basic_witness_input_producer/mod.rs, core/lib/zksync_core/src/eth_sender/aggregator.rs, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/metadata_calculator/mod.rs, core/lib/zksync_core/src/metadata_calculator/tests.rs, core/lib/zksync_core/src/metadata_calculator/updater.rs, core/lib/zksync_core/src/proof_data_handler/mod.rs, core/lib/zksync_core/src/proof_data_handler/request_processor.rs, core/lib/zksync_core/src/state_keeper/io/mempool.rs, core/lib/zksync_core/src/state_keeper/mod.rs, prover/proof_fri_compressor/src/compressor.rs, prover/prover_fri/src/gpu_prover_job_processor.rs, prover/prover_fri/src/main.rs, prover/prover_fri/src/prover_job_processor.rs, prover/prover_fri_gateway/src/api_data_fetcher.rs, prover/witness_generator/src/basic_circuits.rs, prover/witness_generator/src/leaf_aggregation.rs, prover/witness_generator/src/node_aggregation.rs, prover/witness_generator/src/scheduler.rs, prover/witness_vector_generator/src/generator.rs
Changes `Box<dyn ObjectStore>` to `Arc<dyn ObjectStore>`.
`ObjectStore` is meant to be a point of customization in ZK Stack, but with the current approach the only way to get it is via `ObjectStoreFactory`, and it yields objects packed in `Box`, e.g. each instance is unique.
In order to make it customizable, `ObjectStore` should be universally shareable (to allow it to be created once and then copied), and this is the first step toward that.
Later `ObjectStoreFactory` type will be removed completely to grant full control regarding the initial type to the initialization code.
=> refactor(object_store): Wrap ObjectStore in Arc instead of Box

core/bin/external_node/src/main.rs, core/lib/multivm/src/interface/traits/vm.rs, core/lib/multivm/src/interface/types/errors/halt.rs, core/lib/multivm/src/versions/vm_1_3_2/vm.rs, core/lib/multivm/src/versions/vm_boojum_integration/vm.rs, core/lib/multivm/src/versions/vm_latest/vm.rs, core/lib/multivm/src/versions/vm_m5/vm.rs, core/lib/multivm/src/versions/vm_m6/vm.rs, core/lib/multivm/src/versions/vm_refunds_enhancement/vm.rs, core/lib/multivm/src/versions/vm_virtual_blocks/vm.rs, core/lib/multivm/src/vm_instance.rs, core/lib/zksync_core/src/api_server/execution_sandbox/error.rs, core/lib/zksync_core/src/api_server/execution_sandbox/execute.rs, core/lib/zksync_core/src/api_server/tx_sender/mod.rs, core/lib/zksync_core/src/api_server/tx_sender/result.rs, core/lib/zksync_core/src/basic_witness_input_producer/vm_interactions.rs, core/lib/zksync_core/src/state_keeper/batch_executor/mod.rs, core/lib/zksync_core/src/state_keeper/batch_executor/tests/tester.rs, core/lib/zksync_core/src/state_keeper/io/mempool.rs, core/lib/zksync_core/src/state_keeper/mod.rs, core/tests/ts-integration/tests/contracts.test.ts
State keeper and API reject transactions that fail to publish bytecodes
=> feat(state-keeper): Reject transactions that fail to publish bytecodes

core/lib/multivm/src/versions/vm_1_3_2/vm.rs, core/lib/multivm/src/versions/vm_m6/vm.rs
Fixes `inspect_transaction_with_bytecode_compression` for vm_1_3_2 and vm_m6 to work correctly with all tx execution modes
Fix bug
=> fix(vm): `inspect_transaction_with_bytecode_compression` for old VMs

infrastructure/zk/package.json
Bulding the newest image fails with
```
> [12/17] RUN cd /infrastructure/zk && yarn && yarn build && cd /:
26.23 [3/4] Linking dependencies...
26.23 warning " > zksync-web3@0.15.5" has incorrect peer dependency "ethers@~5.7.0".
32.77 [4/4] Building fresh packages...
38.07 success Saved lockfile.
38.08 Done in 37.55s.
38.39 yarn run v1.22.21
38.42 $ tsc
40.31 src/format_sql.ts(3,24): error TS2307: Cannot find module 'sql-formatter' or its corresponding type declarations.
40.34 error Command failed with exit code 1.
40.34 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
Dockerfile:50
--------------------
48 |     
49 |     # Build `zk` tool
50 | >>> RUN cd /infrastructure/zk && yarn && yarn build && cd /
51 |     # Build `local-setup-preparation` …
```
=> chore(zk): adds sql-formatter to zk dependencies

infrastructure/zk/src/init.ts
Currently the run of [local-node](https://github.com/matter-labs/local-node) fails in the logs with:
```
2024-01-15 07:36:06 Deploying TransparentUpgradeableProxy
2024-01-15 07:36:09 TransparentUpgradeableProxy deployed, gasUsed: 678557
2024-01-15 07:36:09 CONTRACTS_L1_ERC20_BRIDGE_PROXY_ADDR=0x1242f30c5c146ed47194BF6D56013A70D9B7C1A0
2024-01-15 07:36:09 Error: TypeError: Cannot read properties of undefined (reading 'address')
2024-01-15 07:36:09     at Deployer.<anonymous> (/contracts/ethereum/src.ts/deploy.ts:318:92)
2024-01-15 07:36:09     at step (/contracts/ethereum/src.ts/deploy.ts:33:23)
2024-01-15 07:36:09     at Object.next (/contracts/ethereum/src.ts/deploy.ts:14:53)
2024-01-15 07:36:09     at /contracts/ethereum/src.ts/deploy.ts:8:71
2024-01-15 07:36:09     at new Promise …
```
=> fix(local-node): deploy erc20 tokens to fix the deployment

infrastructure/zk/src/init.ts
Fixes zk stack cli when spinning up a hyperchain without WETH bridge
Because it was broken. Some changes over the last month removed a param that used to exist
=> chore(hyperchains): fix zk stack cli

.github/workflows/build-prover-template.yml
Job for copy witness-vector-generator between GAR registries
For have access to image from different registries
=> ci: add copying wit-vector-gen image to cross-region registies

core/lib/types/src/fee_model.rs, core/lib/zksync_core/src/api_server/tx_sender/mod.rs, core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/namespaces/debug.rs, core/lib/zksync_core/src/api_server/web3/namespaces/zks.rs, core/lib/zksync_core/src/fee_model.rs, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/state_keeper/io/mempool.rs, core/lib/zksync_core/src/state_keeper/io/tests/mod.rs, core/lib/zksync_core/src/state_keeper/mempool_actor.rs
Before, under big spikes in L1 gas price, it was possible that the state keeper retained the inflated gas price, while the API got the smaller one. In this PR we ensure that the API takes into account the fee params of the latest sealed miniblock
=> feat(api): Consider State keeper fee model input in the API

infrastructure/zk/src/hyperchain_wizard.ts
Remove remapping urls for zk stack initialization
Meanwhile it's good to not expose ports, especially on linux machine. It's hardly complicated to work with it from localhost environment. And we hope, that users won't use our docker-composes for production environment
=> fix(zk-stack): Remove remapping docker containers

core/lib/zksync_core/src/api_server/web3/pubsub.rs, core/lib/zksync_core/src/api_server/web3/tests/filters.rs, core/lib/zksync_core/src/api_server/web3/tests/mod.rs, core/lib/zksync_core/src/api_server/web3/tests/ws.rs
Fixes flaky API server tests:
- `filters::basic_filter_changes` tests (fail when comparing `tx_filter_changes`)
- `ws::log_subscriptions_with_delay` (fails at one of `assert_logs_match` calls).
Flaky tests are obviously bad.
=> test(api): Fix flaky API server tests

core/tests/loadnext/src/account/tx_command_executor.rs, core/tests/loadnext/src/constants.rs, core/tests/loadnext/src/executor.rs, sdk/zksync-rs/src/utils.rs
During the estimation of transaction, the `minAllowance` is set by the user to the paymaster (and then it is fully transferred to the paymaster). Note, however, that the amount of funds to be paid for this operation depends on the size of `minAllowance` (and may also endure additional costs if the write to the slot is an initial one).
=> fix(test): Provide higher min allowance in estimation

Cargo.lock, Cargo.toml, core/lib/vm_utils/Cargo.toml, core/lib/vm_utils/src/lib.rs, core/lib/vm_utils/src/storage.rs, core/lib/zksync_core/Cargo.toml, core/lib/zksync_core/src/basic_witness_input_producer/mod.rs, core/lib/zksync_core/src/state_keeper/extractors.rs, core/lib/zksync_core/src/state_keeper/io/common.rs, core/lib/zksync_core/src/state_keeper/io/mempool.rs, core/lib/zksync_core/src/state_keeper/io/seal_logic.rs, core/lib/zksync_core/src/sync_layer/external_io.rs
For future projects, we have to have some utils for executing txs outside BWIP and zksync_core in general. 
In this PR, I've moved the necessary functions, as is to external crate.
p.s. I've not touched the code by itself, I just moved it.
For correct block execution in different places, e.g. debug methods this code is pretty useful and could be reused without additional dependencies
=> chore(vm): move vm utils outside bwip

Cargo.lock
To make [this](https://github.com/matter-labs/zksync-era/pull/860) PR more efficient, we need the following PRs to be present:
https://github.com/matter-labs/era-zkevm_test_harness/pull/69
https://github.com/matter-labs/era-zkevm_test_harness/pull/68
This lead to some other dependency changes, so I separate out this update to ensure that everything is fine
=> chore(vm): Update zkevm test harness

flake.lock, flake.nix
- update flake.nix for the current release
- also modifiy the standard environment to use the `mold` linker
- add `rustup` and `sqlx-cli`
- reformat with `nixpkgs-fmt`
- add formatter to flake for `nix fmt`
- change flake output `packages` to `devShells`, because that is what this is
- tested the flake
The old version was outdated and the environment with `nix develop --impure` didn't work anymore.
=> chore: update flake.nix for the current release

core/lib/multivm/src/glue/tracers/mod.rs, core/lib/multivm/src/tracers/call_tracer/mod.rs, core/lib/multivm/src/tracers/mod.rs, core/lib/multivm/src/tracers/multivm_dispatcher.rs, core/lib/multivm/src/tracers/old_tracers.rs, core/lib/multivm/src/tracers/storage_invocation/mod.rs, core/lib/multivm/src/tracers/validator/mod.rs, core/lib/multivm/src/versions/vm_1_3_2/vm.rs, core/lib/multivm/src/versions/vm_1_3_2/vm_with_bootloader.rs, core/lib/multivm/src/versions/vm_m6/vm.rs, core/lib/multivm/src/versions/vm_m6/vm_with_bootloader.rs
Support existing tracers for old vms
First step for making tracing on flight instead of saving it in db
=> feat(vm): Support tracers for old vm 

Cargo.lock, core/lib/commitment_utils/Cargo.toml, core/lib/commitment_utils/src/lib.rs, core/lib/types/Cargo.toml, core/lib/types/src/zk_evm_types.rs, core/lib/zksync_core/src/genesis.rs
- Remove `zk_evm_xxx` deps from `zksync_types`
- These deps only needed for a few use cases, so these use cases are implemented elsewhere. Part of initiative of moving heavyweight stuff from `zksync_types`.
=> refactor: Remove zk_evm deps from zksync_types

.github/workflows/build-core-template.yml
This fixes the regression introduced in https://github.com/matter-labs/zksync-era/pull/848/files#diff-76efa69b014ead260f18ba8c40d184f93a2fe72673035d4b48bbaf2f852693a4L75, so Docker login happens only when we want to push image to Docker registry.
This will allow CI to run against forks, where GHA secrets are not available.
=> ci: Logging in to Docker registries only when pushing Docker image

core/lib/dal/migrations/20240129133815_revert_removing_snapshot_recovery_columns.down.sql, core/lib/dal/migrations/20240129133815_revert_removing_snapshot_recovery_columns.up.sql
Creates a new DB migration that restores removed snapshot_recovery columns.
Having non-backward-compatible change leads to potential breaks on various environments.
=> fix(db): Make `snapshot_recovery` migration backward-compatible

core/lib/zksync_core/src/consistency_checker/mod.rs, core/lib/zksync_core/src/reorg_detector/mod.rs, core/lib/zksync_core/src/reorg_detector/tests.rs
Currently, the reorg detector only detects divergence based on the latest local miniblock / L1 batch. This means that if a reorg actually happens, it will only be detected be an EN once the main node catches up to it.
This PR changes this logic as follows. If the main node doesn't contain local node data, it makes sense to check correspondence of the latest L1 batch / miniblock on the main node.
Late reorg detection is less efficient and it may be the reason (or one of the reasons?) EN integration tests in CI frequently fail when gossip-based syncing is enabled.
=> feat(en): Make ENs detect reorgs earlier

core/lib/dal/migrations/20240131123456_add_consensus_fields_for_miniblocks.down.sql, core/lib/dal/migrations/20240131123456_add_consensus_fields_for_miniblocks.up.sql
Added back consensus column to miniblocks table.
There are still binaries deployed which use the column.
=> fix: added consensus column back

core/lib/zksync_core/src/reorg_detector/tests.rs
Fixes flakiness in reorg detector tests introduced in #964.
Flaky tests are bad.
=> test(en): Fix flaky reorg detector tests

Cargo.lock, core/lib/constants/Cargo.toml, core/lib/constants/src/crypto.rs, core/lib/constants/src/ethereum.rs, prover/Cargo.lock
Removes some dead code (and 2 dependencies!) from `zksync_constants`
Dead code bad
=> refactor(constants): Remove dead code from zksync_constants

core/lib/zksync_core/src/metadata_calculator/helpers.rs, core/lib/zksync_core/src/metadata_calculator/mod.rs, core/lib/zksync_core/src/metadata_calculator/recovery/mod.rs, core/lib/zksync_core/src/metadata_calculator/recovery/tests.rs, core/lib/zksync_core/src/metadata_calculator/tests.rs
Makes tree initialization async in metadata calculator (i.e., moves it from the constructor to the `run()` method).
It currently takes ~1m to initialize Merkle tree RocksDB for ENs.
=> feat(merkle-tree): Do not wait for tree initialization when starting node

core/lib/dal/migrations/20240202150009_transaction_batch_index.down.sql, core/lib/dal/migrations/20240202150009_transaction_batch_index.up.sql
=> fix(db): transaction index

core/lib/dal/migrations/20240204153050_add-miniblocks-l1-batch-index.down.sql, core/lib/dal/migrations/20240204153050_add-miniblocks-l1-batch-index.up.sql
We added this index to the DB manually, need to have it in the migrations
=> fix(db): miniblocks index

prover/Cargo.lock
Use version of witness generation that uses a lot less memory.
=> perf: bump harness version

core/lib/dal/src/healthcheck.rs, core/lib/health_check/src/lib.rs
- Time-limits health checks so that the `/health` endpoint doesn't time out w/o returning data.
- Logs timeouts and other health-related data.
Our ENs periodically fail health checks by timing out requests to the `/health` endpoint.
=> feat: Time-limit health checks and log them

prover/Cargo.lock, prover/witness_generator/Cargo.toml, prover/witness_generator/src/main.rs
jemalloc should free memory more aggressively than the system allocator and it was what I used in testing to measure memory use. Behaviour on stage did not correspond with my testing. I hope this will improve things.
=> perf: use jemalloc in witness generator

docker-compose-zkstack-common.yml
Remove redundant postgres command from zk stack docker-compose
=> fix(docker): Fix zk stack start

.github/workflows/ci-core-reusable.yml
- Enable custom-erc20-bridge tests for EN
- Remove `Download zksolc/solc and zkvyper/vyper` step as it's needed only for contract verifier which is not running in EN integration tests job
Test was fixed some time ago and now should be stable
=> chore(ci): Enable custom-erc20-bridge tests for EN

core/lib/state/src/postgres/mod.rs, core/lib/zksync_core/src/api_server/execution_sandbox/apply.rs, core/lib/zksync_core/src/api_server/execution_sandbox/execute.rs, core/lib/zksync_core/src/api_server/execution_sandbox/mod.rs, core/lib/zksync_core/src/api_server/execution_sandbox/testonly.rs, core/lib/zksync_core/src/api_server/execution_sandbox/tests.rs, core/lib/zksync_core/src/api_server/execution_sandbox/validate.rs, core/lib/zksync_core/src/api_server/tx_sender/mod.rs, core/lib/zksync_core/src/api_server/web3/mod.rs, core/lib/zksync_core/src/api_server/web3/namespaces/eth.rs, core/lib/zksync_core/src/api_server/web3/state.rs, core/lib/zksync_core/src/api_server/web3/tests/debug.rs, core/lib/zksync_core/src/api_server/web3/tests/filters.rs, core/lib/zksync_core/src/api_server/web3/tests/mod.rs, core/lib/zksync_core/src/api_server/web3/tests/vm.rs, core/lib/zksync_core/src/api_server/web3/tests/ws.rs, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/state_keeper/mempool_actor.rs, core/lib/zksync_core/src/sync_layer/tests.rs, core/lib/zksync_core/src/utils/mod.rs
- Delays the API server start until there's at least one L1 batch present in the node DB.
- Refactors the VM sandbox so that it's more modular / maintainable.
- Tests VM-related API server methods.
Fixes API server operation when working on the DB after snapshot recovery.
=> feat(api): Start API server after first L1 batch

prover/Cargo.lock, prover/witness_vector_generator/src/generator.rs
This should further lower witness generation memory use, especially during the brief spike when computing RAM circuits.
Also upgrades boojum and shivini because a commit upgrading harness to newer boojum is under my commit in harness.
=> perf: upgrade harness version to improve witness generation memory spike

core/lib/zksync_core/src/api_server/tx_sender/tests.rs, core/lib/zksync_core/src/eth_sender/tests.rs, core/lib/zksync_core/src/fee_model.rs, core/lib/zksync_core/src/l1_gas_price/gas_adjuster/mod.rs, core/lib/zksync_core/src/l1_gas_price/gas_adjuster/tests.rs, core/lib/zksync_core/src/l1_gas_price/mod.rs, core/lib/zksync_core/src/l1_gas_price/singleton.rs, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/state_keeper/io/tests/tester.rs, core/lib/zksync_core/src/state_keeper/mempool_actor.rs, core/lib/zksync_core/src/utils/testonly.rs
- Removes `L1GasPriceProvider` trait.
- Changes the rest of the code to use `BatchFeeModelInputProvider` trait.
`BatchFeeModelInputProvider` is a successor to `L1GasPriceProvider` and it defines a real interface that modules should use.
`L1GasPriceProvider` was only used to instantiate `BatchFeeModelInputProvider`, so it was generally useless as an abstraction, while still increasing the cognitive complexity.
=> refactor: Get rid of L1GasPriceProvider trait

core/lib/zksync_core/src/state_keeper/io/seal_logic.rs
Added a logging event when we encounter a tx that spent more than 10m in mempool.
Part of the investigation on why there are spikes in `transaction_inclusion_delay` metric. Generally inclusion delay tends to be 1-2s, but occasionally spikes up to several hours. Hopefully this log gives us insight into whether there are legitimate transactions that spend a significant amount of time in the pool or the problem is somewhere else.
=> chore: log when tx spends more than 10m in mempool

core/lib/multivm/src/tracers/call_tracer/metrics.rs
Add buckets 128-1024
To have better understanding of stack depth
=> chore: Add more buckets to CallTracer metrics

.github/workflows/ci.yml, docker-compose.yml
port 9090 is used for prometheus, and it's likely that the host machine runs prometheus as well. I don't think we need to export it from docker.
Same applies to 8080
=> fix(local env): don't expose some ports

Cargo.lock, core/lib/snapshots_applier/Cargo.toml, core/lib/snapshots_applier/src/lib.rs, core/lib/snapshots_applier/src/tests/mod.rs, core/lib/snapshots_applier/src/tests/utils.rs
- Modifies DB recovery logic so that it retries on failures.
- Parallelizes DB recovery using a semaphore (i.e., similarly to snapshot recovery in some components).
- Retries on transient errors reduce the chance of the recovery getting stuck.
- Parallelizing DB recovery can speed it up.
=> feat(en): Make snapshots applier resilient and process storage log chunks in parallel

core/lib/zksync_core/src/eth_watch/client.rs, core/lib/zksync_core/src/eth_watch/mod.rs, core/lib/zksync_core/src/lib.rs, core/node/node_framework/examples/main_node.rs, core/node/node_framework/src/implementations/layers/fee_input.rs, core/node/node_framework/src/implementations/layers/mod.rs, core/node/node_framework/src/implementations/layers/pk_signing_eth_client.rs, core/node/node_framework/src/implementations/layers/query_eth_client.rs, core/node/node_framework/src/implementations/resources/eth_interface.rs, core/node/node_framework/src/implementations/resources/mod.rs
- Adds resources for query and signing ETH clients
- Adds layers that provide these resources
- Instantiating a certain client shouldn't be the responsibility of other layers.
- Better incapsulation of concepts.
=> feat(node_framework): Resources and layers for ETH clients

core/lib/dal/src/connection/mod.rs, core/node/node_framework/src/implementations/resources/pools.rs, core/node/node_framework/src/resource/lazy_resource.rs, core/node/node_framework/src/resource/resource_collection.rs, core/node/node_framework/src/resource/unique.rs, core/node/node_framework/src/service/context.rs, core/node/node_framework/src/service/mod.rs
- Adds more logs when the node is being configured. We can certainly improve it further (e.g. print task name in resource-related logs or use prettier type output for Unique), but I think it's a good starting point.
- Logs are helpful for debugging, especially in dynamic systems like the new framework.
New logs look roughly as follows:
=> chore(node_framework): Emit logs on context/resource access

core/bin/external_node/src/main.rs, core/lib/zksync_core/src/consensus/testonly.rs, core/lib/zksync_core/src/state_keeper/batch_executor/main_executor.rs, core/lib/zksync_core/src/state_keeper/batch_executor/mod.rs, core/lib/zksync_core/src/state_keeper/batch_executor/tests/tester.rs, core/lib/zksync_core/src/state_keeper/keeper.rs, core/lib/zksync_core/src/state_keeper/mod.rs, core/lib/zksync_core/src/state_keeper/tests/mod.rs, core/lib/zksync_core/src/state_keeper/tests/tester.rs, core/node/node_framework/examples/main_node.rs, core/node/node_framework/src/implementations/layers/state_keeper/main_batch_executor.rs, core/node/node_framework/src/implementations/layers/state_keeper/mod.rs, core/node/node_framework/src/implementations/resources/state_keeper.rs
- Does a set of renames:
- `L1BatchExecutorBuilder` -> `BatchExecutor`
- `MainBatchExecutorBuilder` -> `MainBatchExecutor`
- `BatchExecutor` -> `CommandReceiver` (as it's just a "processing" part of `MainBatchExecutor`)
- Similar changes in the framework.
- Moves the implementation of `MainBatchExecutor` to a separate file.
- Removes some temporary misplaced constructor for `BatchExecutorHandle`.
- Less Enterprise™
- Better logical structure
=> refactor(state_keeper): Rename batch executor family of types

prover/Cargo.lock, prover/proof_fri_compressor/Cargo.toml, prover/proof_fri_compressor/src/compressor.rs, prover/prover_fri/src/gpu_prover_job_processor.rs, prover/prover_fri/src/main.rs, prover/prover_fri/src/prover_job_processor.rs, prover/prover_fri/src/socket_listener.rs, prover/prover_fri/tests/basic_test.rs, prover/prover_fri_types/src/lib.rs, prover/vk_setup_data_generator_server_fri/Cargo.toml, prover/vk_setup_data_generator_server_fri/src/commitment_generator.rs, prover/vk_setup_data_generator_server_fri/src/commitment_utils.rs, prover/vk_setup_data_generator_server_fri/src/keystore.rs, prover/vk_setup_data_generator_server_fri/src/lib.rs, prover/vk_setup_data_generator_server_fri/src/main.rs, prover/vk_setup_data_generator_server_fri/src/setup_data_generator.rs, prover/vk_setup_data_generator_server_fri/src/tests.rs, prover/vk_setup_data_generator_server_fri/src/utils.rs, prover/witness_generator/src/leaf_aggregation.rs, prover/witness_generator/src/node_aggregation.rs, prover/witness_generator/src/scheduler.rs, prover/witness_vector_generator/src/generator.rs
* Adding keystore object as one interface to handle reading and writing of the verification and setup keys
* As a side effect, also removing dependency on the old test_harness version from key generator
* This will allow us to specify different (non default) directories for verification and setup keys in the future.
=> feat(prover): adding keystore object to handle reading and writing of prover keys

infrastructure/zk/src/env.ts, infrastructure/zk/src/hyperchain_wizard.ts, infrastructure/zk/src/init.ts
=> fix(zk_stack): Use deployer private key and remove create2 address

core/bin/contract-verifier/src/verifier.rs, core/bin/contract-verifier/src/zksolc_utils.rs, docker/contract-verifier/Dockerfile
Contract verifier allows any fields in standard json input settings and passes them to zksolc.
New fields are added to settings from time to time, contract verifier should just accept them and pass to zksolc.
=> fix(contract-verifier): allow other zksolc settings

infrastructure/zk/src/hyperchain_wizard.ts
=> fix(zk_stack): Use correct owner and db url

README.md
https://opensource.org/license/mit/ -> https://opensource.org/blog/license/mit/
CI is broken, seems like https://opensource.org changed the base URL for the license pages
=> chore: fix MIT license link

docker/witness-generator/Dockerfile
=> fix(witness_generator): Add trusted setup to wit gens

docs/guides/setup-dev.md
* nit: there was a mismatch in instructions of setting node version vs yarn version
* make more clear
=> chore: slightly change instructions in node version to match yarn

infrastructure/zk/src/status.ts
* Database was fully split - with prover data now living in separate one
* Updating `zk status prover` to work
* zk status prover is helpful for local debugging of prover progress.
=> fix(zk): Adapting zk status prover to new Database layout

Cargo.lock, core/bin/external_node/src/config/mod.rs, core/bin/external_node/src/main.rs, core/lib/config/src/configs/api.rs, core/lib/config/src/testonly.rs, core/lib/env_config/src/api.rs, core/lib/health_check/Cargo.toml, core/lib/health_check/README.md, core/lib/health_check/src/lib.rs, core/lib/health_check/src/metrics.rs, core/lib/health_check/src/tests.rs, core/lib/protobuf_config/src/api.rs, core/lib/protobuf_config/src/proto/api.proto, core/lib/zksync_core/src/api_server/web3/mod.rs, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/reorg_detector/mod.rs, core/lib/zksync_core/src/reorg_detector/tests.rs, prover/Cargo.lock
- Adds `HeathStatus::ShuttingDown` set immediately after a component receives a termination signal. Makes the `/health` endpoint conforming to K8s readiness probe expectations.
- Makes slow / hard time limits for health checks configurable and decreases their values by default.
- Adds metric for slow, timed out and dropped health checks.
Improves healthcheck observability.
=> feat(healthcheck): Various healthcheck improvements

core/lib/config/src/configs/eth_sender.rs, core/lib/config/src/testonly.rs, core/lib/env_config/src/eth_sender.rs, core/lib/protobuf_config/src/eth_sender.rs, core/lib/protobuf_config/src/proto/eth_sender.proto, core/lib/zksync_core/src/state_keeper/seal_criteria/conditional_sealer.rs, core/lib/zksync_core/src/state_keeper/seal_criteria/criteria/pubdata_bytes.rs, etc/env/base/chain.toml, etc/env/base/eth_sender.toml
Add the pubdata sending method to eth sender config
We want an easy way for indicating to the server what DA layer should be used for pubdata
=> feat(config): add pubdata sending method to config

Cargo.lock, core/lib/config/src/configs/eth_sender.rs, core/lib/config/src/testonly.rs, core/lib/env_config/src/eth_sender.rs, core/lib/eth_client/Cargo.toml, core/lib/eth_client/src/clients/generic.rs, core/lib/eth_client/src/clients/http/query.rs, core/lib/eth_client/src/clients/http/signing.rs, core/lib/eth_client/src/clients/mock.rs, core/lib/eth_client/src/lib.rs, core/lib/eth_client/src/types.rs, core/lib/protobuf_config/src/eth_sender.rs, core/lib/protobuf_config/src/proto/eth_sender.proto, core/lib/zksync_core/src/eth_sender/tests.rs, core/lib/zksync_core/src/l1_gas_price/gas_adjuster/metrics.rs, core/lib/zksync_core/src/l1_gas_price/gas_adjuster/mod.rs, core/lib/zksync_core/src/l1_gas_price/gas_adjuster/tests.rs, core/lib/zksync_core/src/l1_gas_price/singleton.rs, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/state_keeper/io/tests/tester.rs, core/lib/zksync_core/src/state_keeper/metrics.rs, core/node/node_framework/examples/main_node.rs, core/node/node_framework/src/implementations/layers/fee_input.rs
=> feat(gas-adjuster): gas adjuster for EIP4844

core/lib/zksync_core/src/sync_layer/fetcher.rs
Only the last miniblock in batch can have 0 txs. Fail fast if the main node returned wrong value 
It allows to find discrepancy faster
=> fix(en): fail fast if we don't request correct number of txs from man node

docs/guides/advanced/01_initialization.md, docs/guides/advanced/02_deposits.md, docs/guides/advanced/03_withdrawals.md
This PR contains small fixes to the `guides` docs. Mostly around container names / cli syntax.
=> docs: small doc fixes

core/bin/external_node/src/config/mod.rs, core/bin/external_node/src/config/tests.rs, core/bin/external_node/src/main.rs
This pull request addresses the need to dynamically set the L1CommitGeneratorMode of the external node based on the configuration value l1_batch_commit_data_generator_mode in the etc/env/ext-node.toml file. If the configuration value is set, the external node will be configured for Validium; otherwise, the default mode will be Rollup.
Changes Made
Added logic to check for the presence of l1_batch_commit_data_generator_mode in etc/env/ext-node.toml.
If the value is set, the L1CommitGeneratorMode of the external node is set to "validium."
If the value is not set, the default mode "rollup" is used.
Users can manually update the configuration by adding l1_batch_commit_data_generator_mode="Validium" to the ext-node.toml file.
Need to add Valiidium support to EN
=> feat(Validium): add validium support for external node

core/lib/config/src/configs/chain.rs, core/lib/env_config/src/chain.rs
This pull request addresses the issue regarding the `l1_batch_commit_data_generator_mode` field in the `StateKeeperConfig` struct. The issue stems from the absence of an explicit default value and the lack of `Option` marking, potentially causing the node to enter a crash loop if deployed to an existing environment without prior configuration updates.
Resolves #168.
To resolve this issue, the following changes have been implemented:
1. **Using `serde` with Default Value:** The `serde` attribute has been applied to the `L1BatchCommitDataGeneratorMode` enum, setting `Rollup` as the default value. This ensures that if the field is not explicitly provided in the configuration, `Rollup` will be used by default.
2. **Backward Compatibility:** The solution is designed to be backward-compatible, …
=> fix(Validium): Make `l1_batch_commit_data_generator_mode` a non-mandatory attribute

core/lib/multivm/src/utils.rs
Fix match clause in `get_max_gas_per_pubdata_byte`. `crate::vm_latest::constants::MAX_GAS_PER_PUBDATA_BYTE == crate::vm_1_4_1::constants::MAX_GAS_PER_PUBDATA_BYTE` so it should have no effect, but it's still a bug
=> fix(vm): fix match clause in `get_max_gas_per_pubdata_byte`

core/lib/zksync_core/src/l1_gas_price/gas_adjuster/mod.rs, core/lib/zksync_core/src/l1_gas_price/singleton.rs, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/native_token_fetcher/mod.rs
Implement a struct which implements `ConversionRateFetcher` that always returns `1` when `conversion_rate()`.
Make `Erc20Fetcher` mandatory.
=> feat(Gas Oracle): Make the Erc20 Fetcher mandatory and have a no-op implementation

core/lib/eth_signer/src/json_rpc_signer.rs, core/lib/eth_signer/src/lib.rs, core/lib/eth_signer/src/pk_signer.rs, core/lib/types/src/tx/primitives/packed_eth_signature.rs, core/tests/loadnext/src/corrupted_tx.rs
Removes public APIs that allow signing arbitrary messages.
Replaces https://github.com/matter-labs/zksync-era/pull/482
The functionality to sign arbitrary messages was used in zkSync Lite (where it was inherited from), but is not needed for zkSync Era.
Moreover, the implementation is controversial, e.g. we can either add or not add the Ethereum standard prefix, and without a use case we don't really have a justification for either option.
Overall, it reduces the surface of public API we commit to support.
=> feat: Remove methods to sign an arbitraty message

core/lib/zksync_core/src/l1_gas_price/singleton.rs, core/lib/zksync_core/src/native_token_fetcher/mod.rs
Remove `Error` struct that holds `anyhow::Error` inside.
Keep error structure clean.
=> feat(Gas Oracle): Use normal anyhow::Error for the `NativeErc20Fetcher`

core/lib/dal/src/instrument.rs, core/lib/dal/src/snapshots_creator_dal.rs
A  way to disable slow query reporting on a per-query granularity
Slow queries generate lots of spam and we expect some queries to be slow.
=> feat: A way to disable slow query logging for some queries

core/lib/config/src/configs/fri_prover_group.rs, core/lib/env_config/src/fri_prover_group.rs, etc/env/base/fri_prover_group.toml
255 corresponds to EIP4844. This is added to the group of expected circuits (base circuit as of 4844). Additionally, fixed panicing config by turning it into an Result.
This is needed for 4844 release and prevents outages caused by the part of the config that was touched.
=> fix: Add EIP4844 to fri_prover_group_config

core/lib/zksync_core/src/sync_layer/client.rs
Decreasing EN concurrency so that it doesn't trigger 429 errors
It's mostly a band-aid until we fix it in a more organized way
=> feat: change EN main node fetcher concurrency factor

infrastructure/zk/src/env.ts
If a config value with spaces is not wrapped into double quotes, such config will get loaded by the server incorrectly leading to unpredictable system behaviour.
=> fix: wrap config values with spaces into quotes

.github/workflows/build-docker-from-tag.yml
This prevents us from releasing a new version. failed build: https://github.com/matter-labs/zksync-era/actions/runs/8116928319
=> fix(ci): Fix syntax error in `build-docker-image-from-tag` workflow yaml

core/lib/zksync_core/src/consistency_checker/mod.rs
ConsistencyChecker shouldn't try enconding pubdata in Calldata mode, if pubdata doesn't fit into one blob
=> fix(consistency_checker): Fix consistency checker for large pubdata

core/lib/dal/.sqlx/query-bab1857df66bbef57705ae7796161f3a71f5c6737e08745a37b41b22f4dfd030.json, core/lib/dal/src/blocks_dal.rs, core/lib/zksync_core/src/eth_sender/aggregator.rs
=> fix(aggregator): correct order of processing of prove transactions

Cargo.lock, core/bin/external_node/Cargo.toml, core/bin/external_node/src/main.rs, core/lib/zksync_core/src/consistency_checker/mod.rs, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/utils/mod.rs
This PR:
- Adds a cross-check of the commit data generation mode (Validium or Rollup) between the deployed L1 contracts and the config set in the server.
- Updates the ConsistencyChecker `new` method to receive an `impl EthInterface` instead of receiving an Ethereum client URL to instantiate one.
- Moves the function that contains the main logic to `utils` module given that it is used both in EN and in `zksync_core`.
The mode was being cross-checked in the server, but it should also be cross-checked in the EN.
Unit tests for the function in question will be added in the `zksync_core` module in another PR
=> feat(Validium): Commit data generation mode cross-check in EN

infrastructure/zk/src/init.ts
Use https urls instead of ssh, so that zk works on machines that don't have their ssh keys added to GitHub
=> fix: use git https urls in zk

core/lib/state/src/postgres/mod.rs, core/lib/zksync_core/src/api_server/execution_sandbox/mod.rs, core/lib/zksync_core/src/api_server/execution_sandbox/tests.rs, core/lib/zksync_core/src/api_server/tx_sender/tests.rs
Don't panic in `PostgresStorageCaches::schedule_values_update()` if the values cache was not configured.
This leads to panics if the cache is disabled via config. Ignoring the update looks like more reasonable behavior.
=> fix(api): Fix panics in API server if storage values cache is disabled

Cargo.lock, prover/Cargo.lock, prover/prover_fri/src/prover_job_processor.rs, prover/prover_fri/src/utils.rs, prover/prover_fri_types/src/lib.rs, prover/witness_generator/src/basic_circuits.rs, prover/witness_generator/src/utils.rs, prover/witness_vector_generator/src/generator.rs
* Start using the new version of the 1.4.2 test harness, that doesn't export generics
* This should improve the compilation speed.
=> feat: Start using a new test harness interface without generics

Cargo.lock, core/bin/system-constants-generator/Cargo.toml, core/bin/system-constants-generator/README.md, core/bin/system-constants-generator/src/main.rs, core/bin/system-constants-generator/src/utils.rs
* Replacing old evm_test_harness with opcode defs
* To improve compilation speed, and not depend on unneeded methods.
=> chore: Replace  test harness with just opcode_defs in constants generator

Cargo.lock, core/lib/commitment_utils/Cargo.toml, core/lib/commitment_utils/src/lib.rs, core/lib/l1_contract_interface/Cargo.toml, core/lib/l1_contract_interface/src/i_executor/commit/kzg/mod.rs, core/lib/l1_contract_interface/src/i_executor/commit/kzg/tests/mod.rs, core/lib/l1_contract_interface/src/i_executor/commit/kzg/trusted_setup.rs, core/lib/multivm/Cargo.toml, core/lib/multivm/src/lib.rs, core/lib/multivm/src/versions/vm_1_4_1/tracers/circuits_capacity.rs, core/lib/multivm/src/versions/vm_1_4_1/tracers/pubdata_tracer.rs, core/lib/multivm/src/versions/vm_1_4_1/vm.rs, core/lib/multivm/src/versions/vm_boojum_integration/tests/circuits.rs, core/lib/multivm/src/versions/vm_boojum_integration/tracers/circuits_capacity.rs, core/lib/multivm/src/versions/vm_boojum_integration/tracers/pubdata_tracer.rs, core/lib/multivm/src/versions/vm_boojum_integration/vm.rs, core/lib/multivm/src/versions/vm_latest/constants.rs, core/lib/multivm/src/versions/vm_latest/tracers/circuits_capacity.rs, core/lib/multivm/src/versions/vm_latest/tracers/pubdata_tracer.rs, core/lib/multivm/src/versions/vm_latest/vm.rs, core/lib/prover_interface/Cargo.toml, core/lib/prover_interface/src/outputs.rs, core/lib/zksync_core/src/genesis.rs, prover/Cargo.lock, prover/proof_fri_compressor/Cargo.toml, prover/proof_fri_compressor/src/compressor.rs, prover/witness_generator/src/tests.rs
* Now moving version 1.4.0, 1.4.1 and 1.4.2 to use the new circuit_sequencer_api
* To improve compilation speeds.
=> feat: Moving 1.4.x to use the circuit_api

.github/workflows/vm-perf-comparison.yml, core/tests/vm-benchmark/Cargo.toml, core/tests/vm-benchmark/harness/src/instruction_counter.rs, core/tests/vm-benchmark/harness/src/lib.rs, core/tests/vm-benchmark/src/compare_iai_results.rs, core/tests/vm-benchmark/src/instruction_counts.rs
This makes the automatic VM performance reporting also report changes in number of instructions executed. Those changes can be used to identify cases where performance hasn't actually changed but gas prices have changed.
=> test: add info about how many instructions it takes to run benchmarks

core/bin/external_node/src/main.rs, core/lib/config/src/configs/api.rs, core/lib/health_check/src/lib.rs, core/lib/merkle_tree/src/errors.rs, core/lib/web3_decl/src/namespaces/zks.rs, core/lib/zksync_core/src/api_server/tree/mod.rs, core/lib/zksync_core/src/api_server/tree/tests.rs, core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/mod.rs, core/lib/zksync_core/src/api_server/web3/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/state.rs, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/metadata_calculator/helpers.rs, core/lib/zksync_core/src/metadata_calculator/mod.rs, core/lib/zksync_core/src/metadata_calculator/recovery/tests.rs, core/node/node_framework/examples/main_node.rs, core/node/node_framework/src/implementations/layers/web3_api/mod.rs, core/node/node_framework/src/implementations/layers/web3_api/server.rs, core/node/node_framework/src/implementations/layers/web3_api/tree_api_client.rs, core/node/node_framework/src/implementations/resources/web3_api.rs
Enables Merkle tree client on EN so that `zks_getProof` can work properly.
This endpoint won't produce overhead and could be useful for some EN operators. Also, it allows checking Merkle tree consistency after snapshot recovery more easily.
=> feat(en): Enable Merkle tree client on EN

core/lib/zksync_core/src/eth_sender/eth_tx_manager.rs
It has been noted that simply doubling previous prices in case of blob transactions may not be a good enough method to get them actually included. While doubling the prices for replacement transactions is a _necessary_ thing to do it may not be enough, consider a situation where an initial blob gas price has been for any reason estimated to be very low. After a couple of operations of resending the growth of normal fees would quickly outpace the growth of the blob fees:
```
"maxFeePerBlobGas": "0x680",
"maxFeePerGas": "0x6b864500fc0",
"maxPriorityFeePerGas": "0x2540be4000",
```
But this does not reflect the current effective blob (or normal 1559) prices onchain. Because at this moment the actual blob prices may be at `"maxFeePerBlobGas": "0x54c8a469d"` already. So as a solution: take the …
=> fix(eth-sender): adjust the blob tx fees taking into account the current prices

core/lib/zksync_core/src/l1_gas_price/gas_adjuster/mod.rs
Use `internal_pubdata_pricing_multiplier` for pubdata price calculation
This is the correct multiplier to use in this case
=> fix(gas-adjuster): Use `internal_pubdata_pricing_multiplier` for pubdata price calculation

flake.lock, flake.nix
Build the rust binaries with the nix flake.
To do that, we have to vendor zksync-era with a custom patched `cargo`... **sigh** See https://github.com/matter-labs/zksync-era/issues/1086
To build the rust components with this flake, first run:
```
$ nix build .#cargoDeps
```
set `cargoHash` in `flake.nix` to the result of the build then
```
$ nix build .#zksync_server
```
or
```
$ nix build .#zksync_server.contract_verifier
$ nix build .#zksync_server.external_node
$ nix build .#zksync_server.server
$ nix build .#zksync_server.snapshots_creator
$ nix build .#zksync_server.block_reverter
```
To enter the development shell, run:
```
$ nix develop --impure
```
To vendor the dependencies manually, run:
```
$ nix shell .#cargo-vendor -c cargo vendor --no-merge-sources
```
=> chore: build rust binaries with nix flake

core/lib/merkle_tree/src/storage/rocksdb.rs, core/lib/storage/src/db.rs, core/lib/zksync_core/src/metadata_calculator/helpers.rs
Added a field to RocksDBOptions, which is used as an argument to rocksdb::Options::set_max_open_files().
This allows Merkle tree users to limit the number of open files required by RocksDB, which otherwise grows beyond normal OS limits (8192 files) and requires large amounts of memory (currently, beyond 32GB).
- current (integration) tests run as before
- external program requiring the change is now running
- all new fields and methods are documented
- no links added (nor modified)
=> feat(db): Configurable maximum number of open RocksDB files

checks-config/era.dic, core/lib/zksync_core/src/utils/mod.rs
1. Add a set of unit tests for `ensure_l1_batch_commit_data_generation_mode`, making sure the right kind of errors or lack thereof are returned for a given set of parameters and L1 responses. It required a mock for `EthInterface` to return the needed values.
2. Annotate `ensure_l1_batch_commit_data_generation_mode` to make sure we use the result, otherwise we may end up in inconsistent state.
QA
=> feat(Validium): unit tests for `ensure_l1_batch_commit_data_generation_mode`

docs/guides/repositories.md
Update url for `zksync-lite-docs` repo
Previous URL was incorrect and causing 404 errors for link checker
=> chore(docs): Update url for zksync-lite-docs

core/tests/ts-integration/src/env.ts, infrastructure/zk/src/init.ts
Re-add `createVolumes()` function to make `zk init` work and `bridgeAddress` so the `zk test i server` runs.
=> fix(kl-factory): fix init and zk test i server

core/lib/dal/.sqlx/query-26bc9b315c4c57bcff1f46da956727233a36e018fe5c0651995b876053a6a054.json, core/lib/dal/src/events_dal.rs
Fix calculation for `tx_index_in_l1_batch` in `get_vm_events_for_l1_batch` method.
=> fix(dal): correct `tx_index_in_l1_batch` in `get_vm_events_for_l1_batch`

core/node/node_framework/src/service/mod.rs, core/node/node_framework/src/service/tests.rs
Changes the logic of the framework so that it's OK to call `add_layer` with the same layer multiple times: the corresponding layer will only be stored once.
It may be handy if the same layer (e.g. think gas adjuster) is a prerequisite for multiple other layers: we can simply bundle them together without having to worry whether any other layer adds it.
It will be useful for components-based system.
=> feat(node_framework): Only store each wiring layer once

Cargo.lock, checks-config/era.dic, core/node/node_framework/Cargo.toml, core/node/node_framework/examples/main_node.rs, core/node/node_framework/src/implementations/layers/mod.rs, core/node/node_framework/src/implementations/layers/sigint.rs
Adds a task that handles SIGINT (aka ctrl+c), propagating the signal to the `ZkStackService` instead of shutting the node down immediately.
- Graceful shutdown.
- Replicating the current behavior.
=> feat(node_framework): Add a task to handle sigint

.github/workflows/build-prover-template.yml, docker/proof-fri-compressor/Dockerfile, docker/prover-fri-gateway/Dockerfile, docker/prover-fri/Dockerfile, docker/prover-gpu-fri/Dockerfile, docker/witness-generator/Dockerfile, docker/witness-vector-generator/Dockerfile
WIP ⚠️ 
Removes a hack that generated a temporary `Cargo.toml` for prover workspace.
Supposedly not needed anymore.
=> ci: Remove prover workspace hack in CI

core/tests/ts-integration/package.json, package.json
Changes the zkSync-ethers package to the zkSync-SDK repo version.
With the recent merges on that repository, the tests are now fixed.
=> fix(kl-factory/integration-tests): custom accounts

core/bin/external_node/src/main.rs, core/lib/config/src/configs/chain.rs, core/lib/config/src/testonly.rs, core/lib/env_config/src/chain.rs, core/lib/protobuf_config/src/chain.rs, core/lib/protobuf_config/src/proto/chain.proto, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/state_keeper/batch_executor/main_executor.rs, core/lib/zksync_core/src/state_keeper/batch_executor/mod.rs, core/lib/zksync_core/src/state_keeper/batch_executor/tests/mod.rs, core/lib/zksync_core/src/state_keeper/batch_executor/tests/tester.rs, core/lib/zksync_core/src/state_keeper/io/output_handler.rs, core/lib/zksync_core/src/state_keeper/io/persistence.rs, core/lib/zksync_core/src/state_keeper/keeper.rs, core/lib/zksync_core/src/state_keeper/mod.rs, core/lib/zksync_core/src/state_keeper/tests/tester.rs, core/lib/zksync_core/src/sync_layer/sync_state.rs, core/node/node_framework/src/implementations/layers/state_keeper/main_batch_executor.rs, core/node/node_framework/src/implementations/layers/state_keeper/mempool_io.rs, etc/env/base/chain.toml
`WitnessBlockState` is only used in the state keeper persistence logic as a temporary measure before the BWIP component is fully implemented.
Removing this logic simplifies state keeper persistence interfaces.
=> feat(state-keeper): Remove `WitnessBlockState` generation from state keeper

core/bin/external_node/src/config/mod.rs, core/lib/config/src/configs/api.rs, core/lib/zksync_core/src/api_server/web3/mod.rs
Follow-up on #1078 
Websocket API does not suffer from the issues described in the original PR, hence it can and should be used by users.
=> fix(api): `filters_disabled` should only affect HTTP endpoints

core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/mod.rs, core/lib/zksync_core/src/api_server/web3/tests/filters.rs
Changes the error code for `Web3Error::NotImplemented` from `InternalError` to `MethodNotFound`.
Better representation of the nature of an error. Useful for better error-handling on the client side.
=> fix(api): Change error code for Web3Error::NotImplemented

core/lib/zksync_core/src/api_server/contract_verification/api_decl.rs
Sets permissive CORS for contract verifier api server
To have same cors as we had with actix
=> fix(contract-verifier-api): permissive cors for contract verifier api server

core/lib/zksync_core/src/block_reverter/mod.rs, infrastructure/zk/src/init.ts
Fixes a few problems:
- Removes `--remote` flag added to submodule update in https://github.com/matter-labs/zksync-era/pull/1461. This flag would override the currently used submodule version, which is incorrect.
- Adds a fallback to latest block in the block reverter (it seems, in `reth` pending block doesn't always exist).
There are other problems with CI that are to be solved, but it's better to fix something ASAP.
Flaky CI bad
=> fix(CI): Less flaky CI

core/lib/dal/src/blocks_dal.rs, core/lib/zksync_core/src/commitment_generator/mod.rs, core/lib/zksync_core/src/genesis.rs, core/lib/zksync_core/src/state_keeper/io/seal_logic.rs
`events_queue` is not read from and data is no longer inserted there.
`events` table is sufficient.
=> feat: soft removal of `events_queue` table 

core/bin/snapshots_creator/src/creator.rs, core/bin/snapshots_creator/src/tests.rs, core/lib/snapshots_applier/src/lib.rs, core/lib/snapshots_applier/src/tests/utils.rs, core/lib/types/src/api/mod.rs, core/lib/types/src/snapshots.rs, core/lib/zksync_core/src/api_server/web3/namespaces/snapshots.rs, core/tests/snapshot-recovery-test/tests/snapshot-recovery.test.ts, etc/env/ext-node-validium-docker.toml
Reduces the amount of data in `SnapshotHeader` returned by the relevant RPC method. This missing data is fetched from the main node.
Right now, the snapshot header returned by JSON-RPC API includes the entire L1BatchWithMetadata. Most of this information is not used, and the data itself may be not present in DB! Indeed, new snapshots are created for the penultimate L1 batch. It is guaranteed to have metadata calculator run on it (i.e., have a state hash computed), but not the commitment generator. The corresponding errors have been observed in CI runs, and in local testing.
=> fix(en): Reduce amount of data in snapshot header

core/lib/eth_client/src/clients/http/query.rs, core/lib/eth_client/src/types.rs
Uses local FeeHistory type that has optional `base_fee_per_gas`.
See https://github.com/alloy-rs/alloy/blob/main/crates/rpc-types/src/eth/fee.rs#L52 (reth uses alloy-rpc-types)
Tests are flaky because of this, e.g. https://github.com/matter-labs/zksync-era/actions/runs/8521600793/job/23340115243#step:14:26
=> fix(eth-client): Use local FeeHistory type

Cargo.lock, checks-config/links.json
The `era-compiler-llvm` will be open sourced soon. For now we'll just ignore it in the CI
=> fix: Fix CI by ignoring "era-compiler-llvm" and bumping h2

core/lib/multivm/src/versions/vm_1_4_2/tests/circuits.rs, core/lib/multivm/src/versions/vm_1_4_2/tracers/circuits_capacity.rs, core/lib/multivm/src/versions/vm_1_4_2/tracers/circuits_tracer.rs, core/lib/multivm/src/versions/vm_latest/tests/circuits.rs, core/lib/multivm/src/versions/vm_latest/tracers/circuits_capacity.rs, core/lib/multivm/src/versions/vm_latest/tracers/circuits_tracer.rs
Increases log demuxer cycles on far calls
Storage is read when applying far call: https://github.com/matter-labs/era-zk_evm/blob/v1.5.0/src/opcodes/execution/far_call.rs#L159, this adds one query to a log query queue
=> fix(vm): Increase log demuxer cycles on far calls

core/lib/constants/src/contracts.rs, core/lib/zksync_core/src/genesis.rs, core/lib/zksync_core/src/state_keeper/batch_executor/tests/tester.rs, core/lib/zksync_core/src/state_keeper/io/tests/tester.rs, infrastructure/zk/src/server.ts
All chains are initialized with the same chain id, and then we have to set it properly. 
It was hardcoded in scripts before, now it moved to server
=> hardcode initial chain id

core/lib/env_config/src/contract_verifier.rs
Makes contract verifier config test use the correct env var name
Test is failing for me locally, no idea how it works on CI though
=> fix: contract verifier config test

infrastructure/protocol-upgrade/src/l2upgrade/transactions.ts
Supporting constructor call for selected system contracts' forced deployments
In preparation for the v1.5.0 upgrade, where we'll have to override the `blockGasLimit` variable in the `SystemContext` contract
=> feat: Support constructor call in protocol upgrade script

core/tests/revert-test/tests/revert-and-restart-en.test.ts, core/tests/revert-test/tests/revert-and-restart.test.ts, core/tests/ts-integration/src/reporter.ts, core/tests/ts-integration/tests/api/web3.test.ts
Fixes a couple of errors in integration tests with known causes.
- Errors in `getFilterChanges` for pending transactions are caused by introducing the mempool cache. The test makes too strict assumptions as to the transaction latency, which can be easily relaxed.
- The revert test somewhat frequently fails because an L1 transaction response for the deposit is null. The exact cause is unknown (maybe, switching to reth?), but it seems to be fixable by retrying the transaction retrieval until it's not null.
Failing integration tests slow down development.
=> test: Fix easy to fix integration tests

core/lib/merkle_tree/src/domain.rs, core/lib/merkle_tree/tests/integration/domain.rs, core/lib/zksync_core/src/metadata_calculator/helpers.rs, core/lib/zksync_core/src/metadata_calculator/metrics.rs, core/lib/zksync_core/src/metadata_calculator/updater.rs
Removes initial_writes and repeated_writes from tree metadata. Witness object is used in tests to perform needed checks.
initial_writes and repeated_writes weren't used except for testing and consistency check purposes
=> chore: Remove initial_writes and repeated_writes from tree metadata

.github/workflows/protobuf.yaml
Weakened protobuf compatibility check from FILE (backward compatibility of generated code) to WIRE_JSON (backward/forward compatibility of generated JSON and binary messages). This will allow us for removing fields from the schema by [reserving ](https://protobuf.dev/programming-guides/proto3/#fieldreserved) the removed field and number.
=> chore: weakened protobuf compatibility check

docs/guides/external-node/00_quick_start.md, docs/guides/external-node/docker-compose-examples/grafana/provisioning/dashboards/General.json, docs/guides/external-node/docker-compose-examples/grafana/provisioning/dashboards/default.yml, docs/guides/external-node/docker-compose-examples/grafana/provisioning/datasources/prometheus.yml, docs/guides/external-node/docker-compose-examples/mainnet-external-node-docker-compose.yml, docs/guides/external-node/docker-compose-examples/prometheus/prometheus.yml, docs/guides/external-node/docker-compose-examples/testnet-external-node-docker-compose.yml
I've added prometheus and grafana do EN docker compose with a simple dashboard like this:
=> feat(en): metric scraping and grafana for docker compose image

core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
This PR adds `addmod` and `mulmod` opcodes to YUL EVM interpreter, as well as tests for them.
=> [EVM-Equivalent-YUL] Add addmod and mulmod opcodes

.github/workflows/vm-perf-comparison.yml, core/tests/vm-benchmark/src/compare_iai_results.rs, core/tests/vm-benchmark/src/instruction_counts.rs
Instruction count diff should now be correct. The problem wasn't found initially because counting instructions legitimately fails if the PR starts from a version where that wasn't supported yet.
Also found and fixed a bug that hid performance improvements.
=> fix: instruction count diff always N/A in VM perf comparison

core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
This PR adds `exp` and `signextend` opcodes to YUL EVM interpreter, as well as tests for them.
=> [EVM-Equivalent-YUL] Add exp and signextend opcodes

infrastructure/zk/src/init.ts
Alter the order of the commands in the init script.
The first init ran in the repo was failing because the contracts were being compiled before downloading the dependencies.
=> fix(kl-factory): first init failing

core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
This PR adds `lt`, `gt`, `slt`, `sgt`, `eq`, `iszero`, `xor`, `not` and `byte` opcodes tests.
=> [EVM-Equivalent-YUL] Add some logic operators opcodes

.github/release-please/config.json, .github/workflows/release-please.yml
Fixes release-please config broken after #1584, by bumping the corresponding GitHub action.
release-please shouldn't be broken.
=> fix(ci): Bump `release-please-action` to v4

core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
This PR adds `mload`, `mstore` and `mstore8` tests.
=> [EVM-Equivalent-Yul] Add mload, mstore and mstore8

core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
Fix tests about gas consumption as now `PUSH`n opcodes consume gas.
=> [EVM-Equivalent-Yul] Add gas charge to lacking opcodes

.github/workflows/check-links.yml, .github/workflows/ci-core-lint-reusable.yml, .github/workflows/ci-core-reusable.yml, .github/workflows/ci.yml, core/lib/zksync_core/src/state_keeper/io/common/tests.rs, core/tests/ts-integration/src/context-owner.ts, core/tests/ts-integration/src/env.ts, core/tests/ts-integration/tests/ether.test.ts, yarn.lock
* Test was failing due to EVM-554 (wrong estimate of gas in the SDK).
For now, I've manually specified the gas limit.
* I've also disabled the parts of the CI (and created tickets for each one), to make the current CI pass.
=> fix: Fixing integration test for custom base token & temporarily disabling failing CI tests

core/bin/external_node/src/main.rs, core/lib/dal/src/metrics.rs, core/node/node_framework/src/implementations/layers/house_keeper.rs
Uses a singleton DB pool for scraping Postgres metrics instead of sharing the main pool.
The main pool may be used at capacity (e.g., during snapshot recovery), which leads to timeouts collecting Postgres metrics.
=> fix(en): Fix DB pool for Postgres metrics on EN

.github/workflows/ci-core-reusable.yml
=> chore: Enable fee projection tests

.github/workflows/ci-core-lint-reusable.yml, infrastructure/zk/src/fmt.ts, infrastructure/zk/src/utils.ts
Fixes EVM-560 - but still keeps '.sol' files disabled.
* Fixing lint
=> fix: Fixing issues with lint

core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
Add tests for `keccak256` opcode.
Note: The `MSTORE` opcode has to be implemented in order to pass the first `assert` of the test. The second `assert` passes because the `keccak256` function is applied to the memory with an offset of 0 and length of 4 bytes, which is equal to 0x0000_0000, since no value was stored in memory.
=> [EVM-Equivalent-YUL] Add tests for keccak256 opcode

.github/workflows/ci-core-reusable.yml, core/lib/zksync_core/src/consistency_checker/mod.rs, core/lib/zksync_core/src/consistency_checker/tests/mod.rs, core/tests/ts-integration/src/context-owner.ts, core/tests/ts-integration/src/env.ts, core/tests/ts-integration/tests/base-token.test.ts, yarn.lock
=> chore: Fix ext node test

.github/workflows/ci-core-reusable.yml, core/lib/zksync_core/src/consistency_checker/mod.rs
=> test: fix snapshot test

prover/Cargo.lock, prover/prover_cli/src/cli.rs, prover/prover_cli/src/commands/mod.rs, prover/prover_cli/src/commands/status/jobs.rs, prover/prover_cli/src/commands/status/mod.rs, prover/prover_cli/src/main.rs
Refactors `status` cmd.
The `status` cmd now supports the addition of new commands (not flags).
=> feat(Prover CLI): Refactor `status` cmd

.github/workflows/ci.yml, etc/ERC20/hardhat.config.ts
=> chore(kl-factory): Restore build core images workflow

checks-config/era.dic, docs/guides/external-node/00_quick_start.md, docs/guides/external-node/03_running.md, yarn.lock
Dedups system requirements in External Node docs and makes them (hopefully) more clear
Users are being confused by unclear system requirements mentioned in two different places in docs.
=> chore(docs): Dedup system requirements in EN docs

.dockerignore, .github/workflows/build-local-node-docker.yml, docker/local-node/Dockerfile, docker/local-node/README.md, docker/local-node/entrypoint.sh, infrastructure/local-setup-preparation/src/index.ts, infrastructure/zk/src/contract.ts, infrastructure/zk/src/database.ts
* Fixing docker build and scripts for the local node/setup.
* This will allow local node to work again - which is crucial before the bridgehub udpate.
* This PR is only fixing it in the 'main' branch - there will be a followup PR to the bridgehub branch coming later.
=> fix: Fixing local node

Cargo.lock, core/lib/merkle_tree/Cargo.toml, core/lib/merkle_tree/src/hasher/proofs.rs, core/lib/merkle_tree/tests/integration/merkle_tree.rs, core/lib/merkle_tree/tests/integration/recovery.rs
don't panic in `BlockOutputWithProofs::verify_proofs` and rather return a `Result`
So  `BlockOutputWithProofs::verify_proofs` can be used by other components.
=> fix(merkle_tree): don't panic in `BlockOutputWithProofs::verify_proofs`

.gitignore, recompile_interpreter.sh
Adds a preprocessor step in recompile_interpreter.sh in order to be able to use include on the EvmInterpreter.yul
Remember to run `npm install -g preprocess-cli-tool`
Related to the following PR: https://github.com/matter-labs/era-contracts/pull/377
=> Add preprocessor for evm interpreter

docker/local-node/README.md
Makes local-setup link properly formatted
Link checker has been failing with below for the last couple of days, e.g. [here](https://github.com/matter-labs/zksync-era/actions/runs/8749278699/job/24010671980?pr=1734)
```
FILE: ./docker/local-node/README.md
[✖] https://github.com/matter-labs/local-setup%5D
ERROR: 1 dead links found!
1 links checked.
[✖] https://github.com/matter-labs/local-setup%5D → Status: 404
```
=> chore: fix local-setup link

core/tests/ts-integration/tests/ether.test.ts
* Fixed ethers.test for ETH based chains.
* Minimised the diff against 'main' branch.
* Before, the test was depending on local env variables (to check if L2 was a ETH or custom based).
* also it didn't pass the proper arguments to the estimate method.
=> fix: fixed ethers.test for ETH based chain.

Cargo.lock, core/lib/state/src/rocksdb/mod.rs
Adds `enum_index_migration_cursor` back to storage layout description and says it's deprecated.
Storage layout should be complete
=> chore: keep `enum_index_migration_cursor` in storage layout description

core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/state_keeper/mod.rs
Fixes recently discovered bug in v22.1.0 where executor and fee migration logic get starved out by async catch up task that holds a long-term connection.
=> fix: ensure two connections for both executor and async catchup

.github/workflows/ci.yml, infrastructure/zk/src/hyperchain_wizard.ts
=> chore: factory stops CI, final PR

core/lib/dal/src/models/storage_transaction.rs, core/lib/types/src/vm_trace.rs
Adds `LegacyMixedCall` struct
Previous versions of the node saved such call traces, and they should be deserializable
=> fix(types): Add LegacyMixedCall

docker/external-node/Dockerfile
Removes `liburing` dependency in the EN image introduced in #1701.
`liburing` doesn't lead to much performance improvement in practice, and it complicates using the EN executable outside Docker.
=> fix(en): Revert using `liburing` for EN Docker image

core/lib/basic_types/src/prover_dal.rs, prover/prover_cli/src/commands/status/batch.rs, prover/prover_cli/src/commands/status/utils.rs, prover/prover_dal/.sqlx/query-2ab2f83b273c5aa88c1eefc8f70a8ea23052f714cd74c1d28ae1203ce8f0eaa9.json, prover/prover_dal/src/fri_proof_compressor_dal.rs
Handles the batch proof compression status for the `status batch` command.
A user that will do maintenance on the prover could find useful to see the batch proof compression job status.
```
cd prover/prover_cli
zk f cargo run --release  status batch -n 1
```
=> feat(Prover CLI): Batch proof compression job status

core/lib/zksync_core/src/api_server/tx_sender/mod.rs, core/lib/zksync_core/src/api_server/tx_sender/tests.rs, core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/mod.rs, core/lib/zksync_core/src/api_server/web3/namespaces/debug.rs, core/lib/zksync_core/src/api_server/web3/namespaces/zks.rs, core/lib/zksync_core/src/fee_model.rs, core/lib/zksync_core/src/state_keeper/io/mempool.rs, core/lib/zksync_core/src/state_keeper/io/tests/mod.rs, core/lib/zksync_core/src/state_keeper/mempool_actor.rs, core/lib/zksync_core/src/utils/testonly.rs
Currently, `TxSender::submit_tx()` on the main node acquires 2 DB connections at the same time: one explicitly, and another in batch fee input provider. This PR eliminates this.
Also, propagates errors in batch fee input provider, so that they don't lead to panics.
Holding multiple DB connections at the same time can lead to connection starvation, or at worst case (temporary) deadlocks.
=> fix(api): Fix extra DB connection acquisition during tx submission

.github/workflows/protobuf.yaml
It turns out that the current implementation of the check compares a given pr against the head of the base branch. If some proto files have been updated on the base branch (so there is a fork between the pr and the base branch), compatibility check will think that the pr wants to revert the changes made on the base branch. 
This pr fixes that by making the check compare pr against the lowest common ancestor between the pr and the base branch.
=> fix: updated protobuf ci

.github/workflows/release-please.yml
- Removes obsolete output from release-please workflow
- Swaps to explicit "true" evaluation to ensure it actually works and "Send Release Info" is not executed on empty "releases_created" input
- To fix workflow, so it does not fail on no releases
=> fix(ci): Do not send Slack webhooks in release-please on no release

.gitignore, Cargo.lock, core/lib/contracts/src/lib.rs, core/lib/multivm/Cargo.toml, core/lib/multivm/benchmarks/compare_benchmarks.py, core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs, core/lib/types/src/system_contracts.rs, core/lib/zksync_core/src/genesis.rs
This PR adds the possibility of running benchmarks with the YUL evm
A new environment variable was added for this purpose
Right now there a 3 benchmarks, you can add your own adding a new function following the same structure as `benchmark_basic`
How to run benchmarks:
`EVM_SIMULATOR=YUL cargo test test_emv_benchmark`
or
`EVM_SIMULATOR=SOLIDITY cargo test test_emv_benchmark`
This will generate a csv file under `zksync-era/core/lib/multivm/benchmarks`, with the following name: `benchmark_<yul/solidity>_<date>.csv` for example: `benchmark_yul_2024-04-25-18-09-53.csv`
The csv has the following headers:
`name,used_zkevm_ergs,used_evm_gas,used_circuits`
A python script was added in `zksync-era/core/lib/multivm/benchmarks` to facilitate comparing two benchmarks, it can be run as:
`python3 …
=> [EVM-Equivalent-YUL] Benchmarks

core/bin/external_node/src/config/mod.rs, core/bin/external_node/src/main.rs
=> fix(en): correct en config vars

core/lib/types/src/storage/writes/compression.rs
Removes methods that copypaste default implementations on `CompressionMode` trait.
=> chore(types): removes redundant trait method implementations

core/lib/multivm/src/glue/types/vm/vm_block_result.rs, core/lib/multivm/src/interface/types/outputs/execution_state.rs, core/lib/multivm/src/versions/vm_1_3_2/vm.rs, core/lib/multivm/src/versions/vm_1_4_1/vm.rs, core/lib/multivm/src/versions/vm_1_4_2/vm.rs, core/lib/multivm/src/versions/vm_boojum_integration/vm.rs, core/lib/multivm/src/versions/vm_latest/tests/refunds.rs, core/lib/multivm/src/versions/vm_latest/vm.rs, core/lib/multivm/src/versions/vm_m5/vm.rs, core/lib/multivm/src/versions/vm_m6/vm.rs, core/lib/multivm/src/versions/vm_refunds_enhancement/vm.rs, core/lib/multivm/src/versions/vm_virtual_blocks/vm.rs, core/lib/zksync_core/src/state_keeper/io/persistence.rs, core/lib/zksync_core/src/state_keeper/io/seal_logic.rs, core/lib/zksync_core/src/state_keeper/tests/mod.rs
Before this change CurrentExecutionState contained deduplicated storage logs and the raw storage logs. However, the fast VM cannot produce the raw storage logs, as those are an implementation detail. Luckily it seems that they aren't needed, at least for out-of-circuit use.
=> chore: remove storage_logs field from ExecutionState

core/tests/snapshot-recovery-test/tests/snapshot-recovery.test.ts
Fixes flakiness in the snapshot recovery / pruning test by relaxing some checks.
Flaky tests bad.
=> test(en): Fix snapshot recovery test flakiness

core/tests/loadnext/src/command/tx_command.rs
Makes sure that any transaction has amount of 1 wei at least.
- It is no longer possible to withdraw 0 wei, so the test became flaky.
- Testing edge cases is not a point for loadtest, we have integration tests for that.
=> fix(loadtest): Do not initiate transactions with 0 amount

core/lib/db_connection/src/connection.rs, core/lib/db_connection/src/utils.rs, core/node/node_framework/src/implementations/layers/commitment_generator.rs, core/node/node_framework/src/implementations/layers/consensus.rs, core/node/node_framework/src/implementations/layers/consistency_checker.rs, core/node/node_framework/src/implementations/layers/contract_verification_api.rs, core/node/node_framework/src/implementations/layers/eth_sender.rs, core/node/node_framework/src/implementations/layers/eth_watch.rs, core/node/node_framework/src/implementations/layers/house_keeper.rs, core/node/node_framework/src/implementations/layers/metadata_calculator.rs, core/node/node_framework/src/implementations/layers/pools_layer.rs, core/node/node_framework/src/implementations/layers/proof_data_handler.rs, core/node/node_framework/src/implementations/layers/state_keeper/main_batch_executor.rs, core/node/node_framework/src/implementations/layers/state_keeper/mempool_io.rs, core/node/node_framework/src/implementations/layers/web3_api/caches.rs, core/node/node_framework/src/implementations/layers/web3_api/server.rs, core/node/node_framework/src/implementations/layers/web3_api/tx_sender.rs, core/node/node_framework/src/implementations/layers/web3_api/tx_sink.rs, core/node/node_framework/src/implementations/resources/pools.rs
Refactors pools layer:
- Introduces a single generic type instead of 3 mostly copy-pasted ones.
- Parameters for builder are now passed to the resource instead of cloning a builder.
- Fixes a problem where an unbound pool is created for each requester (now it's lazily initialized and cloned).
a) less boilerplate
b) align the implementation to the expected behavior
=> refactor(node_framework): Refactor pools layer

Cargo.lock, core/lib/basic_types/Cargo.toml, core/lib/basic_types/src/lib.rs
Skip the `serde_json` workarounds, if the serializer is not human readable.
Deserialization with the `bincode` serializer is broken, because it is assumed to be json.
=> fix(basic_types): bincode deserialization for `L2ChainId`

core/lib/zksync_core/src/utils/mod.rs
Change to which contract we call when calling the method `getPubdataPricingMode`.
Now `getPubdataPricingMode` method is in the `IZkSyncHyperchain` [interface](https://github.com/matter-labs/zksync-era/blob/main/core/tests/loadnext/src/sdk/abi/IZkSyncHyperchain.json#L1438).
=> fix(Validium): `getPubdataPricingMode` contract call

core/bin/external_node/src/config/mod.rs, core/bin/external_node/src/main.rs, core/bin/external_node/src/tests.rs, core/lib/eth_client/src/clients/http/query.rs, core/lib/eth_client/src/clients/http/signing.rs, core/lib/eth_client/src/clients/mock.rs, core/lib/eth_client/src/lib.rs, core/lib/zksync_core/src/consistency_checker/mod.rs, core/lib/zksync_core/src/consistency_checker/tests/mod.rs, core/lib/zksync_core/src/eth_sender/eth_tx_aggregator.rs, core/lib/zksync_core/src/eth_sender/eth_tx_manager.rs, core/lib/zksync_core/src/eth_sender/tests.rs, core/lib/zksync_core/src/genesis.rs, core/lib/zksync_core/src/l1_gas_price/gas_adjuster/mod.rs, core/lib/zksync_core/src/l1_gas_price/gas_adjuster/tests.rs, core/lib/zksync_core/src/l1_gas_price/singleton.rs, core/lib/zksync_core/src/lib.rs, core/lib/zksync_core/src/state_keeper/io/tests/tester.rs, core/node/eth_watch/src/client.rs, core/node/node_framework/src/implementations/layers/pk_signing_eth_client.rs, core/node/node_framework/src/implementations/layers/query_eth_client.rs, core/node/node_framework/src/implementations/resources/eth_interface.rs, core/tests/loadnext/src/account/tx_command_executor.rs, core/tests/loadnext/src/executor.rs, core/tests/loadnext/src/sdk/ethereum/mod.rs
Refactors L1 client interfaces so that they work similarly to L2 client ones.
DevEx and maintainability.
=> refactor(eth-client): Refactor L1 client interfaces

core/lib/multivm/src/glue/types/vm/vm_block_result.rs, core/lib/multivm/src/interface/traits/vm.rs, core/lib/multivm/src/interface/types/outputs/finished_l1batch.rs, core/lib/multivm/src/versions/vm_1_4_1/vm.rs, core/lib/multivm/src/versions/vm_1_4_2/vm.rs, core/lib/multivm/src/versions/vm_boojum_integration/vm.rs, core/lib/multivm/src/versions/vm_latest/vm.rs, core/lib/types/src/storage/writes/mod.rs, core/lib/zksync_core/src/state_keeper/io/persistence.rs, core/lib/zksync_core/src/state_keeper/io/seal_logic.rs, core/lib/zksync_core/src/state_keeper/tests/mod.rs
New versions of VM (1.4.2 and 1.5.0) return list of initially written slots. State keeper doesn't need to query DB to filter slots anymore.
Improve L1 batch seal performance.
=> perf(state-keeper): Improve `FilterWrittenSlots` l1 batch seal stage

core/bin/contract-verifier/src/verifier.rs, core/bin/contract-verifier/src/zksolc_utils.rs
Adds opportunity to verify yul contract source code with system-mode on.
Some contract are compiled with system mode off, some with mode on, all must be verifiable.
=> fix(contract-verifier): YUL system-mode verification

core/bin/external_node/src/config/mod.rs, core/bin/external_node/src/helpers.rs, core/bin/external_node/src/main.rs, core/bin/external_node/src/metrics.rs, core/bin/external_node/src/tests.rs, core/lib/zksync_core/src/api_server/tx_sender/mod.rs
- Removes `max_pubdata_per_batch` from the remote EN config.
- Moves L1 and L2 chain IDs from the remote config to the required one. Adds a managed task asynchronously validating these IDs.
- `max_pubdata_per_batch` is unused.
- L1 and L2 chain IDs are required to start a node anyway. Async validation means that the EN can now start w/o connecting to L1 / L2 nodes (well, other than to fetch contract addresses etc., but those will be dealt with separately).
=> refactor(en): Remove chain IDs and unused field from remote EN config

core/lib/eth_client/src/clients/http/decl.rs, core/lib/eth_client/src/clients/http/query.rs
Fixes passing `null` parameters where RPC providers don't expect them.
Without the fix, L1 client is broken.
=> fix(eth-client): Make block params non-optional

core/node/node_framework/src/service/runnables.rs, prover/prover_cli/src/commands/status/utils.rs
`cargo-spellcheck` got bumped to 0.14.0 in CI, and it started to discover more problems.
This PR aims to fix that.
Dead CI bad
=> ci: Fix spellcheck issues

bin/run_retried, bin/zk, infrastructure/zk/src/run.ts
Yarn 1.* doesn't seem to have any sort of built-in mechanisms for retries, so I've added a generic wrapper that just retries provided command.
=> fix(ci): add retried to yarn install

core/lib/dal/.sqlx/query-8cc3cf441b12a8b6a2f25f4fe5581e33845ec68e386ef032715ad1222e2fdc8b.json, core/lib/dal/src/transactions_dal.rs
Delete txs not only by hash but also by (init_addr, nonce) before inserting them
Fix bug
=> fix(en): Delete old txs by (init_addr, nonce)

core/lib/basic_types/src/web3/mod.rs, core/lib/basic_types/src/web3/tests.rs
Only use custom format, if human readable serializer is used.
Don't assume we only use serde_json... Make bincode ser/deser work
=> fix(basic_types): bincode deserialization for `web3::Bytes`

Cargo.lock, core/lib/utils/Cargo.toml, core/lib/utils/src/serde_wrappers.rs
Only do a hex string conversion if serializer/deserializer `.is_human_readable()`.
bincode does not need a hex string presentation.
=> fix(utils): bincode ser-/deserialization for `BytesToHexSerde`

.github/workflows/build-contract-verifier-template.yml, .github/workflows/build-core-template.yml, .github/workflows/build-docker-from-tag.yml, .github/workflows/build-local-node-docker.yml, .github/workflows/build-prover-fri-gpu-gar.yml, .github/workflows/build-prover-template.yml, .github/workflows/cargo-license.yaml, .github/workflows/check-spelling.yml, .github/workflows/ci-common-reusable.yml, .github/workflows/ci-core-lint-reusable.yml, .github/workflows/ci-core-reusable.yml, .github/workflows/ci-docs-reusable.yml, .github/workflows/ci-prover-reusable.yml, .github/workflows/ci.yml, .github/workflows/nodejs-license.yaml, .github/workflows/protobuf.yaml, .github/workflows/release-please-cargo-lock.yml, .github/workflows/release-test-stage.yml, .github/workflows/secrets_scanner.yaml, .github/workflows/vm-perf-comparison.yml, .github/workflows/vm-perf-to-prometheus.yml, .github/workflows/zk-environment-publish.yml
Just making actions/checkout consistent everywhere across all CI workflows
To get latest/non-deprecated version of GHA action
=> chore(ci): Bump and pin actions/checkout everywhere (v4.1.6)

core/tests/ts-integration/scripts/compile-yul.ts, core/tests/ts-integration/src/context-owner.ts, core/tests/ts-integration/src/env.ts, core/tests/ts-integration/src/helpers.ts, core/tests/ts-integration/src/types.ts, core/tests/ts-integration/tests/api/contract-verification.test.ts, core/tests/ts-integration/tests/api/debug.test.ts, core/tests/ts-integration/tests/api/web3.test.ts, core/tests/ts-integration/tests/contracts.test.ts, core/tests/ts-integration/tests/custom-account.test.ts, core/tests/ts-integration/tests/fees.test.ts, core/tests/ts-integration/tests/l1.test.ts, core/tests/ts-integration/tests/paymaster.test.ts, core/tests/ts-integration/tests/system.test.ts
Remove dependency from dev.env envs from ts-tests
For migrating it later to file-based config we have to consolidate all env calls into one place
=> feat(tests): Move all env calls to one place in ts-tests

core/bin/external_node/src/main.rs
Runs `MainNodeFeeParamsFetcher` in `run_api`.
Removes it from `run_core`.
En's core doesn't use `MainNodeFeeParamsFetcher`. API uses it. API operated normally only if Core and Api are launched in the same process which is not true for distributed nodes. The PR fixes it
=> fix(en): run `MainNodeFeeParamsFetcher` in API component

Cargo.lock, Cargo.toml, prover/Cargo.lock
I need https://github.com/matter-labs/era-consensus/pull/114 to be included, so start testing EN validator mode (on stage).
=> chore: bumped era-consensus

core/node/house_keeper/src/prover/metrics.rs, core/node/house_keeper/src/prover/queue_reporter/fri_witness_generator_queue_reporter.rs
Add protocol_version label to WG jobs metric
To be able to use autoscaler for protocol versions
=> feat: Add protocol_version label to WG jobs metric

core/bin/external_node/src/main.rs, core/lib/merkle_tree/src/metrics.rs, core/lib/merkle_tree/src/recovery.rs
- Starts metrics exporter on EN immediately so that it covers snapshot recovery.
- Fixes / extends Merkle tree recovery metrics (e.g., incorrectly reported `nodes_by_nibble_count`).
Improves metrics coverage.
=> fix(en): Fix recovery-related metrics

prover/vk_setup_data_generator_server_fri/src/keystore.rs, prover/vk_setup_data_generator_server_fri/src/utils.rs, prover/vk_setup_data_generator_server_fri/src/vk_commitment_helper.rs
Fix path after migration to non zksync home dir
=> fix(prover): Fix path to vk_setup_data_generator_server_fri

zk_toolbox/crates/zk_inception/src/commands/chain/args/init.rs, zk_toolbox/crates/zk_inception/src/commands/containers.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/args/create.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/args/init.rs
=> fix(zk_tool): Change some texts

zk_toolbox/crates/common/src/ethereum.rs, zk_toolbox/crates/common/src/forge.rs, zk_toolbox/crates/common/src/prompt/confirm.rs, zk_toolbox/crates/zk_inception/src/accept_ownership.rs, zk_toolbox/crates/zk_inception/src/commands/chain/deploy_paymaster.rs, zk_toolbox/crates/zk_inception/src/commands/chain/init.rs, zk_toolbox/crates/zk_inception/src/commands/chain/initialize_bridges.rs, zk_toolbox/crates/zk_inception/src/commands/chain/mod.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/init.rs, zk_toolbox/crates/zk_inception/src/consts.rs, zk_toolbox/crates/zk_inception/src/forge_utils.rs
=> feat(zk-toolbox): add balance check

zk_toolbox/crates/common/src/ethereum.rs, zk_toolbox/crates/common/src/forge.rs
=> fix(zk_toolbox): Add chain id for local wallet

checks-config/era.dic, docs/guides/setup-dev.md, zk_toolbox/README.md, zk_toolbox/rust-toolchain
- Added dependencies section
- Added `bash` to code blocks
- Made all major commands code blocks for easier copying and better styling
- Added fixed version to rust toolchain (1.78.0)
=> fix(zk_toolbox): readme added dependencies section and cleaned up

core/node/node_framework/src/implementations/layers/state_keeper/mod.rs
`AsyncRocksdbCache` requires at least 2 connections, but in the glue it was provided with only 1.
Bug
=> fix(node_framework): Fix the connection pool size for the catchup task

core/lib/contracts/src/lib.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/init.rs
Use forge and hardhat output for loading the contracts
During the transition period we have to keep both versions
=> fix(zk_toolbox):  Use both folders for loading contracts 

core/node/node_framework/src/implementations/layers/commitment_generator.rs
We create a custom pool for commitment generator in `initialize_components`, but use "global" pool in the framework.
Align implementations.
=> fix(node_framework): Use custom pool for commitiment generator

zk_toolbox/README.md, zk_toolbox/crates/zk_inception/src/main.rs
- readme added dependencies section and cleaned up
- fixed name of chain
- to help testers
=> fix(zk_toolbox): improve readme to include containers command and cd

core/lib/merkle_tree/src/domain.rs, core/lib/merkle_tree/src/hasher/nodes.rs, core/lib/merkle_tree/src/lib.rs, core/node/metadata_calculator/src/helpers.rs
Makes `MerkleTreeInfo` returned from `AsyncTreeReader` consistent.
Right now, it's not consistent, which e.g., leads to sporadic CI failures, and could lead to inconsistent data exposed via tree API or tree health check.
=> fix(merkle-tree): Fix incoherent Merkle tree view

infrastructure/protocol-upgrade/src/l2upgrade/transactions.ts, infrastructure/protocol-upgrade/src/protocol-upgrade-manager.ts, infrastructure/protocol-upgrade/src/transaction.ts, infrastructure/protocol-upgrade/src/utils.ts
We'll store the semantic version of the protocol in the `common.json`.
For the upgrade itself we'll have to use packed format, but for the l2 transaction we'll use only the `minor` version (for compatibility with the server). It is expected that the upgrade transaction is only present during at least `minor` upgrades and never present during `patch` ones
=> Make protocol upgrade tool support semver

core/node/metadata_calculator/src/helpers.rs
Makes protective reads sorted
Fix bug
=> fix(metadata-calculator): protective reads sort

core/lib/protobuf_config/src/genesis.rs, core/lib/protobuf_config/src/proto/config/genesis.proto, etc/env/file_based/genesis.yaml
=> fix(protocol_version): Add backward compatibility

core/node/state_keeper/src/batch_executor/main_executor.rs, core/node/state_keeper/src/batch_executor/mod.rs, core/node/state_keeper/src/batch_executor/tests/mod.rs, core/node/state_keeper/src/batch_executor/tests/tester.rs, core/node/state_keeper/src/keeper.rs, core/node/state_keeper/src/testonly/mod.rs, core/node/state_keeper/src/testonly/test_batch_executor.rs, core/node/vm_runner/src/process.rs
Propagates errors in the batch executor instead of panicking.
Batch executor somewhat frequently panics on node shutdown. This is suboptimal UX, can lead to false positive bug reports etc.
=> refactor(state-keeper): Propagate errors in batch executor

infrastructure/zk/src/fmt.ts, infrastructure/zk/src/lint.ts, zk_toolbox/crates/common/src/db.rs, zk_toolbox/crates/common/src/docker.rs, zk_toolbox/crates/common/src/prerequisites.rs, zk_toolbox/crates/common/src/prompt/confirm.rs, zk_toolbox/crates/common/src/prompt/input.rs, zk_toolbox/crates/zk_inception/src/accept_ownership.rs, zk_toolbox/crates/zk_inception/src/commands/chain/args/create.rs, zk_toolbox/crates/zk_inception/src/commands/chain/args/genesis.rs, zk_toolbox/crates/zk_inception/src/commands/chain/args/init.rs, zk_toolbox/crates/zk_inception/src/commands/chain/create.rs, zk_toolbox/crates/zk_inception/src/commands/chain/deploy_paymaster.rs, zk_toolbox/crates/zk_inception/src/commands/chain/genesis.rs, zk_toolbox/crates/zk_inception/src/commands/chain/init.rs, zk_toolbox/crates/zk_inception/src/commands/chain/initialize_bridges.rs, zk_toolbox/crates/zk_inception/src/commands/containers.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/args/init.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/change_default.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/create.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/init.rs, zk_toolbox/crates/zk_inception/src/commands/server.rs, zk_toolbox/crates/zk_inception/src/config_manipulations.rs, zk_toolbox/crates/zk_inception/src/forge_utils.rs, zk_toolbox/crates/zk_inception/src/main.rs
- Follow rust formatting convention to zk_toolbox
- Add format and clippy to CI
=> feat(toolbox): add format and clippy to zk_toolbox ci

core/node/node_framework/examples/showcase.rs, core/node/node_framework/src/implementations/layers/circuit_breaker_checker.rs, core/node/node_framework/src/implementations/layers/commitment_generator.rs, core/node/node_framework/src/implementations/layers/consensus.rs, core/node/node_framework/src/implementations/layers/consistency_checker.rs, core/node/node_framework/src/implementations/layers/contract_verification_api.rs, core/node/node_framework/src/implementations/layers/eth_sender.rs, core/node/node_framework/src/implementations/layers/eth_watch.rs, core/node/node_framework/src/implementations/layers/healtcheck_server.rs, core/node/node_framework/src/implementations/layers/house_keeper.rs, core/node/node_framework/src/implementations/layers/l1_gas.rs, core/node/node_framework/src/implementations/layers/metadata_calculator.rs, core/node/node_framework/src/implementations/layers/prometheus_exporter.rs, core/node/node_framework/src/implementations/layers/proof_data_handler.rs, core/node/node_framework/src/implementations/layers/sigint.rs, core/node/node_framework/src/implementations/layers/state_keeper/mempool_io.rs, core/node/node_framework/src/implementations/layers/state_keeper/mod.rs, core/node/node_framework/src/implementations/layers/tee_verifier_input_producer.rs, core/node/node_framework/src/implementations/layers/web3_api/caches.rs, core/node/node_framework/src/implementations/layers/web3_api/server.rs, core/node/node_framework/src/implementations/layers/web3_api/tx_sender.rs, core/node/node_framework/src/precondition.rs, core/node/node_framework/src/service/context.rs, core/node/node_framework/src/service/runnables.rs, core/node/node_framework/src/service/tests.rs, core/node/node_framework/src/task.rs
This PR refactors `Task`-related traits to use an owned type `TaskId` instead of `&'static str`.
There are use cases where a task's id needs to be generated dynamically (e.g. broad trait implementations) which this PR accommodates for.
=> refactor(node-framework): use owned type to identify `Task`s

Cargo.lock, core/bin/block_reverter/src/main.rs, core/lib/object_store/Cargo.toml, core/lib/object_store/src/file.rs, core/lib/object_store/src/gcs.rs, core/lib/object_store/src/raw.rs, core/lib/snapshots_applier/src/lib.rs, core/lib/snapshots_applier/src/tests/mod.rs, core/node/block_reverter/Cargo.toml, core/node/block_reverter/src/lib.rs, core/node/block_reverter/src/tests.rs, prover/Cargo.lock
- Does not retry "not found" errors when removing objects.
- Makes rolling back snapshot files optional.
The current implementation leads to very slow reverts because of retries.
=> fix(block-reverter): Fix reverting snapshot files

core/node/eth_watch/src/event_processors/governance_upgrades.rs
Changes assert so it allows upgrade that have set bootloader set but equal to previous bootloader code.
=> fix(eth-watch): make assert less strict

core/bin/external_node/src/config/mod.rs, core/bin/external_node/src/main.rs, core/bin/external_node/src/tests.rs
- Removes a no longer needed CLI flag.
- Removes an undocumented configuration option that was deprecated [long ago](https://github.com/matter-labs/zksync-era/pull/793).
Less dead code.
=> refactor(node): Remove some dead code

core/node/node_framework/src/implementations/layers/main_node_client.rs, core/node/node_framework/src/implementations/layers/mod.rs
Note: healthchecks for `Main Node` and `Eth` client  layers will be added in the next PR(there is a general principle of change.)
=> feat(node-framework): Add Main Node Client layer

core/bin/external_node/src/helpers.rs, core/bin/external_node/src/main.rs
Removes L1 client health check from EN.
Doesn't bring that much value and leads to L1 client getting rate-limited for our GCS ENs.
=> fix(en): Remove L1 client health check

core/node/state_keeper/src/io/seal_logic/l2_block_seal_subtasks.rs
save l2 l1 logs for miniblock only if there are some
We save l2 l1 logs using `COPY` and it appears it has some constant overhead of ~40ms regardless whether there is some data to copy or not. By checking if l2_l1_logs.is_empty we can save this 40ms.
=> chore: save l2 l1 logs only if there are some

core/bin/external_node/src/config/mod.rs, core/bin/external_node/src/init.rs, core/bin/external_node/src/main.rs, core/lib/snapshots_applier/src/lib.rs, core/lib/snapshots_applier/src/tests/mod.rs, core/lib/snapshots_applier/src/tests/utils.rs
Allows recovering a node from a specific snapshot specified at the start of recovery.
Useful at least for testing recovery and pruning end-to-end on the testnet. There, L1 batches are produced very slowly, so it makes sense to recover from an earlier snapshot in order to meaningfully test pruning.
=> feat(en): Allow recovery from specific snapshot

core/node/consistency_checker/src/lib.rs
Considers a subset of contract call errors as transient.
Currently, consistency checker considers all contract call errors fatal, which leads to EN terminating when it shouldn't.
=> fix(en): Fix transient error detection in consistency checker

docs/guides/external-node/docker-compose-examples/mainnet-external-node-docker-compose.yml, docs/guides/external-node/docker-compose-examples/testnet-external-node-docker-compose.yml
- Tweaking postgres `healthcheck` command in EN Docker Compose example to work from shells other than bash
- Minor formatting fixes to the aforementioned Docker Compose example files
- EN bump to the latest stable in the aforementioned Docker Compose example files
Fixes: **https://github.com/zkSync-Community-Hub/zksync-developers/discussions/526#discussioncomment-9552115**
=> chore(docs): Fix healthcheck command in EN docker-compose example

.github/workflows/build-contract-verifier-template.yml, .github/workflows/build-core-template.yml, .github/workflows/build-prover-template.yml
Curl is unable to retry some transient errors, so it's more reliable to use run_retried which retries any error
=> fix(ci): Run_retried instead of curl --retry

core/node/api_server/src/web3/namespaces/debug.rs, core/node/api_server/src/web3/namespaces/eth.rs
Fixes getting data for the pending block in `eth_getBlockByNumber` and a couple of other methods.
Getting a pending block should always return `null`, but right now it actually doesn't. Caused by non-atomic reads from Postgres in the method implementation: first, a pending block number is resolved, and then a block with this number is fetched. Between these two reads, a block with this number may be inserted to Postgres.
While it's somewhat unlikely that anyone will query a pending block, it's still a correctness issue.
=> fix(api): Fix getting pending block

core/bin/external_node/src/main.rs, core/bin/zksync_server/src/node_builder.rs, core/lib/contracts/src/lib.rs, core/lib/zksync_core_leftovers/src/lib.rs, core/node/api_server/src/execution_sandbox/tests.rs, core/node/api_server/src/tx_sender/mod.rs, core/node/api_server/src/web3/namespaces/debug.rs, core/node/api_server/src/web3/testonly.rs, core/node/node_framework/examples/main_node.rs, core/node/node_framework/src/implementations/layers/web3_api/tx_sender.rs
Fixes the latency of API server unit tests caused by the lack of buffering when reading contracts.
Lack of buffering is a logical error on its own. In this case, it leads t slow test runs, i.e., degrades DevEx.
=> test(api): Fix latency of API server unit tests

core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
This PR adds tests for the fixes of some bugs on extcodecopy where the destiny for memory was not being handled and if the address didn't have code it reverted instead of returning zeros
Implementation is on this [PR](https://github.com/matter-labs/era-contracts/pull/515)
=> [EVM-Equivalence-YUL] Extcodecopy fix

core/lib/dal/.sqlx/query-f023e5fa599b279acd6ac02dffb7a33a8fea8ab7fdefb7d9210673245a2a6f6c.json, core/lib/dal/src/transactions_dal.rs
Optimize `get_l2_blocks_to_execute_for_l1_batch`
`transactions.l1_batch_number` is not indexed
=> fix(db): Optimize `get_l2_blocks_to_execute_for_l1_batch`

Cargo.lock, core/node/vm_runner/Cargo.toml, core/node/vm_runner/src/lib.rs, core/node/vm_runner/src/metrics.rs, core/node/vm_runner/src/output_handler.rs, core/node/vm_runner/src/process.rs, core/node/vm_runner/src/storage.rs
This PR just adds some basic VM runner-specific metrics. Note that VM runner already inherits VM-related metrics from state keeper.
I decided to split `storage_load`/`vm_run`/`output_handle` into 3 different metrics as opposed to a single metric with 3 stages as the stages happen asynchronously and don't represent a continuous execution. Lmk if you disagree though.
=> feat(vm-runner): add basic metrics

core/node/node_sync/src/tree_data_fetcher/metrics.rs, core/node/node_sync/src/tree_data_fetcher/mod.rs, core/node/node_sync/src/tree_data_fetcher/provider/mod.rs, core/node/node_sync/src/tree_data_fetcher/provider/tests.rs, core/node/node_sync/src/tree_data_fetcher/tests.rs, core/node/reorg_detector/src/lib.rs, core/node/reorg_detector/src/tests.rs
Fixes reorg detection logic so that it accounts for the tree data fetcher:
- **In tree data fetcher:** Tries to detect reorgs, so that root hashes are not written for diverging L1 batches.
- **In reorg detector:** Checks last L2 block correspondence during binary searching a diverging L1 batch.
Reorg detection may be broken if tree data fetcher is enabled:
- The tree data fetcher doesn't check that fetched L1 batch root hashes correspond to local L1 batches, i.e. it can fetch a root hash after a revert.
- Hence, the logic in reorg detector which binary-searches the diverged L1 batch is broken because the latest L1 batch isn't guaranteed to diverge if there's a divergence.
=> fix(en): Fix reorg detection in presence of tree data fetcher

core/lib/merkle_tree/src/domain.rs, core/lib/snapshots_applier/src/tests/utils.rs, core/node/metadata_calculator/src/helpers.rs, core/node/metadata_calculator/src/lib.rs, core/node/metadata_calculator/src/tests.rs, core/node/metadata_calculator/src/updater.rs
Reworks tree rollback so that it's supported on the distributed external node, including the case when a node runs multiple trees.
- Desync with Postgres is now detected on metadata calculator initialization, and the tree is truncated correspondingly.
- The old approach is left intact as a safety guard.
Right now, reorg logic on EN relies on a node running a single tree, and block reverter being a singleton. Both these assumptions are bogus in case of a distributed EN.
=> feat(merkle-tree): Rework tree rollback

core/node/eth_sender/src/abstract_l1_interface.rs, core/node/eth_sender/src/eth_fees_oracle.rs, core/node/eth_sender/src/eth_tx_manager.rs, core/node/eth_sender/src/lib.rs, core/node/eth_sender/src/metrics.rs, core/node/eth_sender/src/tests.rs
This PR deliberately only moves the code around without refactoring the logic itself to decrease the risk of error. More PRs will most likely follow
=> chore(eth-sender): extact abstract l1 interface and all fee-related code

core/node/consensus/src/era.rs
"%err" is just printing the leaf message which is not useful. "{err:#}" prints the whole stack trace, as desired.
=> chore: fixed consensus error logging

core/node/state_keeper/src/keeper.rs, core/node/state_keeper/src/metrics.rs
Add metrics for better observability
=> feat(state-keeper): More state keeper metrics

core/lib/state/src/catchup.rs, core/lib/state/src/lib.rs, core/lib/state/src/storage_factory.rs, core/node/state_keeper/src/state_keeper_storage.rs, core/node/vm_runner/src/storage.rs
Improves switching logic between Postgres and RocksDB for SK cache. With these changes, RocksDB is guaranteed to be used if it's up to date when it's opened.
Previously, Postgres could be used after node start (primarily if there's a pending L1 batch) even if RocksDB is up to date. This is caused by potential delays when opening RocksDB. This behavior was observed in the wild, e.g. for a mainnet full node with pruning enabled.
=> perf(db): Improve storage switching for state keeper cache

core/lib/object_store/src/gcs.rs
Considers `reqwest::Error`s with "request" kind transient for the object store logic.
Similar to some other kinds of `reqwest::Error`s, not all "request" errors are truly transient, but considering them as such is a safer option.
=> fix(object-store): Consider more GCS errors transient

.github/workflows/ci-zk-toolbox-reusable.yml, zk_toolbox/crates/zk_inception/src/commands/args/run_server.rs, zk_toolbox/crates/zk_inception/src/messages.rs
- Improves zk-toolbox integration tests CI adding missing arguments from typescript core CI
=> fix: zk-toolbox integration tests ci

core/lib/multivm/src/versions/vm_latest/old_vm/oracles/decommitter.rs, core/lib/multivm/src/versions/vm_latest/tests/get_used_contracts.rs, core/lib/multivm/src/versions/vm_latest/tests/tester/inner_state.rs, core/lib/multivm/src/versions/vm_latest/tracers/circuits_tracer.rs
Update `decommitted_code_hashes` in `prepare_to_decommit`
Contract hashes that reached `prepare_to_decommit` should be returned by `get_used_contracts`
=> fix(vm): Update `decommitted_code_hashes` in `prepare_to_decommit`

zk_toolbox/crates/common/src/forge.rs, zk_toolbox/crates/zk_inception/src/forge_utils.rs, zk_toolbox/crates/zk_inception/src/messages.rs
Show balance of account if it's not enough for contract deployment
=> fix(zk_toolbox): Show balance

Cargo.lock, core/lib/contract_verifier/Cargo.toml, core/lib/contract_verifier/src/lib.rs, core/lib/contract_verifier/src/zksolc_utils.rs, core/lib/types/src/contract_verification_api.rs
- `system-mode`, `force-evmla` flag are not provided for zksolc post v1.5.0 compilations
- `solc-path` is not provided for system yul post v1.5.0 compilations 
Changes in compiler interface
=> feat(contract-verifier): Adjust contract verifier for zksolc 1.5.0

core/node/node_sync/src/tree_data_fetcher/metrics.rs, core/node/node_sync/src/tree_data_fetcher/mod.rs, core/node/node_sync/src/tree_data_fetcher/provider/mod.rs, core/node/node_sync/src/tree_data_fetcher/provider/tests.rs, core/node/node_sync/src/tree_data_fetcher/tests.rs
Improves logging and metrics for the tree data fetcher.
Currently, some errors don't have their context logged, and some metrics are defined suboptimally.
=> refactor(en): Fetch old L1 batch hashes from L1 – improve metrics / logging

core/node/metadata_calculator/src/recovery/mod.rs, core/node/metadata_calculator/src/tests.rs, core/node/metadata_calculator/src/updater.rs
Adds checks in the case the metadata calculator cannot proceed because of pruning.
While we don't officially support distributed setup for ENs, it still looks worth it to have intelligent error messages in case metadata calculator is stuck.
=> fix(pruning): Check pruning in metadata calculator

core/node/node_framework/src/implementations/layers/circuit_breaker_checker.rs, core/node/node_framework/src/implementations/layers/commitment_generator.rs, core/node/node_framework/src/implementations/layers/contract_verification_api.rs, core/node/node_framework/src/implementations/layers/eth_sender.rs, core/node/node_framework/src/implementations/layers/eth_watch.rs, core/node/node_framework/src/implementations/layers/healtcheck_server.rs
This is the first PR in the queue.
Adds a description for the next wiring layers:
- `CircuitBreakerCheckerLayer`
- `CommitmentGeneratorLayer`
- `ContractVerificationApiLayer`
- `EthTxManagerLayer`
- `EthTxAggregatorLayer`
- `EthWatchLayer`
- `HealthCheckLayer`
=> feat(docs): Add documentation for subset of wiring layer implementations, used by Main node

core/lib/dal/src/proof_generation_dal.rs, core/lib/db_connection/src/instrument.rs, core/node/metadata_calculator/src/updater.rs
Removes a double insertion check from `insert_proof_generation_details()` in `ProofGenerationDal`.
It is not an error, and can and will happen if multiple full trees are run for the same node.
=> fix(db): Fix `insert_proof_generation_details()`

core/bin/zksync_server/src/node_builder.rs, core/lib/config/src/configs/chain.rs, core/lib/config/src/testonly.rs, core/lib/env_config/src/chain.rs, core/lib/protobuf_config/src/chain.rs, core/lib/protobuf_config/src/proto/config/chain.proto, core/node/node_framework/src/implementations/layers/state_keeper/output_handler.rs, core/node/vm_runner/src/impls/protective_reads.rs, etc/env/file_based/general.yaml
Makes `protective-reads-writer` actually write the data when it hasn't already been written by state keeper.
Next iteration of VM runner
=> feat(vm-runner): add protective reads persistence flag for state keeper

yarn.lock, zk_toolbox/Cargo.lock, zk_toolbox/Cargo.toml, zk_toolbox/crates/common/src/lib.rs, zk_toolbox/crates/common/src/slugify.rs, zk_toolbox/crates/zk_inception/Cargo.toml, zk_toolbox/crates/zk_inception/src/commands/chain/args/create.rs, zk_toolbox/crates/zk_inception/src/commands/chain/args/genesis.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/args/create.rs
Use slug crate for covering more problematic ecosystem names
=> fix(zk_toolbox): Use slug crate instead of self written function

core/bin/external_node/src/main.rs, core/bin/external_node/src/node_builder.rs, core/bin/zksync_server/src/node_builder.rs, core/lib/dal/.sqlx/query-daa330d43f150824f2195cdbfb96862d6ad0de7c7ca1d5320800f317428f07e1.json, core/lib/dal/src/vm_runner_dal.rs, core/node/consensus/src/testonly.rs, core/node/metadata_calculator/src/api_server/tests.rs, core/node/metadata_calculator/src/lib.rs, core/node/metadata_calculator/src/recovery/tests.rs, core/node/metadata_calculator/src/tests.rs, core/node/metadata_calculator/src/updater.rs, core/node/node_framework/examples/main_node.rs
=> feat(metadata-calculator): option to use VM runner for protective reads

core/bin/external_node/src/main.rs, core/node/metadata_calculator/src/helpers.rs, core/node/node_framework/src/implementations/layers/metadata_calculator.rs
Makes `LazyAsyncTreeReader::wait()` return an `Option` to make it clearer that not initializing is not necessarily an error (this decision is up to the caller).
Recent errors on ENs were caused by unwrapping `LazyAsyncTreeReader::wait()`. They partially masked the real error cause (not related to this task).
=> fix(merkle-tree): Change `LazyAsyncTreeReader::wait()` signature

core/lib/object_store/src/gcs.rs
Considers some token source GCS errors transient.
Considering errors as transient leads to less abnormal application terminations.
=> fix(object-store): Consider some token source errors transient

core/lib/basic_types/src/web3/mod.rs, core/lib/eth_client/src/clients/http/query.rs, core/lib/eth_client/src/clients/mock.rs, core/lib/eth_client/src/lib.rs, core/node/api_server/src/web3/namespaces/eth.rs, core/node/eth_sender/src/tests.rs, core/node/fee_model/src/l1_gas_price/gas_adjuster/mod.rs, core/node/fee_model/src/l1_gas_price/gas_adjuster/tests.rs, core/node/state_keeper/src/io/tests/tester.rs
Updated the codebase to support blob information in the  `eth_feeHistory` RPC method.
Changes GasAdjuster so that it only uses this method to retrieve info.
Use dedicated RPC method for getting info instead of custom implementation.
Less requests to L1.
Less code to maintain.
=> feat(gas_adjuster): Use eth_feeHistory for both base fee and blobs

zk_toolbox/crates/zk_inception/src/commands/ecosystem/args/init.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/init.rs, zk_toolbox/crates/zk_inception/src/messages.rs
Shortcut for developers, for not answering all questions
=> feat(zk_toolbox): Dev command

core/node/metadata_calculator/src/recovery/mod.rs
Fixes logging / observing metrics in the case a termination signal was received during tree recovery.
Logging / observing metrics in this case is misleading.
=> fix(merkle-tree): Fix chunk recovery reporting during tree recovery

Cargo.lock, core/lib/dal/src/lib.rs, core/lib/db_connection/Cargo.toml, core/lib/db_connection/src/connection.rs
- Makes readonly Postgres transaction have "repeatable read" isolation level by default.
- Allows specifying an isolation level in the transaction builder.
Readonly transactions usually expect a consistent DB view, hence the "repeatable read" isolation level.
=> fix(db): Fix / extend transaction isolation levels

core/lib/multivm/Cargo.toml, core/lib/multivm/src/versions/shadow.rs, core/lib/multivm/src/versions/vm_fast/vm.rs
Fixes refund-related bugs in the glue code for the new VM:
- Computes `pubdata_published` as a difference with the previous transaction
- Sets refund for the bootloader state
=> set_refund_for_current_tx

prover/vk_setup_data_generator_server_fri/src/commitment_utils.rs, prover/vk_setup_data_generator_server_fri/src/keystore.rs, prover/witness_generator/src/main.rs
Add file based config support for vk-setup-data-generator-server-fri
`KeyStore::default()` uses `FriProverConfig::from_env()` which panics when config is provided via files
=> feat(prover): Add file based config support for vk-setup-data-generator-server-fri

core/node/consensus/src/storage/mod.rs, core/node/consensus/src/testonly.rs, core/node/metadata_calculator/src/updater.rs, core/node/node_sync/src/sync_action.rs, core/node/node_sync/src/tests.rs
- Makes DB connections short-lived during main tree update loop.
- Propagates errors when queuing sync actions on EN.
- There's less chance of DB connection timeout during tree pruning. Realistically, such timeouts can occur when the tree is syncing if pruning is enabled.
- Propagating errors gets rid of potential panics during EN shutdown.
fix(en): Fix panics when queuing sync actions during shutdown
=> fix(merkle-tree): Fix connection timeouts during tree pruning

Cargo.lock, core/lib/state/Cargo.toml, core/lib/state/src/postgres/mod.rs, prover/Cargo.lock
Retries calling `read_value` when it fails with statement_timeout.
Eliminate sporadic failures.
=> feat(api): Retry `read_value`

core/lib/dal/migrations/20240708194915_vm_runner_processing_started_at_timestamp.down.sql, core/lib/dal/migrations/20240708194915_vm_runner_processing_started_at_timestamp.up.sql
=> fix(vm-runner): change `processing_started_at` column type to `timestamp`

prover/prover_fri/README.md, prover/vk_setup_data_generator_server_fri/src/commitment_utils.rs
Remove lazy loading of commitments in BWG
Add BWIP to docs
It is not needed, because it is called only once
=> feat: Remove cached commitments, add BWIP to docs

core/lib/basic_types/src/web3/mod.rs, core/lib/dal/src/models/storage_event.rs, core/lib/dal/src/transactions_web3_dal.rs, core/lib/types/src/api/mod.rs
timestamp should be (de)serialized as QUANTITY (hex string)
Follow proposal spec
=> fix(api): fix log timestamp format

Cargo.lock, Cargo.toml, core/lib/eth_client/src/clients/http/query.rs, core/lib/web3_decl/Cargo.toml, core/lib/web3_decl/src/client/mod.rs, core/lib/web3_decl/src/client/rustls.rs, prover/Cargo.lock
`jsonrpsee` client expects `rustls` to use the default crypto provider, but `rustls` cannot choose and panics if there are multiple providers available. See [this issue](https://github.com/rustls/rustls/issues/1877) for more detail.
Recently `rustls` changed the default backend, so now some (older) of crates use `ring` backend, while some (newer) use `aws-lc-rs`.
Until the issue is fixed on `jsonrpsee` side, we're making sure that the provider is installed before we create any `jsonrpsee` client.
Added test used to fail before the change and passes now.
Panics are bad.
=> fix: Fix rustls setup for jsonrpsee clients

core/bin/zksync_tee_prover/Cargo.toml, etc/nix/README.md, etc/nix/container-tee-prover.nix, etc/nix/devshell.nix, etc/nix/tee-prover.nix, etc/nix/zksync-server.nix, flake.lock, flake.nix
```
$ nix build -L .#tee_prover
$ nix build -L .#container-tee_prover-dcap
$ nix build -L .#container-tee_prover-azure
$ export IMAGE_TAG=$(docker load < result | grep -Po 'Loaded image.*: \K.*')
$ docker run -i --env GRAMINE_DIRECT=1 --env TEE_API_URL="http://127.0.0.1:3320" --privileged --init $IMAGE_TAG
```
=> feat: add zksync_tee_prover and container to nix

Cargo.lock, core/node/proof_data_handler/Cargo.toml, core/node/proof_data_handler/src/lib.rs, core/node/proof_data_handler/src/metrics.rs, core/node/proof_data_handler/src/request_processor.rs
Add metrics for witness input data blob sizes
To have deeper understanding of what is right and what is wrong
=> feat: Add blob size metrics

.github/workflows/ci-zk-toolbox-reusable.yml, core/lib/contracts/src/lib.rs, zk_toolbox/crates/common/src/cmd.rs, zk_toolbox/crates/common/src/git.rs, zk_toolbox/crates/common/src/lib.rs, zk_toolbox/crates/config/src/ecosystem.rs, zk_toolbox/crates/zk_inception/src/commands/chain/init.rs, zk_toolbox/crates/zk_inception/src/commands/chain/mod.rs, zk_toolbox/crates/zk_inception/src/commands/containers.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/create.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/init.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/mod.rs, zk_toolbox/crates/zk_inception/src/commands/prover/init_bellman_cuda.rs, zk_toolbox/crates/zk_inception/src/commands/prover/mod.rs, zk_toolbox/crates/zk_inception/src/main.rs, zk_toolbox/crates/zk_inception/src/messages.rs, zk_toolbox/crates/zk_supervisor/src/commands/test/mod.rs, zk_toolbox/crates/zk_supervisor/src/main.rs
Add aliases
Remove redundant l1 build
Create .env files 
Update submodules
=> feat(zk_toolbox): Small adjustment for zk toolbox

zk_toolbox/crates/zk_inception/src/main.rs
Fixes a bug for which it is impossible to run `zk_inception containers`.
The command required an impossible to supply subcommand due to the `#[command(subcommand,...` attribute.
```
❯ zk_inception containers
┌   ZKsync toolbox 
│
Run containers for local development
Usage: zk_inception containers [OPTIONS]
Options:
-h, --help  Print help
Global options:
-v, --verbose               Verbose mode
--chain <CHAIN>         Chain to use
--ignore-prerequisites  Ignores prerequisites checks
```
```
❯ zk_inception containers  -v
┌   ZKsync toolbox 
│
error: 'zk_inception containers' requires a subcommand but one was not provided
Usage: zk_inception containers [OPTIONS]
For more information, try '--help'.
```
Bug
=> fix: impossible to run zk_inception containers command

core/node/eth_sender/src/eth_tx_manager.rs
Makes eth_tx_manager emit less logs
Even if there is no activity (e.g. locally), `eth_tx_manager` keeps emitting a lot of logs, which makes it harder to understand what's going on with the server.
=> chore: Make eth_tx_manager logs less verbose

core/lib/config/src/configs/fri_prover.rs, core/lib/config/src/testonly.rs, core/lib/env_config/src/fri_prover.rs, core/lib/protobuf_config/src/proto/config/prover.proto, core/lib/protobuf_config/src/prover.rs, prover/proof_fri_compressor/Cargo.toml, prover/prover_fri/src/gpu_prover_availability_checker.rs, prover/prover_fri/src/gpu_prover_job_processor.rs, prover/prover_fri/src/main.rs, prover/prover_fri/src/socket_listener.rs, prover/prover_fri_utils/src/region_fetcher.rs, prover/witness_vector_generator/src/generator.rs, prover/witness_vector_generator/src/main.rs
~~When zone read domain name cannot be resolved, assumes local environment and uses `local` zone.~~
- Introduces a new config to choose cloud type, either GCP or local.
- Creates `RegionFetcher` structure that can fetch the zone based on configuration.
- Introduces strong typing for zone.
Makes it possible to run prover locally.
=> feat(prover): Make it possible to run prover out of GCP

core/lib/vlog/Cargo.toml, core/tests/test_account/Cargo.toml
A few more fixes that were required to publish packages.
Core workspace crates are already published under `crates.io-v0.1.0` tag.
Publishing on crates.io
=> chore: Publish fix-ups

core/lib/multivm/src/versions/vm_latest/bootloader_state/l2_block.rs, core/lib/multivm/src/versions/vm_latest/bootloader_state/state.rs, core/lib/multivm/src/versions/vm_latest/bootloader_state/utils.rs
It used to grow proportionally to the number of transactions in the L2 block squared.
=> perf: writing tx to bootloader memory is no longer quadratic

core/bin/external_node/src/config/mod.rs
the output format didn't match the expected consensus_secrets.yaml format.
=> fix: consensus secrets generator

etc/env/base/fri_witness_generator.toml, etc/env/base/fri_witness_vector_generator.toml, prover/docs/03_launch.md
Changes the default prometheus ports for prover binaries so that there is no need to override them when running together.
Updates the docs accordingly. Also mentions that you can run WVG with multiple threads.
Convenience.
=> docs(prover): Improve default configuration for prover binaries

etc/env/file_based/general.yaml, zk_toolbox/crates/zk_inception/src/commands/chain/genesis.rs
Fix the bug, where we don't send correct pub data with validium
=> fix(zk_toolbox): Set proper pubdata sending mode 

core/lib/multivm/src/versions/vm_fast/tests/refunds.rs, core/lib/multivm/src/versions/vm_fast/tests/utils.rs, core/lib/multivm/src/versions/vm_fast/vm.rs, core/lib/multivm/src/versions/vm_latest/tests/refunds.rs, core/lib/multivm/src/versions/vm_latest/tests/utils.rs, etc/contracts-test-data/contracts/expensive/expensive.sol
Fixes integer underflow in refund computation in the glue code for the new VM.
Leads to refund divergencies.
=> fix(vm): Fix operator refund divergency

core/node/node_framework/src/implementations/layers/consensus/external_node.rs, core/node/node_framework/src/implementations/layers/consensus/main_node.rs
consensus layer was incorrectly waiting for stop_receiver, while the panic/error should be propagated immediately.
=> fix: fixed panic propagation

core/lib/dal/.sqlx/query-3f9543c622a3877dd8612f3fc5f31867b3c0bff34bbacbc31ff4cd786c97ca90.json, core/lib/dal/src/consensus_dal.rs
Clean state at every fork is closer to what will happen during hard fork on L1.
=> feat: added dropping all attester certificates when doing hard fork

core/lib/vlog/src/lib.rs, core/lib/vlog/src/opentelemetry/mod.rs
Improves the `ObservabilityGuard` so that it flushes both sentry & otlp events on drop.
Without it, some events (at least for otlp) may be missed if the application exits right after events were produced.
=> feat(vlog): Implement otlp guard with force flush on drop

Cargo.lock, core/lib/protobuf_config/Cargo.toml, core/lib/protobuf_config/src/consensus.rs, core/lib/protobuf_config/src/eth.rs, core/lib/protobuf_config/src/general.rs, core/lib/protobuf_config/src/lib.rs, core/lib/protobuf_config/src/secrets.rs, core/lib/protobuf_config/src/snapshot_recovery.rs, prover/Cargo.lock, zk_toolbox/Cargo.lock
If config is partially serialized, do not throw an error just print it and the app, for which part the config is required will panic by itself
=> feat(configs): Do not panic if config is only partially filled

core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs, recompile_interpreter.sh
This PR fixes recompile_interpreter.sh for zksolc 1.5.0, which now puts the compiled interpreter on another folder, it also does not use the jump table (apparently)
=> [EVM-Equivalence-YUL] Fix zksolc changes

core/bin/zksync_server/src/node_builder.rs
Respect the configuration of namespaces when building the HTTP Web3 API layer.
This commit fixes a bug found when trying to run the node server with the following configuration:
```
API_WEB3_JSON_RPC_API_NAMESPACES=eth,web3,net,pubsub,zks,en,debug,unstable
```
This was added to the `etc/env/target/dev.env` file to test PR #2474. It turned out that the `unstable` namespace works fine for the WebSocket API but not for the HTTP API.
=> fix(node): respect namespaces configuration

.github/workflows/ci-zk-toolbox-reusable.yml, core/tests/ts-integration/src/env.ts, zk_toolbox/crates/zk_inception/src/commands/chain/args/create.rs, zk_toolbox/crates/zk_inception/src/commands/chain/create.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/args/create.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/create.rs, zk_toolbox/crates/zk_inception/src/messages.rs
Allow to run `zk_inception chain create` non-interactively and create custom chains within CI integration tests.
=> feat(zk_toolbox): allow to run `zk_inception chain create` non-interactively

Cargo.lock, core/lib/multivm/Cargo.toml, core/lib/multivm/src/versions/vm_fast/tests/rollbacks.rs, core/lib/multivm/src/versions/vm_fast/tests/tester/transaction_test_info.rs, core/lib/multivm/src/versions/vm_fast/tests/tracing_execution_error.rs, core/lib/multivm/src/versions/vm_fast/vm.rs, prover/Cargo.lock
Fixes unit tests that previously failed because of incorrect `Heap` comparisons.
Better test coverage.
=> test(vm): Fix fast VM unit tests

Cargo.lock, core/lib/state/src/lib.rs, core/lib/state/src/rocksdb/mod.rs, core/lib/state/src/storage_factory.rs, core/node/consensus/src/testonly.rs, core/node/node_sync/src/tests.rs, core/node/state_keeper/Cargo.toml, core/node/state_keeper/src/batch_executor/main_executor.rs, core/node/state_keeper/src/batch_executor/mod.rs, core/node/state_keeper/src/batch_executor/tests/read_storage_factory.rs, core/node/state_keeper/src/batch_executor/tests/tester.rs, core/node/state_keeper/src/keeper.rs, core/node/state_keeper/src/state_keeper_storage.rs, core/node/state_keeper/src/testonly/mod.rs, core/node/state_keeper/src/testonly/test_batch_executor.rs, core/node/state_keeper/src/tests/mod.rs, core/node/vm_runner/Cargo.toml, core/node/vm_runner/src/process.rs, core/node/vm_runner/src/storage.rs, core/node/vm_runner/src/tests/mod.rs, core/node/vm_runner/src/tests/process.rs, core/node/vm_runner/src/tests/storage.rs, core/node/vm_runner/src/tests/storage_writer.rs
- Refactors `ReadStorageFactory` and `BatchExecutor`.
- Tests the VM runner on multiple batch workloads and fixes bugs discovered by the tests (e.g., a data race in the storage loader).
- `ReadStorageFactory` and `BatchExecutor` become more composable and work in VM runner with less crutches.
- More tests allow fixing bugs in VM runner earlier.
fix(vm-runner): Fix data race in storage loader
test(vm-runner): Test VM runner with multiple L1 batches
=> refactor(state-keeper): Use owned VM storage for batch executor

core/lib/dal/src/consensus_dal.rs, core/node/consensus/src/en.rs
The error about receiving an unsupported consensus genesis was unnecessarily delayed. I've disallowed unknown fields in genesis to fix that.
=> fix: restrictive genesis parsing

Cargo.lock, Cargo.toml, core/bin/zksync_server/src/node_builder.rs, core/lib/multivm/Cargo.toml, core/lib/multivm/src/versions/shadow.rs, core/lib/multivm/src/versions/vm_fast/tests/gas_limit.rs, core/lib/multivm/src/versions/vm_fast/vm.rs, prover/Cargo.lock
- Bumps the `vm2` revision and moves it to the workspace manifest.
- Brushes up TODOs in the new VM code.
- Re-enables the TEE input producer.
Part of preparations to merge the feature branch into `main`.
=> chore(vm): Update VM revision and TODOs

Cargo.lock, core/lib/config/Cargo.toml, core/lib/config/src/observability_ext.rs, core/lib/vlog/src/lib.rs, prover/Cargo.lock
Adds more logs for observability lifecycle.
Easier to debug issues.
=> feat(vlog): Report observability config, flush, and shutdown

core/bin/zksync_server/src/node_builder.rs
Uses default experimental VM config if one is not supplied when initializing the state keeper.
Otherwise, the state keeper will panic on start if the config is missing. Logically, this config shouldn't be required for it to work (unlike for the VM playground).
=> fix(vm): Fix missing experimental VM config

.github/workflows/ci-zk-toolbox-reusable.yml, zk_toolbox/crates/zk_inception/src/commands/args/containers.rs, zk_toolbox/crates/zk_inception/src/commands/containers.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/args/init.rs, zk_toolbox/crates/zk_inception/src/messages.rs
Add observability interactive option
=> feat(zk_toolbox): Add observability interactive option

.github/workflows/ci-core-reusable.yml
Relax expected TPS for CI load tests.
The current expected TPS values are chosen too aggressively, leading to sporadic CI failures.
=> ci: Relax TPS for CI loadtest

zk_toolbox/crates/common/src/ethereum.rs
=> fix(zk_toolbox): Do not panic during mint

etc/nix/container-tee_prover.nix
Shrink the enclave size of `zksync-tee-prover`.
32G was a bit of safe guard while testing. 8G seems to be enough and will fit better the memory size of the Azure nodes.
=> fix: shrink enclave size of `zksync-tee-prover`

docker-compose-cpu-runner.yml, docker-compose-gpu-runner-cuda-12-0.yml, docker-compose-gpu-runner.yml, docker-compose.yml
This PR adds the `--http.corsdomain "*"` option to Docker Compose files to enable CORS (Cross-Origin Resource Sharing) on locally running Reth nodes.
Enables web applications like dapp-portal and block-explorer to make requests to the local RPC endpoint. Without CORS enabled, browser policies block these requests, causing the applications to fail.
=> feat: enable CORS for local reth

core/lib/db_connection/src/connection.rs, core/lib/db_connection/src/connection_pool.rs, core/lib/state/src/lib.rs, core/lib/state/src/storage_factory.rs, core/node/api_server/src/web3/state.rs, core/node/state_keeper/src/batch_executor/main_executor.rs, core/node/state_keeper/src/batch_executor/tests/read_storage_factory.rs, core/node/state_keeper/src/state_keeper_storage.rs, core/node/vm_runner/src/storage.rs, core/node/vm_runner/src/tests/mod.rs, core/node/vm_runner/src/tests/storage.rs
- Changes `Connection` so that it has `'static` lifetime if created from a pool (i.e., when it is non-transactional).
- Simplifies `ReadStorageFactory` and `MainBatchExecutor` accordingly.
Reduces complexity. `'static` connections can be sent to a Tokio task etc., meaning improved DevEx.
=> feat(db): Allow creating owned Postgres connections

prover/crates/bin/witness_generator/src/leaf_aggregation.rs, prover/crates/bin/witness_generator/src/node_aggregation.rs, prover/crates/bin/witness_generator/src/utils.rs
- Loading of proofs for each recursive circuit is now done asynchronously
- Each recursive circuit is now processed in a blocking thread, which speeds up serialization and other CPU-sensitive processing.
Locally, with additional artificial network delays (500 ms), a x5 speed up is observed
=> fix(prover): speed up LWG and NWG

core/lib/dal/.sqlx/query-c988b8aa7708a4b76671a8454c3e9806a8cb4031f7c11c6890213d8693e7d385.json, core/lib/dal/src/blocks_dal.rs, core/node/logs_bloom_backfill/src/lib.rs
Do not run heavy query if logs bloom migration was completed
Do not put additional load on DB
=> perf(logs-bloom): do not run heavy query if migration was completed

zk_toolbox/crates/zk_inception/README.md, zk_toolbox/crates/zk_inception/src/accept_ownership.rs, zk_toolbox/crates/zk_inception/src/commands/chain/init.rs, zk_toolbox/crates/zk_inception/src/commands/chain/mod.rs, zk_toolbox/crates/zk_inception/src/commands/chain/set_token_multiplier_setter.rs, zk_toolbox/crates/zk_inception/src/messages.rs
Add a top level command `zk_inception chain update-token-multiplier-setter`. It allows to invoke "IChainAdmin.setTokenMultiplierSetter` which will be useful for the chains with a custom base token that hasn't had that role before.
=> feat: add `update-token-multiplier-setter` command

core/lib/contract_verifier/src/lib.rs
Check for 0x in zkvyper output
Don't panic when bytecode is 0x prefixed
=> fix(contract-verifier): Check for 0x in zkvyper output

core/node/base_token_adjuster/src/base_token_ratio_persister.rs, core/node/base_token_adjuster/src/lib.rs, core/node/node_framework/src/implementations/layers/base_token/base_token_ratio_persister.rs
For backwards compatibility make setting token multiplier on L1 optional. If private key for token multiplier setter is not provided, L1 quote update will be skipped.
=> fix: make set token multiplier optional

core/bin/zksync_server/src/node_builder.rs
Base token ratio persister lacked L1 gas layer when started as a separate component.
=> fix: base token ratio startup as a separate component

core/bin/external_node/src/config/mod.rs, core/lib/config/src/configs/en_config.rs, core/lib/config/src/testonly.rs, core/lib/protobuf_config/src/en.rs, core/lib/protobuf_config/src/proto/config/en.proto, etc/env/configs/ext-node.toml, etc/env/file_based/external_node.yaml, zk_toolbox/crates/zk_inception/src/commands/external_node/prepare_configs.rs
=> feat: Add `gateway_url` to EN config

.prettierignore
Added `configs` folder in the root directory to `.prettierignore`
Ecosystem configs may include generated JS config files that may not pass `zk fmt --check`.
This change prevents errors during `zk fmt` execution.
=> fix: add default ecosystem configs folder to .prettierignore

docs/guides/launch.md
Encountered an issue when setting up new development environment: when running `zk init`, it would fail with the following error:
```text
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
$ ts-node scripts/compile-yul.ts compile-precompiles
Using zksolc from https://github.com/matter-labs/era-compiler-solidity/releases/download/prerelease-a167aa3-code4rena/zksolc-macosx-arm64-v1.5.0
Yarn project directory: /Users/jacob/Projects/zksync-era/contracts/system-contracts
Error: Cannot read properties of undefined (reading 'compilerPath')
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit …
```
=> chore(docs): adds instructions for `Cannot read properties of undefined (reading 'compilerPath')` error resolution

prover/crates/bin/proof_fri_compressor/src/compressor.rs
Compressor should fail when a corresponding fri prover job is not found. Unlikely to occur in real world but helps when manually populating DB for debugging.
This behaviour makes more sense
=> fix(prover): fail when fri prover job is not found

core/bin/external_node/src/config/mod.rs, core/lib/config/src/configs/chain.rs, core/lib/config/src/configs/experimental.rs, core/lib/protobuf_config/src/chain.rs, core/node/node_framework/src/implementations/layers/state_keeper/output_handler.rs
Changes default_protective_reads_persistence_enabled to false both for main and external node
For EN: it was confirmed that it works well without protective reads
For main node: it's expected that vm_runner_protective_reads is run by default
=> feat: Change default_protective_reads_persistence_enabled to false

Cargo.lock, core/lib/config/src/configs/base_token_adjuster.rs, core/lib/config/src/testonly.rs, core/lib/env_config/src/base_token_adjuster.rs, core/lib/protobuf_config/src/base_token_adjuster.rs, core/lib/protobuf_config/src/proto/config/base_token_adjuster.proto, core/node/base_token_adjuster/Cargo.toml, core/node/base_token_adjuster/src/base_token_ratio_persister.rs, core/node/base_token_adjuster/src/lib.rs, core/node/base_token_adjuster/src/metrics.rs
* Add cbt-related metrics;
* Move last hardcoded cbt-related properties to the config.
=> feat(Base token): add cbt metrics

core/lib/dal/doc/ProofGenerationDal.md
It should have been updated as part of these 2 PRs:
- https://github.com/matter-labs/zksync-era/pull/2258
- https://github.com/matter-labs/zksync-era/pull/2486
Update ProofGenerationDal docs chart.
We like up-to-date docs.
=> docs(dal): update ProofGenerationDal docs chart

core/lib/dal/src/models/storage_transaction.rs, core/tests/ts-integration/tests/api/web3.test.ts, zk_toolbox/crates/zk_supervisor/src/commands/database/reset.rs, zk_toolbox/crates/zk_supervisor/src/commands/test/prover.rs
Fixes `tx.gas_price` field for legacy and EIP-2930 transactions.
Follow the [spec](https://ethereum.github.io/execution-apis/api-documentation/)
=> fix(api): `tx.gas_price` field

core/lib/multivm/src/tracers/mod.rs, core/lib/multivm/src/tracers/validator/mod.rs, core/lib/vm_interface/src/lib.rs, core/lib/vm_interface/src/types/inputs/l2_block.rs, core/lib/vm_interface/src/types/inputs/mod.rs, core/node/api_server/src/execution_sandbox/apply.rs, core/node/api_server/src/execution_sandbox/execute.rs, core/node/api_server/src/execution_sandbox/mod.rs, core/node/api_server/src/execution_sandbox/testonly.rs, core/node/api_server/src/execution_sandbox/tests.rs, core/node/api_server/src/execution_sandbox/tracers.rs, core/node/api_server/src/execution_sandbox/validate.rs, core/node/api_server/src/tx_sender/mod.rs, core/node/api_server/src/tx_sender/tests.rs, core/node/api_server/src/web3/namespaces/debug.rs, core/node/api_server/src/web3/namespaces/eth.rs, core/node/api_server/src/web3/testonly.rs, core/node/api_server/src/web3/tests/mod.rs, core/node/api_server/src/web3/tests/vm.rs
Extracts oneshot VM executor from the API server crate.
Simplifies reasoning about oneshot VM execution and its maintenance. Allows for alternative implementations.
=> feat(vm): Extract oneshot VM executor interface

core/node/base_token_adjuster/src/metrics.rs
Fix a bug with base_token_adjuster metrics reported under a wrong namespace.
=> fix(base_token_adjuster): bug with a wrong metrics namespace

Cargo.lock, Cargo.toml, core/lib/multivm/Cargo.toml, core/lib/multivm/src/versions/vm_fast/tests/get_used_contracts.rs, core/lib/multivm/src/versions/vm_fast/tests/utils.rs, core/lib/multivm/src/versions/vm_latest/tests/get_used_contracts.rs, core/lib/multivm/src/versions/vm_latest/tests/utils.rs, etc/contracts-test-data/contracts/counter/counter.sol, etc/contracts-test-data/contracts/counter/proxy_counter.sol, prover/Cargo.lock
Fixes divergence in used bytecodes info between the old and new VMs.
The new VM behaved differently to the old VM on far call if decommitting the called contract leads to out-of-gas revert. The old VM records the called contract bytecode as decommitted in this case; the new one didn't.
=> fix(vm): Fix used bytecodes divergence

zk_toolbox/README.md, zk_toolbox/crates/zk_inception/README.md, zk_toolbox/crates/zk_inception/src/main.rs, zk_toolbox/crates/zk_inception/src/messages.rs
- Fix casing of "ZKsync" in READMEs and console messages in `zksync-era/zk_toolbox`
- ZKsync - correct
- zkSync - incorrect
- ZkSync (pascal case)
- PS: Some of those pascal cases may have been in purpose - let me know if I should revert any of those.
- Matches newer branding
=> fix(zk_toolbox): various ways of writing zksync

core/node/api_server/src/tx_sender/mod.rs, core/node/api_server/src/tx_sender/tests.rs, core/node/api_server/src/web3/testonly.rs
Fixes a duplicate DB connection getting acquired in the `eth_call` handler.
Extra connection leads to performance degradation.
=> fix(api): Fix duplicate DB connection acquired in `eth_call`

core/node/external_proof_integration_api/src/processor.rs
* Return correct binary(was ProofGenerationData before, but WitnessInputData needed)
* Request for specific batch was always returning the latest one
=> fix: return correct witness inputs

core/node/node_framework/src/implementations/layers/vm_runner/playground.rs, core/node/node_framework/src/implementations/resources/pools.rs
Fixes statement timeout errors in VM playground.
VM playground uses the replica DB pool, which has statement timeout configured by default. This timeout is intended for the API server and doesn't make sense for VM playground. Hence, this PR removes the statement timeout and allows to configure it for each built DB pool (in case other components would require similar changes).
=> fix(vm-runner): Fix statement timeouts in VM playground

core/lib/dal/src/tee_verifier_input_producer_dal.rs
Increase retries.
An alert fires when we hit maximum number of retries. Retries happen, for example, when a component restarts. Those restarts are transient and harmless. By increasing the number of retries, we reduce the number of false/spurious alerts.
=> fix(tee-prover): increase retries to reduce spurious alerts

prover/crates/bin/vk_setup_data_generator_server_fri/src/keystore.rs
Follow-up to #2785
We use `zksync_utils::env::locate_workspace` in our code, which behaves differently locally (uses `cargo locate-project` locally and does a fallback to `.` in docker), which is then altered via `..` in `core_workspace_dir_or_current_dir`, making the path resolution very hard.
I fix the issue so that it works both locally and in docker, and also add comments explaining how it works.
=> chore: Fix path resolution when running from compiled binary

core/node/genesis/src/lib.rs, core/node/node_storage_init/src/main_node/genesis.rs
Validate protocol version and vk hash from genesis config against L1
Right now nothing prevents from initializing contracts and node with different protocol versions or vk hashs, and it already happened 🥲
=> feat(genesis): Validate genesis config against L1

docs/guides/external-node/07_snapshots_recovery.md
Mentions treeless mode / tree data fetcher in the snapshot recovery guide.
Makes the treeless mode more discoverable.
=> docs(en): Mention treeless mode in snapshot recovery

zk_toolbox/crates/config/src/general.rs, zk_toolbox/crates/zk_inception/src/commands/chain/args/init.rs
Fixed port offset for newly created chains via `zk_inception`:
- Use `chain.id` instead of `chain.chain_id`
- Use `(chain.id - 1) * 100` as an offset to keep the port for the first chain as 3050
Using `chain.chain_id` was not intended as the resulting port number could potentially overflow.
=> fix(zk_toolbox): fix port offset for new chains

prover/crates/bin/prover_fri/src/gpu_prover_job_processor.rs
=> feat(prover): Add error to panic message of prover

core/node/eth_watch/src/client.rs
Removes querying from the earliest batch in eth watch. Instead queries for constant block range and splits queried range in parts if needed
Vanilla reth doesn't allow eth_logs requests where block range is greater than 1_000_000. This changes allows eth watch to work with this limitation.
=> feat(eth-watch): do not query events from earliest block

docker/proof-fri-gpu-compressor/Dockerfile
Add arch 80 to docker image of compressor
To be able to run it on NVIDIA A100
=> feat(prover): Make compressor build with 80 CUDA arch.

.github/workflows/cargo-license.yaml, deny.toml
- Allow new advisory (low impact; hard to fix).
- Omit printing the tree in output; because with it the output is not readable.
- Unblock CI
- Make cargo deny CI usable.
=> chore(ci): Fix cargo deny check and make output readable

prover/Cargo.lock, prover/crates/bin/proof_fri_compressor/src/compressor.rs, prover/crates/bin/proof_fri_compressor/src/main.rs, prover/crates/bin/prover_fri/src/gpu_prover_job_processor.rs, prover/crates/bin/prover_fri/src/main.rs, prover/crates/bin/prover_fri/src/prover_job_processor.rs, prover/crates/bin/prover_fri/tests/basic_test.rs, prover/crates/bin/vk_setup_data_generator_server_fri/src/commitment_generator.rs, prover/crates/bin/vk_setup_data_generator_server_fri/src/main.rs, prover/crates/bin/vk_setup_data_generator_server_fri/src/tests.rs, prover/crates/bin/witness_generator/src/leaf_aggregation.rs, prover/crates/bin/witness_generator/src/main.rs, prover/crates/bin/witness_generator/src/node_aggregation.rs, prover/crates/bin/witness_generator/src/recursion_tip.rs, prover/crates/bin/witness_generator/src/scheduler.rs, prover/crates/bin/witness_generator/tests/basic_test.rs, prover/crates/bin/witness_vector_generator/src/generator.rs, prover/crates/bin/witness_vector_generator/src/main.rs, prover/crates/bin/witness_vector_generator/tests/basic_test.rs, prover/crates/lib/keystore/Cargo.toml, prover/crates/lib/keystore/src/keystore.rs, prover/crates/lib/keystore/src/utils.rs
- Remove `Keystore::default`, which implicitly used env config to find the setup path.
- Remove dependency on `zksync_config` and `zksync_env_config` from keystore crate.
- Reduce the number of constructors for `Keystore`
- Pass `Keystore` instead of `setup_data_path` to the components to make access more explicit.
*What next?*
The following will be done separately to not overly expand the PR:
- Remove implicit lookups from `Keystore` completely. Config-less lookup should be done by the caller, not the keystore.
- Remove boilerplate code from `Keystore` (e.g. family of `load_x` and `load_y` methods -- this should be reworked as traits)
- Cover code with tests.
=> refactor(prover_keystore): Reduce number of Keystore constructors

etc/nix/container-tee_prover.nix
Passthrough env vars to the SGX enclave.
Relevant logs showcasing the issue:
https://grafana.matterlabs.dev/goto/1iFHMIeIg?orgId=1
To fix the bug.
=> fix(tee-prover): passthrough env vars to the SGX enclave

.github/workflows/ci-zk-toolbox-reusable.yml
Limits rayon threadpool size to 2 and tokio threadpool size to 4 in zk_toolbox CI.
I have checked locally, and with this configuration time to run integration tests is pretty close to the default configuration.
By default, both tokio and rayon will try to use all the CPUs. When we run multiple Rust binaries at the same time (3 servers and 3 ENs in our case), it causes a lot of conflict for resources, regardless of the number of CPUs.
=> chore(ci): Limit tokio/rayon pools for zk_toolbox CI

zk_toolbox/Cargo.lock, zk_toolbox/Cargo.toml, zk_toolbox/crates/zk_inception/Cargo.toml, zk_toolbox/crates/zk_inception/src/commands/chain/init.rs, zk_toolbox/crates/zk_inception/src/commands/external_node/prepare_configs.rs, zk_toolbox/crates/zk_inception/src/messages.rs
=> fix(zk_toolbox): set correct key configs

core/node/node_framework/src/implementations/layers/node_storage_init/external_node_strategy.rs, core/node/node_storage_init/src/external_node/snapshot_recovery.rs
- Fixes DB connection starvation during snapshot recovery. Caused by the insufficient number of connections in the DB pool provided to recovery logic.
- Additionally, fixes max concurrency of recovery not being set.
Connection starvation errors degrade UX.
=> fix(en): Fix connection starvation during snapshot recovery

core/node/consensus/src/en.rs
When a method is missing:
proxyd returns HTTP 403:  methodnotfound
while api server returns HTTP 200: methodnotfound
we need to handle both.
=> fix: handling of HTTP 403 thrown by proxyd

core/node/node_framework/src/service/mod.rs
"{err}" is not useful, because it truncates the stack trace of anyhow errors.
=> chore: log the whole error message when the task fails

zk_toolbox/crates/zk_supervisor/src/commands/test/args/integration.rs, zk_toolbox/crates/zk_supervisor/src/commands/test/integration.rs, zk_toolbox/crates/zk_supervisor/src/messages.rs
`zks t i` now accepts a `-t` flag that can can be used to specify a pattern. Only matching tests are run.
=> feat: allow specifying what tests to run with zks

Cargo.lock, core/bin/contract-verifier/src/main.rs, core/bin/system-constants-generator/src/main.rs, core/lib/contract_verifier/src/lib.rs, core/lib/contracts/src/lib.rs, core/lib/utils/Cargo.toml, core/lib/utils/src/env.rs, core/lib/utils/src/lib.rs, core/tests/loadnext/src/config.rs, core/tests/loadnext/src/fs_utils.rs, prover/Cargo.lock, prover/crates/bin/prover_cli/src/config/mod.rs, prover/crates/bin/prover_cli/src/helper.rs, prover/crates/bin/vk_setup_data_generator_server_fri/Cargo.toml, prover/crates/bin/vk_setup_data_generator_server_fri/src/vk_commitment_helper.rs, prover/crates/lib/keystore/src/keystore.rs, prover/crates/lib/keystore/src/utils.rs
- Removes `locate_workspace` and `workspace_dir_or_current_dir` methods.
- Instead, introduces `Workspace` type that is aware of different Cargo workspaces in the codebase.
The approach with a single `locate_workspace` doesn't work well for our codebase, since we have multiple workspaces. It resulted in some very implicit and convoluted code (see the removed `get_base_dir` in prover workspace).
New approach handles all 3 workspaces _plus_ the lack of a workspace.
=> feat(utils): Rework locate_workspace, introduce Workspace type

zk_toolbox/crates/config/src/wallet_creation.rs, zk_toolbox/crates/config/src/wallets.rs, zk_toolbox/crates/zk_inception/src/commands/chain/init.rs, zk_toolbox/crates/zk_inception/src/commands/chain/set_token_multiplier_setter.rs, zk_toolbox/crates/zk_inception/src/messages.rs
=> fix(zk-toolbox): Make token multiplier optional

zk_toolbox/crates/zk_inception/src/commands/prover/init.rs, zk_toolbox/crates/zk_inception/src/commands/prover/run.rs, zk_toolbox/crates/zk_supervisor/src/commands/prover/info.rs, zk_toolbox/crates/zk_supervisor/src/commands/prover/insert_batch.rs, zk_toolbox/crates/zk_supervisor/src/commands/prover/insert_version.rs
Fix getting chain config in zk_supervisor prover
Fix artifacts path when initializing.
Setup data path for provers
=> fix(zk_toolbox): secrets path, artifacts path

.github/workflows/ci.yml, core/tests/upgrade-test/tests/upgrade.test.ts, docker-compose-cpu-runner.yml, docker-compose-gpu-runner-cuda-12-0.yml, docker-compose-gpu-runner.yml, docker-compose.yml, zk_toolbox/Cargo.lock, zk_toolbox/crates/zk_supervisor/src/commands/test/rust.rs, zk_toolbox/crates/zk_supervisor/src/messages.rs
`cargo install --list` doesn't work properly in CI because we copy only binaries to zk-environment
also increase reth block-time and fixes upgrade-test which improves tests stability
we rely on cargo-nextest in tests
=> ci: fix using cargo nextest

.github/workflows/build-docker-from-tag.yml, .github/workflows/release-test-stage.yml
Add CUDA ARCH 80 to list of CUDA archs.
To be able to run provers on A100.
=> feat: Add 80 arch to cuda archs

etc/nix/tee_prover.nix
Strip `zksync_tee_prover` binary for nix package.
Somehow llvm decided to produce different symbol names each build
```diff
- 12916: 000000000194d628    48 OBJECT  LOCAL  HIDDEN    23 anon.c880a573512c356e53163839ee7cd669.742.llvm.17979232152659092167
+ 12916: 000000000194d628    48 OBJECT  LOCAL  HIDDEN    23 anon.c880a573512c356e53163839ee7cd669.742.llvm.14235143304249741099
[...]
```
Remove those to make the builds reproducible again.
=> fix(zksync_tee_prover): strip binary for nix package

Cargo.lock, Cargo.toml, core/node/eth_watch/Cargo.toml, core/node/eth_watch/src/client.rs
- `get_events_inner` should recursively call itself
- `get_events_inner` should allow passing `None` as topics and/or addresses
bug fix
=> fix(eth_watch): fix `get_events_inner`

core/lib/state/src/lib.rs, core/lib/state/src/storage_factory/metrics.rs, core/lib/state/src/storage_factory/mod.rs, core/lib/state/src/storage_factory/rocksdb_with_memory.rs, core/lib/state/src/storage_factory/snapshot.rs, core/lib/vm_executor/src/batch/factory.rs, core/lib/vm_executor/src/oneshot/metrics.rs, core/lib/vm_executor/src/oneshot/mod.rs, core/lib/vm_executor/src/shared.rs, core/lib/vm_interface/src/storage/mod.rs, core/lib/vm_interface/src/storage/view.rs, core/node/vm_runner/src/impls/bwip.rs, core/node/vm_runner/src/impls/playground.rs, core/node/vm_runner/src/impls/protective_reads.rs, core/node/vm_runner/src/io.rs, core/node/vm_runner/src/metrics.rs, core/node/vm_runner/src/output_handler.rs, core/node/vm_runner/src/process.rs, core/node/vm_runner/src/storage.rs, core/node/vm_runner/src/tests/mod.rs, core/node/vm_runner/src/tests/process.rs, core/node/vm_runner/src/tests/storage_writer.rs
Various minor improvements to VM runner / VM playground:
- Get batch storage asynchronously, so that it works efficiently with snapshot storage.
- Add metrics / logs to ensure that snapshot storage works as expected.
Improves usability.
=> refactor(vm-runner): Improve VM runner / VM playground

infrastructure/zk/src/docker.ts, zk_toolbox/crates/common/src/ethereum.rs
Increase confirmations in testing.
Should make CI workflows less flaky.
=> fix(zk_toolbox): increase confirmations in testing

Cargo.lock, core/bin/snapshots_creator/Cargo.toml, core/bin/snapshots_creator/src/creator.rs, core/bin/snapshots_creator/src/tests.rs, infrastructure/zk/src/docker.ts
Resumes an incomplete snapshot in the snapshot creator if the creator config doesn't specify an L1 batch.
This effectively reverts the relevant changes from https://github.com/matter-labs/zksync-era/pull/2256. It makes the snapshot creator resilient by default without additional setup, at the cost of parallel creator jobs working incorrectly (unless they all specify L1 batches).
=> feat(en): Resume incomplete snapshot in snapshot creator in more cases

docs/guides/external-node/09_decentralization.md, zk_toolbox/crates/zk_inception/src/commands/chain/set_token_multiplier_setter.rs
Fix `zki chain update-toen-multiplier-setter` to take the address from the chain config instead of the ecosystem.
=> fix: token multiplier setter is taken from chain config

core/node/external_proof_integration_api/src/lib.rs, core/node/external_proof_integration_api/src/metrics.rs, core/node/external_proof_integration_api/src/middleware.rs
Report reasons of failed calls in prover API metrics.
To have more observability
=> feat: emit errors in prover API metrics

etc/env/file_based/general.yaml
increases max_nonce_ahead in default config
fix flaky test
=> chore: increase max_nonce_ahead

docker/contract-verifier/Dockerfile, docker/external-node/Dockerfile, docker/prover-fri-gateway/Dockerfile, docker/prover-job-monitor/Dockerfile, docker/server-v2/Dockerfile, docker/snapshots-creator/Dockerfile, docker/verified-sources-fetcher/Dockerfile, docker/witness-generator/Dockerfile, docker/witness-vector-generator/Dockerfile
Change build-base image location from dockerhub to ghcr.io
Workaround for dockerhub rate-limiting
=> fix(ci): Switch build-base to ghcr.io

prover/crates/bin/witness_generator/src/artifacts.rs, prover/crates/bin/witness_generator/src/basic_circuits/artifacts.rs, prover/crates/bin/witness_generator/src/basic_circuits/job_processor.rs, prover/crates/bin/witness_generator/src/basic_circuits/mod.rs, prover/crates/bin/witness_generator/src/leaf_aggregation/artifacts.rs, prover/crates/bin/witness_generator/src/leaf_aggregation/job_processor.rs, prover/crates/bin/witness_generator/src/leaf_aggregation/mod.rs, prover/crates/bin/witness_generator/src/lib.rs, prover/crates/bin/witness_generator/src/node_aggregation/artifacts.rs, prover/crates/bin/witness_generator/src/node_aggregation/job_processor.rs, prover/crates/bin/witness_generator/src/node_aggregation/mod.rs, prover/crates/bin/witness_generator/src/recursion_tip/artifacts.rs, prover/crates/bin/witness_generator/src/recursion_tip/job_processor.rs, prover/crates/bin/witness_generator/src/recursion_tip/mod.rs, prover/crates/bin/witness_generator/src/scheduler/artifacts.rs, prover/crates/bin/witness_generator/src/scheduler/job_processor.rs, prover/crates/bin/witness_generator/src/scheduler/mod.rs, prover/crates/bin/witness_generator/src/utils.rs, prover/crates/bin/witness_generator/src/witness_generator.rs, prover/crates/bin/witness_generator/tests/basic_test.rs
Introduce WitnessGenerator trait
Rename some methods
=> feat(prover): WitnessGenerator refactoring #2

Cargo.lock, core/lib/prover_interface/Cargo.toml, core/lib/prover_interface/src/api.rs, core/lib/prover_interface/src/outputs.rs, core/lib/prover_interface/tests/job_serialization.rs, core/lib/types/Cargo.toml, core/lib/types/src/api/mod.rs, core/node/api_server/src/web3/testonly.rs, core/node/api_server/src/web3/tests/mod.rs, core/node/api_server/src/web3/tests/unstable.rs, core/node/proof_data_handler/src/tests.rs, prover/Cargo.lock
Following Anton's suggestion, we have switched to hex serialization for API/RPC requests and responses. Previously, we used default JSON serialization for Vec<u8>, which resulted in a lengthy comma-separated list of integers.
This change standardizes serialization, making it more efficient and reducing the size of the responses. The previous format, with a series of comma-separated integers for pubkey-like fields, looked odd.
Then:
```
curl -X POST\
-H "Content-Type: application/json" \
--data '{"jsonrpc": "2.0", "id": 1, "method": "unstable_getTeeProofs", "params": [491882, "sgx"] }' \
https://mainnet.era.zksync.io
{"jsonrpc":"2.0","result":[{"attestation":[3,0,2,0,0,0,0,0,10,<dozens of comma-separated integers here>
```
Now:
```
$ curl -X POST \
-H "Content-Type: application/json" \ …
```
=> feat(tee): use hex serialization for RPC responses

.github/workflows/build-runtime-base.yml
Proper platform names for docker build action
Docker documentation (which is linked in docker-build-action docs) [points to non-working reference](https://docs.docker.com/reference/cli/docker/buildx/build/#platform)
=> fix(ci): zksync-runtime-base proper platforms names

docker/contract-verifier/Dockerfile, docker/external-node/Dockerfile, docker/prover-fri-gateway/Dockerfile, docker/prover-job-monitor/Dockerfile, docker/server-v2/Dockerfile, docker/snapshots-creator/Dockerfile, docker/verified-sources-fetcher/Dockerfile, docker/witness-generator/Dockerfile, docker/witness-vector-generator/Dockerfile
Move building images to zksync-runtime-base
Workaround for dockerhub rate limits
=> feat(ci): Migrate to vendored image as a zksync-runtime-base

docs/guides/external-node/00_quick_start.md
- 30 GB of free disk space are no longer sufficient to run a testnet EN. Upped the system requirements to 50 GB.
- State growth is normally used to refer to the growth of the state tree, not of the historical state. What we have is historical state pruning, not state pruning.
=> docs: Update system requirements

flake.nix
Use precompiled `rocksdb` and `snappy` in the nix build.
Speeds up compilation and is usually better maintained.
=> feat(nix): use precompiled `rocksdb` and `snappy`

prover/crates/lib/prover_dal/.sqlx/query-0eac6f7b2d799059328584029b437891598dc79b5ed11258b2c90c3f282929ad.json, prover/crates/lib/prover_dal/.sqlx/query-1926cf432237684de2383179a6d0d001cdf5bc7ba988b742571ec90a938434e3.json, prover/crates/lib/prover_dal/.sqlx/query-39f60c638d445c5dbf23e01fd89a468057599be1e6c6c96a947c33df53a68224.json, prover/crates/lib/prover_dal/.sqlx/query-3a9ffd4d88f2cfac22835aac2512e61157bf58aec70903623afc9da24d46a336.json, prover/crates/lib/prover_dal/.sqlx/query-3bb8fbd9e83703887e0a3c196031b931c0d8dbc6835dfac20107ea7412ce9fbb.json, prover/crates/lib/prover_dal/.sqlx/query-434f7cb51a7d22948cd26e962679a67936d572f8046d3a1c7a4f100ff209d81d.json, prover/crates/lib/prover_dal/.sqlx/query-548414f8148740c991c345e5fd46ea738d209eb07e7a6bcbdb33e25b3347a08c.json, prover/crates/lib/prover_dal/.sqlx/query-63cf7038e6c48af8ed9afc7d6ea07edd87cb16a79c13e7d4291d99736e51d3b9.json, prover/crates/lib/prover_dal/.sqlx/query-75c1affbca0901edd5d0e2f12ef4d935674a5aff2f34421d753b4d1a9dea5b12.json, prover/crates/lib/prover_dal/.sqlx/query-aabcfa9005b8e1d84cfa083a47a700302981be0afef31a8864613484f8521f9e.json, prover/crates/lib/prover_dal/.sqlx/query-c19fc4c8e4b3a3ef4f9c0f4c22ed68c598eada8e60938a8e4b5cd32b53f5a574.json, prover/crates/lib/prover_dal/src/cli_test_dal.rs, prover/crates/lib/prover_dal/src/fri_witness_generator_dal.rs
In some places our sqlx queries are using string literals instead of query macros. This PR changes this behaviour in places it is possible.
To prevent possible SQL injections.
It also will cache the queries, which should make them faster.
=> feat(prover): Use query macro instead string literals for queries

.github/workflows/build-docker-from-tag.yml, .github/workflows/build-prover-fri-gpu-gar-and-circuit-prover-gpu-gar.yml, .github/workflows/build-prover-template.yml, .github/workflows/release-test-stage.yml, docker/circuit-prover-gpu-gar/Dockerfile, docker/circuit-prover-gpu/Dockerfile, docker/circuit-prover/Dockerfile, infrastructure/zk/src/docker.ts
This will enable us to build images for circuit proving (new version). Not tested.
=> feat(circuit-prover): Add circuit_prover Dockerfile and build rules

docs/guides/advanced/05_how_call_works.md
This PR fixes 2 invalid links in the documents which was caused by refactor (refactor: Split the rest of the zksync_core (https://github.com/matter-labs/zksync-era/pull/1940))
Unclarity in documentation
=> docs: fix invalid links to "namespaces/eth.rs" and "execution_sandbox.rs"

core/node/eth_sender/src/aggregator.rs
Removes deprecated proof loading for eth-sender
=> chore(eth-sender): remove deprecated proof loading

deny.toml
Adds https://rustsec.org/advisories/RUSTSEC-2024-0375 to `deny.toml`, which is due to `StructOpt`. 
* Currently it's impossible to migrate to clap as [zkevm_test_harness](https://github.com/matter-labs/era-zkevm_test_harness/blob/v1.5.0/Cargo.toml#L46) still depends on structopt.
* This [unblocks](https://github.com/matter-labs/zksync-era/actions/runs/11054218994/job/30710479095) the CI
=> fix: cargo-deny advisory due to structopt

zk_toolbox/crates/common/src/ethereum.rs, zk_toolbox/crates/zk_inception/src/commands/chain/common.rs
Use governor for minting process and do not panic if minting is not successful
=> fix(zk_toolbox): Do not panic if mint is not successful

.github/workflows/build-core-template.yml, docker/external-node/Dockerfile, docker/server-v2/Dockerfile
Removing deprecated `artifacts` dir from build process
=> fix(ci): Remove deprecated artifacts dir in contracts

core/lib/eth_client/src/clients/http/query.rs, core/lib/eth_client/src/clients/mock.rs
There was a wrong assertion: `if fee_history.inner.base_fee_per_gas.len() != fee_history.l2_pubdata_price.len()`. Instead `base_fee_per_gas.len()` should equal `l2_pubdata_price.len() + 1`.
Refactors code of l*_fee_history methods: 
- adds exhaustive assertions
- returns errors instead of only logging
=> fix(eth-client): fix l2_fee_history

zk_toolbox/crates/zk_inception/src/commands/prover/args/run.rs, zk_toolbox/crates/zk_inception/src/commands/prover/run.rs
Right now, while running prover binaries inside of zksync-era, config paths are specified as path to config from chain config(which is `./chain/configs` - relative path, but not absolute). This breaks, because to run prover binaries, shell enters prover directory of era.
=> fix(zk_toolbox): wrong configs path for prover binaries

docs/guides/external-node/00_quick_start.md, docs/guides/external-node/01_intro.md, docs/guides/external-node/04_observability.md, docs/guides/external-node/07_snapshots_recovery.md, zk_toolbox/crates/zk_inception/src/commands/update.rs, zk_toolbox/crates/zk_inception/src/main.rs
Update databases during update process, now it's a universal receipt how to pull changes
=> feat(zk_toolbox): Migrate db during update

.github/workflows/build-core-template.yml, docker/Makefile, docker/external-node/Dockerfile, docker/server-v2/Dockerfile
Creation of empty dirs, to support building from both new (foundry-built) and old contracts
=> fix(ci): Bring back hack for contracts build till full migration to foundry

.github/workflows/ci-core-reusable.yml, zk_toolbox/crates/config/src/secrets.rs, zk_toolbox/crates/zk_inception/src/commands/chain/args/genesis.rs, zk_toolbox/crates/zk_inception/src/commands/chain/genesis/database.rs, zk_toolbox/crates/zk_inception/src/commands/chain/genesis/mod.rs
Remove prover db from server init
prover db is not needed in server init since prover  db is initialized with prover init
=> fix(zk_toolbox): Remove prover db from server init

.github/workflows/zk-environment-publish.yml
Ability to build zk-env with cuda not only from push to main branch
=> fix(ci): Build zk-env with CUDA

.githooks/pre-push, core/lib/config/src/configs/eth_sender.rs, core/lib/config/src/testonly.rs, core/lib/env_config/src/eth_sender.rs, core/lib/protobuf_config/src/eth.rs, core/lib/protobuf_config/src/proto/config/eth_sender.proto, core/node/eth_sender/src/eth_fees_oracle.rs, core/node/eth_sender/src/eth_tx_manager.rs, core/node/fee_model/src/l1_gas_price/gas_adjuster/mod.rs, core/node/fee_model/src/l1_gas_price/mod.rs, etc/env/base/eth_sender.toml
Configuration parameter for time_in_mempool_cap, cap for time_in_mempool in eth-sender fee model + default values for parameter_a and parameter_b for GasAdjuster
=> feat(eth-sender): add time_in_mempool_cap config

zk_toolbox/README.md, zk_toolbox/crates/zk_inception/README.md
Remove `generate-sk` subcommand which doesn’t exist anymore.
=> docs(zk_toolbox): remove generate-sk subcommand references

zk_toolbox/crates/zk_supervisor/src/commands/test/args/integration.rs, zk_toolbox/crates/zk_supervisor/src/commands/test/mod.rs
Forces clap to allow hyphens after `zks test rust --options`
So that you can run sensible commands like `zks test rust --options "-E test(io::tests::continue_unsealed_batch_on_restart) --no-capture"`
=> fix(zk_toolbox): allow hyphens after `zks test rust --options`

core/lib/prover_interface/src/inputs.rs
Implement custom deserialize for VM run data
serde(deserialize_if) is not working with bincode
=> fix: bincode deserialization for VM run data

core/lib/config/src/configs/consensus.rs, core/lib/config/src/testonly.rs, core/lib/protobuf_config/src/consensus.rs, core/lib/protobuf_config/src/proto/core/consensus.proto, core/node/consensus/src/testonly.rs, etc/env/consensus_config.yaml, etc/env/en_consensus_config.yaml, etc/env/file_based/general.yaml, zk_toolbox/crates/config/src/consts.rs, zk_toolbox/crates/zk_inception/src/commands/chain/init/configs.rs, zk_toolbox/crates/zk_inception/src/commands/external_node/prepare_configs.rs, zk_toolbox/crates/zk_inception/src/consts.rs, zk_toolbox/crates/zk_inception/src/utils/consensus.rs, zk_toolbox/crates/zk_inception/src/utils/ports.rs
This reverts commit 25112df39d052f083bc45964f0298b3af5842cac.
=> revert(configs): Add port parameter to ConsensusConfig (#2986)

zk_toolbox/Cargo.lock, zk_toolbox/crates/zk_supervisor/Cargo.toml
Makes zks use a published version of sqruff-lib
zks is no longer installable (git version of sqruff-lib got bumped to 0.19.0 today)
=> chore(zk_toolbox): use published sqruff-lib

core/lib/dal/src/tee_proof_generation_dal.rs, core/node/api_server/src/web3/tests/unstable.rs, core/node/proof_data_handler/src/lib.rs, core/node/proof_data_handler/src/tee_request_processor.rs, core/node/proof_data_handler/src/tests.rs
Return `204` ([No Content][1]) HTTP status code if no proofs are available.
[1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204
We were getting an HTTP `200` response with `null` as the result when hitting the `/tee/proof_inputs` endpoint, which doesn’t seem right.
=> feat(proof-data-handler): return 204 HTTP status code if no proofs are available

docker/Makefile
Fix pseudo-check for contacts submodule in Makefile
=> fix(ci): Fix pseudo-check for contacts submodule in Makefile

.github/workflows/ci-docs-reusable.yml, docs/guides/external-node/00_quick_start.md
Stuff was left misformatted after https://github.com/matter-labs/zksync-era/pull/3060.
Seems like we don't run `zks fmt` on PRs that only touch MD files
=> chore(docs): run fmt on docs

core/lib/dal/src/blocks_dal.rs, core/lib/types/src/block.rs, core/lib/vm_interface/src/types/inputs/l1_batch_env.rs, core/node/genesis/src/lib.rs, core/node/node_sync/src/external_io.rs, core/node/state_keeper/src/io/mempool.rs, core/node/state_keeper/src/io/persistence.rs, core/node/state_keeper/src/io/tests/mod.rs
Ensures unsealed L1 batch is present in the DB even if we start with re-execution.
Leftover bug after #2846
=> fix(state-keeper): ensure unsealed batch is present during IO init

etc/nix/tee_prover.nix, etc/nix/zksync.nix, flake.nix
While `zksync` deps might not compile with nix, `tee_prover` deps must.
To enable nix incompatible changes in the workspace, separate the build process completely.
To enable nix incompatible changes in the workspace, which are unrelated to `tee_prover`.
=> fix(nix): separate `tee_prover` and `zksync` deps

core/node/consensus/src/en.rs, core/node/consensus/src/storage/store.rs, core/node/consensus/src/testonly.rs, core/node/consensus/src/tests/mod.rs
https://linear.app/matterlabs/issue/BFT-515/smooth-transition-from-json-rpc-to-p2p-syncing-for-ens
=> feat(consensus): smooth transition to p2p syncing (BFT-515)

Cargo.lock, core/lib/multivm/src/lib.rs, core/lib/multivm/src/versions/vm_fast/vm.rs, core/lib/multivm/src/vm_instance.rs, core/lib/vm_executor/Cargo.toml, core/lib/vm_executor/src/batch/factory.rs, core/lib/vm_executor/src/lib.rs, core/lib/vm_executor/src/testonly.rs
Fixes a regression introduced by https://github.com/matter-labs/zksync-era/pull/2915: The protocol version is now not checked before instantiating a fast VM.
Without this check, fast VM can be used with old protocol versions, which most likely will cause divergencies.
=> fix(vm): Check protocol version for fast VM

docs/guides/external-node/docker-compose-examples/configs/mainnet_consensus_config.yaml, docs/guides/external-node/docker-compose-examples/configs/testnet_consensus_config.yaml
Debug page address was set to 127.0.0.1:5000 on the consensus config file for the docker node. That didn't let users access the page from outside the container. It was set to 0.0.0.0:5000 and it now works.
=> fix: Changed debug page address on config file

core/bin/zksync_tee_prover/src/api_client.rs, core/bin/zksync_tee_prover/src/tee_prover.rs, core/lib/dal/src/tee_proof_generation_dal.rs, core/lib/prover_interface/src/api.rs, core/node/proof_data_handler/src/lib.rs, core/node/proof_data_handler/src/tee_request_processor.rs, core/node/proof_data_handler/src/tests.rs
This PR addresses Alex's code review comment:
https://github.com/matter-labs/zksync-era/pull/3017#discussion_r1795237929
and partially addresses this one too:
https://github.com/matter-labs/zksync-era/pull/3017#discussion_r1795240750
Simplify `TeeProofGenerationDataResponse`.
Because it's ugly.
=> fix(tee-prover): simplify TeeProofGenerationDataResponse

infrastructure/protocol-upgrade/README.md, infrastructure/protocol-upgrade/src/transaction.ts
Remove the calldata generated for `Governance.sol`. We don't use `Governance.sol` anymore and so this calldata is not needed. 
- [ x PR title corresponds to the body of PR (we generate changelog entries from PRs).
=> fix(protocol upgrade tool): Remove legacy from protocol upgrade tool

.github/workflows/build-prover-template.yml, infrastructure/zk/src/docker.ts
Add prover-autoscaler into old release workflow
ref ZKD-1855
=> ci: Add prover-autoscaler into old release workflow

zkstack_cli/crates/zkstack/README.md, zkstack_cli/crates/zkstack/src/commands/prover/args/init.rs, zkstack_cli/crates/zkstack/src/commands/prover/args/run.rs, zkstack_cli/crates/zkstack/src/commands/prover/run.rs, zkstack_cli/crates/zkstack/src/consts.rs
Add option to run prover images from tag, but not only latest.
=> feat: Add option to run prover images from tag

Cargo.lock, core/bin/zksync_tee_prover/Cargo.toml, core/node/proof_data_handler/Cargo.toml, core/node/proof_data_handler/src/lib.rs
Add zstd compression for the HTTP connection between `proof_data_handler` and `zksync_tee_prover`.
This enables faster intercloud communication.
=> fix(tee_prover): add zstd compression

core/bin/external_node/src/tests/mod.rs, core/node/node_framework/src/implementations/layers/state_keeper/external_io.rs, core/node/node_framework/src/implementations/layers/sync_state_updater.rs, core/node/node_sync/src/sync_state.rs
Returns `SyncState`-based health check, which was removed when transitioning to the node framework.
This health check looks useful and is used at least in some internal automations.
=> fix(en): Return `SyncState` health check

core/lib/dal/src/consensus_dal/mod.rs, core/node/consensus/src/en.rs
Random failures of consensus_global_config RPC may cause config reverts, until the consensus_genesis() RPC is fully deprecated. Although the problems of this sort are transient, this pr adds extra protection from this kind of situations to prevent unnecessary binary restarts.
=> fix(consensus): preventing config update reverts

etc/env/file_based/overrides/mainnet.yaml, etc/env/file_based/overrides/testnet.yaml
This PR increases the L1 Batch seadl default deadline from 1 hour to 8 hours.
- For lower TPS chains, this configuration matches reality better and is less wasteful in terms of Ethereum interactions.
- For higher TPS chains, the batches will be sealed by other seal criteria anyways
=> fix(zk chains): Increase Batch Seal Default Deadline

core/node/base_token_adjuster/src/base_token_l1_behaviour.rs
Stop converting `BigDecimal` to `BigInt` when logging to avoid loosing precision.
=> fix: update logging in cbt l1 behaviour

core/node/base_token_adjuster/src/base_token_ratio_provider.rs
Lowers no base token ratio log level to `WARN` instead of `ERROR`
It gets printed >500 times during integration tests making it hard to find the actual errors.
=> chore: lower no base token ratio log level

.github/workflows/build-contract-verifier-template.yml, .github/workflows/build-core-template.yml, .github/workflows/build-local-node-docker.yml, .github/workflows/build-prover-template.yml, .github/workflows/build-witness-generator-template.yml, .github/workflows/ci-common-reusable.yml, .github/workflows/ci-prover-e2e.yml, .github/workflows/ci-prover-reusable.yml, bin/ci_localnet_up, docker-compose-gpu-runner-cuda-12-0.yml, docker-compose-runner-nightly.yml, docker-compose-unit-tests.yml, docker-compose.yml, zkstack_cli/crates/common/src/docker.rs, zkstack_cli/crates/zkstack/src/commands/containers.rs, zkstack_cli/crates/zkstack/src/commands/dev/commands/clean/mod.rs, zkstack_cli/crates/zkstack/src/commands/dev/messages.rs
Host-bound volumes never get cleaned even if you do `docker compose down -v`. Existing dev flows don't seem to rely on volumes being on the host machine, so this is PoC of how we can move to Docker-managed volumes.
Avoid pesky bugs that prevent user from deleting `./volumes`, rely on Docker to persist and dispose of data as need be
=> feat(zkstack_cli): use docker-managed volumes

core/lib/dal/src/consensus_dal/mod.rs, core/node/consensus/src/en.rs, core/node/consensus/src/mn.rs, core/node/consensus/src/storage/connection.rs, core/node/consensus/src/storage/store.rs, core/node/node_framework/src/service/error.rs, core/node/node_framework/src/service/mod.rs
Added more debug information in case of payload mismatch.
Improved formatting of errors in the node_framework.
=> fix(consensus): better logging of errors

core/bin/external_node/src/node_builder.rs, core/bin/external_node/src/tests/mod.rs, core/lib/merkle_tree/src/domain.rs, core/lib/merkle_tree/src/errors.rs, core/lib/merkle_tree/src/lib.rs, core/lib/merkle_tree/src/storage/rocksdb.rs, core/lib/merkle_tree/src/storage/serialization.rs, core/lib/merkle_tree/src/types/internal.rs, core/lib/merkle_tree/src/types/mod.rs, core/lib/merkle_tree/tests/integration/domain.rs, core/node/metadata_calculator/src/api_server/metrics.rs, core/node/metadata_calculator/src/api_server/mod.rs, core/node/metadata_calculator/src/api_server/tests.rs, core/node/metadata_calculator/src/helpers.rs, core/node/metadata_calculator/src/lib.rs, core/node/node_framework/src/implementations/layers/metadata_calculator.rs
- Adds `/debug/nodes` and `/debug/stale-keys` endpoints for tree API to debug tree-related incidents.
- Allows to run tree API on EN without a tree.
Allows investigating tree-related incidents easier. Allowing to run tree API without a tree potentially improves UX / DevEx.
=> feat(metadata-calculator): Add debug endpoints for tree API

core/node/consensus/src/en.rs, core/node/consensus/src/mn.rs, yarn.lock
The attestation logic in consensus component is experimental, while p2p synchronization is critical. I've made the attestation controller non-critical, i.e. if attestation controller fails, an error is logged, but the consensus component keeps working (on both main node and external node). This should prevent situations like in https://www.notion.so/matterlabs/mainnet2-p2p-synchronization-downtime-12aa48363f2380e6b8e0c8e1c3728201?pvs=4
=> fix(consensus): made attestation controller non-critical

core/lib/dal/src/models/storage_transaction.rs, core/lib/types/src/api/mod.rs
Transaction receipt `root` was replaced by `status` in [EIP658](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-658.md). Since we already return `status` there is no need in having `root` too.
Fixes #3188 
It is actively harmful as it confuses some ETH tooling that considers having both `status` and `root` at the same time an invalid receipt.
=> feat(api): get rid of tx receipt root

core/lib/config/src/configs/prover_autoscaler.rs, core/lib/protobuf_config/src/proto/config/prover_autoscaler.proto, core/lib/protobuf_config/src/prover_autoscaler.rs, prover/crates/bin/prover_autoscaler/src/agent.rs, prover/crates/bin/prover_autoscaler/src/global/scaler.rs, prover/crates/bin/prover_autoscaler/src/global/watcher.rs, prover/crates/bin/prover_autoscaler/src/main.rs, zkstack_cli/crates/zkstack/completion/_zkstack.zsh
Add sending scale requests for Scaler targets.
Add dry-run config option for Scaler.
ref ZKD-1855
=> feat(prover): Add sending scale requests for Scaler targets

Cargo.lock, core/node/da_clients/Cargo.toml
Enable `tls-roots` feature in `tonic` crate.
Without this feature, the connection with the Eigen disperser can't be established
=> fix(da-clients): enable tls-roots feature for tonic

core/node/da_clients/Cargo.toml, core/node/da_clients/src/eigen/sdk.rs
Add the padding to the blob data in EigenDA client
The unpadded larger blobs can't be decoded by the EigenDA disperser.
=> fix(da-clients): add padding to the data within EigenDA blob

core/lib/config/src/configs/prover_autoscaler.rs, prover/crates/bin/prover_autoscaler/src/global/queuer.rs, prover/crates/bin/prover_autoscaler/src/global/scaler.rs, prover/crates/bin/prover_autoscaler/src/metrics.rs
Add `queue` metric to report autoscaler view of the queue.
Add Copy trait for QueueReportFields and remove unneeded clone or references.
The `queue` metric will be used in dashboards.
ref ZKD-1855
=> feat(prover): Add queue metric to report autoscaler view of the queue.

core/lib/multivm/src/versions/vm_latest/tracers/default_tracers.rs, core/lib/multivm/src/versions/vm_latest/tracers/result_tracer.rs
Currently, successful validations are reported as reverts, which is super confusing.
Why this is safe:
- `TracerExecutionStopReason::Finished` is only emitted on success, Errors always emit Abort instead
- Some of the removed code was just dead code. `self.result` was checked twice.
I'd rather fix the strange behaviour than emulate it to make ShadowVm line up.
=> chore: make artificially shortened executions count as successes

prover/crates/bin/prover_autoscaler/src/config.rs, prover/crates/bin/prover_autoscaler/src/k8s/watcher.rs, prover/crates/bin/prover_autoscaler/src/main.rs
If cluster_name isn't provided via flag, get it from GCP. Removes unused `cluster_name` config option.
To reduce possibility of errors in configs.
ref ZKD-1855
=> feat(prover): Add cluster name autodetection

.github/workflows/ci-core-lint-reusable.yml, rust-toolchain, zkstack_cli/Cargo.lock, zkstack_cli/crates/zkstack/completion/_zkstack.zsh, zkstack_cli/crates/zkstack/completion/zkstack.fish, zkstack_cli/crates/zkstack/completion/zkstack.sh, zkstack_cli/crates/zkstack/src/commands/dev/commands/lint.rs, zkstack_cli/crates/zkstack/src/commands/dev/commands/lint_utils.rs, zkstack_cli/rust-toolchain
Add linting target for Rust toolchains.
=> feat(zkstack_cli): Use the same rust toolchain as main repo

prover/Cargo.lock, prover/crates/bin/prover_autoscaler/Cargo.toml, prover/crates/bin/prover_autoscaler/src/config.rs
Remove unneeded dependencies.
Add default for graceful_shutdown_timeout.
ref ZKD-1855
=> fix(prover): Remove unneeded dependencies, add default for graceful_shutdown_timeout

deny.toml
Ignores RUSTSEC advisory for `derivative` crate being unmaintained
=> chore: ignore derivative advisory

core/node/metadata_calculator/src/recovery/tests.rs
Fixes RocksDB termination in a unit test.
Without such a termination, the test sporadically fails with the "terminate called without an active exception" message.
=> test(merkle-tree): Fix RocksDB termination in test

core/bin/external_node/src/config/mod.rs, core/bin/external_node/src/node_builder.rs, core/bin/external_node/src/tests/mod.rs, core/lib/config/src/configs/contracts.rs, core/lib/config/src/testonly.rs, core/lib/env_config/src/contracts.rs, core/lib/protobuf_config/src/contracts.rs, core/lib/protobuf_config/src/proto/config/contracts.proto, core/node/api_server/src/web3/namespaces/en.rs, core/node/api_server/src/web3/namespaces/zks.rs, core/node/api_server/src/web3/state.rs, zkstack_cli/crates/config/src/contracts.rs
for en: 
- renames prefixes: `user_facing_` -> `l1_`
- `ExternalNodeConfig::l1_diamond_proxy_address` is used instead of remote.diamon_proxy
for main node:
- remove `user_facing_diamond_proxy` and `user_facing_bridgehub` as duplicates for corresponding fields from l1 contracts config
Renaming for clarity (IMO l1_ prefix providers better understanding of what is put under variable)
Removing for config simplicity and avoiding duplication
=> feat(en): remove `user_facing_*` addresses

core/node/da_dispatcher/src/da_dispatcher.rs
Fix invalid `if` usage for `use_dummy_inclusion_data` flag.
=> fix: use_dummy_inclusion_data condition

Cargo.lock, core/lib/contract_verifier/Cargo.toml, core/lib/contract_verifier/src/compilers/mod.rs, core/lib/contract_verifier/src/compilers/solc.rs, core/lib/contract_verifier/src/compilers/vyper.rs, core/lib/contract_verifier/src/compilers/zksolc.rs, core/lib/contract_verifier/src/compilers/zkvyper.rs, core/lib/contract_verifier/src/lib.rs, core/lib/contract_verifier/src/resolver.rs, core/lib/contract_verifier/src/tests/mod.rs, core/lib/contract_verifier/src/tests/real.rs, core/lib/types/src/contract_verification_api.rs
- Supports the Vyper toolchain for EVM bytecodes in the contract verifier.
- Adds some more unit tests for the verifier (e.g., testing multi-file inputs, Yul contracts, abstract contract errors etc.).
Part of preparations to support EVM bytecodes throughout the codebase.
=> feat(contract-verifier): Support Vyper toolchain for EVM bytecodes

core/bin/zksync_server/src/node_builder.rs
Uses default experimental VM config when initializing the main node.
Currently, the experimental VM config is required in certain cases, which may lead to panics during node initialization.
=> fix(vm): Do not require experimental VM config

README.md, docs/src/SUMMARY.md, docs/src/guides/architecture.md
- Change order in `SUMMARY.md` so that it reads more naturally.
- Update `architecture.md`.
- Add links to the docs to the `README.md` at repo root.
=> chore(docs): Improve the core book

.github/workflows/zk-environment-publish.yml
Ability to publish zk-environment from manual trigger
Sometimes we need to force-update zk-environment
=> fix(ci): Ability to publish zk-environment from manual trigger

zkstack_cli/crates/zkstack/src/commands/chain/args/create.rs, zkstack_cli/crates/zkstack/src/commands/chain/create.rs
=> fix(zkstack): Fix duplicated chain layer

docker/circuit-prover-gpu-gar/Dockerfile, docker/circuit-prover-gpu/Dockerfile
Upgrade CUDA from 12.2 to 12.4 for circuit prover.
ref ZKD-2085
=> feat(prover): Bump CUDA to 12.4 for circuit prover

docker/circuit-prover-gpu/Dockerfile, docker/proof-fri-gpu-compressor/Dockerfile, docker/prover-gpu-fri/Dockerfile
Add CUDA cuobjdump output on binary after build.
To make sure that we build in all the needed GPU support.
ref ZKD-2085
=> feat(prover): Add cuobjdump output after prover builds

.github/workflows/build-docker-from-tag.yml, .github/workflows/build-prover-template.yml, .github/workflows/build-witness-generator-template.yml, .github/workflows/new-build-prover-template.yml, .github/workflows/new-build-witness-generator-template.yml, .github/workflows/release-test-stage.yml
Remove unneeded CUDA_ARCH 60 and 70.
Move needed CUDA_ARCH to default, so actual list will be in a single place after old CI cleanup.
Remove CUDA_ARCH from witness-generator build, it isn't used there.
To decrease build time and binary size.
ref ZKD-2123
=> ci: Remove unused CUDA_ARCH 60,70

Cargo.lock, core/node/state_keeper/src/io/mempool.rs, core/node/state_keeper/src/io/tests/mod.rs
Mempool io opens batch if there is protocol upgrade tx
Currently if mempool is empty but there is protocol upgrade tx, then batch is not opened
=> feat(state-keeper): mempool io opens batch if there is protocol upgrade tx

core/lib/contract_verifier/src/resolver/github/gh_api.rs
GH resolver wasn't adding `v` for zksolc/zkvyper, while our API expects it.
=> fix(contract-verifier): Fix version extraction in gh resolver

core/node/eth_sender/src/eth_fees_oracle.rs
We have a limit on priority fee, if an eth-sender transaction hits it, we panic. Currently eth-sender transactions may in some very rare situations hit this limits as base_fees may grow slower than priority_fees (it happened today), this change forces base_fee to grow at least as fast as priority fee.
=> feat(eth-sender): make base fee grow at least as fast as priority fee

core/lib/dal/migrations/20241226161705_add_ratio_timestamp_index.down.sql, core/lib/dal/migrations/20241226161705_add_ratio_timestamp_index.up.sql
This PR adds a migration that creates an index on `ratio_timestamp` field of `base_token_ratios` table.
Queries to this table are currently much heavier than they should be, that has to be optimized.
=> chore: create base_token_ratios_ratio_timestamp_idx index

core/lib/dal/.sqlx/query-18e351067537a6fc5d837f01778eeb89dcf134f97acb695e7f232cbd3839e81b.json, core/lib/dal/.sqlx/query-a8cc4da6200478a72a1b490d302b8a0949212bf66c602024aaa9843b4c66f965.json, core/lib/dal/src/eth_sender_dal.rs
optimize sql query
improve performance
=> perf(eth-sender): optimize sql query

Cargo.lock, core/lib/types/Cargo.toml, core/lib/types/src/abi.rs, core/lib/types/src/protocol_upgrade.rs, core/node/eth_watch/Cargo.toml, core/node/eth_watch/src/client.rs, core/node/eth_watch/src/event_processors/decentralized_upgrades.rs, core/node/eth_watch/src/lib.rs, core/node/eth_watch/src/tests/client.rs, core/node/eth_watch/src/tests/mod.rs, core/node/node_framework/src/implementations/layers/eth_watch.rs, prover/Cargo.lock, zkstack_cli/Cargo.lock
Copies protocol upgrade schema changes from sync-layer-stable in a non-breaking way.
Support post-gateway upgrade schema.
=> feat(eth-watch): Change protocol upgrade schema

.github/workflows/ci-prover-e2e.yml, core/lib/l1_contract_interface/src/i_executor/methods/prove_batches.rs
=> chore: Fix prove e2e

docker/zk-environment/22.04_amd64_cuda_11_8.Dockerfile, docker/zk-environment/22.04_amd64_cuda_12.Dockerfile
Change of deprecated nvidia repos to newer ones, and changing from ubuntu 20 repos to ubuntu 22
=> fix: Zk-environment proper Nvidia driver repos

docker/zk-environment/22.04_amd64_cuda_11_8.Dockerfile, docker/zk-environment/22.04_amd64_cuda_12.Dockerfile
=> fix: Zk-environment fix Nvidia repo add

zkstack_cli/crates/zkstack/src/commands/dev/commands/database/migrate.rs
`zkstack dev migrate` attempts to create a database first before performing the migration. It should instead only try to perform the migration, and fail if the database does not exist.
Keeping the create database command may potentially drop and recreate the database - the current behaviour of `cargo sqlx database create` doesn't do this, but it may change in the future. Furthermore, even if the database doesn't exist, it doesn't make sense for a migrate command to perform database creation.
=> fix(zkstack): shouldn't attempt to create db on migrate command

core/node/eth_sender/src/aggregator.rs
fixes eth aggregator restrictions
=> fix: eth aggregator restriction

core/node/fee_model/src/l1_gas_price/main_node_fetcher.rs
Alternative to https://github.com/matter-labs/zksync-era/pull/3487
Before this PR EN based its gas pricing solely on main node's fee params which are based on immediate market conditions and not representative of the open batch's fee input. This is a problem on environments with long-running batches. This PR makes EN fetch main node's batch fee input along with fee params and report fetched batch fee input from its fee input provider.
=> fix(en): make EN use main node's fee input

zkstack_cli/crates/zkstack/build.rs
Fixes `zkstack` completion for `zsh` shell.
For `zsh` shell default completion will fail with the following error:
`command not found: compdef`
because autocompletion is not activated by default.
This PR adds the following to activate it on `zsh` in addition to `source` of the autocompletion script:
```
autoload -Uz compinit
compinit
```
*[Related thread](https://unix.stackexchange.com/questions/339954/zsh-command-not-found-compinstall-compinit-compdef)
=> chore: fix zkstack completion for zsh

.github/workflows/ci-core-reusable.yml, core/tests/recovery-test/package.json, core/tests/revert-test/package.json, core/tests/ts-integration/package.json, core/tests/ts-integration/src/context-owner.ts, core/tests/ts-integration/src/helpers.ts, core/tests/ts-integration/src/retry-provider.ts, core/tests/ts-integration/tests/fees.test.ts, core/tests/upgrade-test/package.json, yarn.lock
A bunch of small improvements to make fee tests robust:
* Upgrade ethers
* Catch retryable networking issues in `ethers.FetchRequest`
* Destroy providers on context teardown to avoid econnreset
* Retry fee-related issues that can arise when transaction is rejected by mempool
Fee tests are disruptively flaky right now
=> test: make fee tests robust

core/node/eth_watch/src/client.rs
=> fix(gateway): erc20 workaround for gateway upgrade

core/lib/multivm/src/utils/mod.rs, core/node/api_server/src/web3/namespaces/zks.rs
- Use scaled version of batch fee input in get_batch_fee_input_impl
- Improve adjust_pubdata_price_for_tx so it assumes optimistic scenario
Scaled fee input should be used for every user-facing API method
=> fix(api): use scaled version of batch fee input in `get_batch_fee_input_impl`

.github/workflows/build-circuit-prover-gpu-gar.yml, .github/workflows/build-docker-from-tag.yml, .github/workflows/build-proof-fri-gpu-compressor-gar.yml, .github/workflows/build-prover-template.yml, .github/workflows/release-test-stage.yml
Remove prover-gpu-fri and witness-vector-generator from build.
To cleanup unneeded builds.
ref ZKD-2084
=> ci: Remove prover-gpu-fri and witness-vector-generator from build

core/lib/prover_interface/src/outputs.rs, core/lib/prover_interface/tests/job_serialization.rs
Add `#[serde(untagged)]` for L1BatchProofForL1 to ensure backwards compatibility.
=> fix: JSON proof serialization

.github/workflows/ci-core-reusable.yml, core/tests/ts-integration/src/helpers.ts
In a very unlikely scenario timeouted tx can still succeed in the short window while we are resubmitting it with updated gas. This PR handles this gracefully + another case when nonce might have been used asynchronously by someone else.
Good ol' flakiness
=> ci: fix nonce reuse

prover/crates/lib/keystore/src/keystore.rs
Load compressor setup data from the right dir
=> fix: Compressor setup data

core/bin/external_node/README.md
dummy change to trigger release-please PR
=> fix: add . to readme

prover/crates/bin/witness_generator/src/main.rs
Allow witness_generator to use Prometheus push gateway in continuous mode.
Log which metrics method is used on start.
To keep receiving metrics in any running mode.
=> fix: Allow witness_generator to use Prometheus push gateway in continuous mode

core/node/api_server/src/tx_sender/gas_estimation.rs
Fixes the `gas_per_pubdata_limit` field calculation. Right now, we provide the value we get from deriving the existing batch input, which is most likely lower than limit provided in fee estimation request.
Given that we scale the overall fee, it should be safe to scale the limit as well, as long as we don't go beyond the limit supplied in the tx.
Providing the limit as-is without scaling can be very flaky: transaction risks to be left in the mempool over minor `gas_per_pubdata` changes.
=> fix(api): Improve estimation for gas_per_pubdata_limit

core/Cargo.lock, core/Cargo.toml, core/lib/basic_types/src/secrets.rs, core/lib/config/src/configs/consensus.rs, core/lib/config/src/testonly.rs, core/lib/env_config/src/da_client.rs, core/lib/protobuf_config/src/secrets.rs, core/node/commitment_generator/src/validation_task.rs, core/node/consensus/src/config.rs, core/node/da_clients/Cargo.toml, core/node/da_clients/src/avail/sdk.rs, core/node/da_clients/src/eigen/client.rs, prover/Cargo.lock, zkstack_cli/Cargo.lock
Made sure that we only have one version of jsonrpsee in our dependencies now and that version is latest (new version is also a bit lighter as they finally stopped depending on wasm libraries for non-wasm targets). Had to adapt to breaking changes in `secrecy` as a side effect.
=> chore: upgrade jsonrpsee and subxt

core/lib/basic_types/src/protocol_version.rs, core/lib/types/src/abi.rs, core/lib/types/src/protocol_upgrade.rs, core/lib/vm_executor/src/oneshot/contracts.rs, core/lib/vm_executor/src/storage.rs, core/node/eth_watch/src/tests/client.rs, core/node/genesis/src/utils.rs, core/tests/upgrade-test/tests/upgrade.test.ts
Fixes the upgrade workflow with new L1 contracts.
The existing workflow doesn't work because of changes in `ProposedUpgrade` (+ some stubs in the codebase).
=> fix: EVM emulation integration – upgrade workflow fixes

core/lib/env_config/src/da_client.rs
Allow configuring NoDA client via environment variables.
This is required by the partners running chains using ENV-based configuration.
=> fix: allow configuring NoDA client via ENV

.github/workflows/release-please.yml
Update `Cargo.lock` files in other workspaces in release PRs.
To prevent release CI failures due to outdated `Cargo.lock` files in other workspaces.
=> ci: update Cargo.lock files in other workspaces in release PRs

.github/workflows/vm-perf-comparison.yml
Fix permissions in VM perf tests
In external contributions we have all the VM perf test runs failing with the `Error: Resource not accessible by integration` error like [here](https://github.com/matter-labs/zksync-era/actions/runs/13282215771/job/37083063381?pr=3584).
=> fix: add permissions to fix failing VM perf CI runs

core/Cargo.lock, core/Cargo.toml, prover/Cargo.lock, zkstack_cli/Cargo.lock
Bump Cargo to 26.4.0.
To correspond to the release-please config after merge without Cargo.toml and Cargo.lock updates.
=> chore: bump cargo toml to 26.4.0

.github/workflows/release-please.yml, .github/workflows/release-zkstack-bins.yml, zkstack_cli/Cargo.toml
Release `zkstack` binary with each `zkstack_cli` release.
When `zkstack_cli` release PR is merged, an additional job will be triggered to build and publish `zkstack` executables for Linux and MacOS platforms to the release artifacts.
=> ci: release zkstack binary with zkstack_cli releases

core/node/api_server/src/tx_sender/master_pool_sink.rs
Fixes the lock for simultaneous tx insertion with mutex.
The previous approach could lead to a "stuck" state if the task panics/get canceled before hashmap entry is cleaned.
This shouldn't happen now with guard removing entry on drop.
No changes
=> fix(api): lock simultaneous tx insertsion with mutex

core/node/da_clients/src/avail/sdk.rs
Increase Avail max blob size to 1 MB.
Avail now supports larger blobs, we can adjust our constants now.
=> feat(da-clients): raise Avail blob size to 1mb

core/node/da_clients/src/avail/sdk.rs, core/node/da_dispatcher/src/da_dispatcher.rs, zkstack_cli/crates/types/src/l1_network.rs
- Fix `balance` in Avail client
- Improve error handling in `da_dispatcher`'s `poll_for_inclusion` function
- Update the AvailL1DAValidator for Sepolia
=> chore(validium): improve error handling, update AvailL1DAValidator address

zkstack_cli/crates/config/src/general.rs
Set correct default core_object_store path i.e. `chains/<CHAIN_NAME>/artifacts`, currently it's just `artifacts`
If >1 chain is initted they should store artifacts in different folders
Nothing
=> fix(zkstack_cli): default core_object_store path

core/lib/state/src/postgres/metrics.rs, core/lib/state/src/postgres/mod.rs, core/lib/state/src/postgres/tests.rs
Switches `PostgresStorageCachesTask` to use a watch channel for update commands instead of an unbounded MPSC one.
Under load, update commands can be queued faster than they are processed, and the existing logic to drop the cache if it's too far behind the current L2 block is never triggered (while it should).
=> perf(api): Use watch channel in values cache updates

.github/workflows/cargo-license.yaml, docker/zk-environment/Dockerfile
rustup broke installation of default toolchain in v1.28.0, it has to be installed manually now.
See https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html
To fix zk-environment-publish.yml and Cargo licence check CIs.
=> fix: Install needed rust toolchain

prover/crates/bin/prover_autoscaler/src/global/manager.rs
Add `autoscaler_queue` metric back.
`autoscaler_queue` metric is used in dashboard to show current queue per scaler target.
ref ZKD-2229
=> fix: Add autoscaler_queue metric back

.github/workflows/build-circuit-prover-gpu-gar.yml, .github/workflows/build-proof-fri-gpu-compressor-gar.yml
Stop copying unneeded setup-data files into each circuit-prover-gpu-gar and proof-fri-gpu-compressor-gar images.
To reduce docker image size and startup time.
ref ZKD-2469
=> ci: Stop copying unneeded setup-data files into each gar images

core/Cargo.lock, core/lib/zk_os_merkle_tree/Cargo.toml, core/lib/zk_os_merkle_tree/examples/loadtest.rs, core/lib/zk_os_merkle_tree/src/hasher/proofs.rs, core/lib/zk_os_merkle_tree/src/lib.rs, core/lib/zk_os_merkle_tree/src/metrics.rs, core/lib/zk_os_merkle_tree/src/storage/mod.rs, core/lib/zk_os_merkle_tree/src/storage/patch.rs, core/lib/zk_os_merkle_tree/src/storage/rocksdb.rs, core/lib/zk_os_merkle_tree/src/storage/tests.rs, core/lib/zk_os_merkle_tree/src/tests.rs, core/lib/zk_os_merkle_tree/src/types/mod.rs
- Implements proofs for read operations in the ZK OS Merkle tree. Adds tree API to get such proofs asynchronously.
- Adds metrics for the tree.
- Allows batches writes / in-memory buffering for the tree.
- Read proofs are necessary for ZK OS integration.
- Metrics are necessary for observability.
- In-memory buffering improves performance.
=> feat(zkos): Merkle tree follow-ups

core/lib/web3_decl/src/namespaces/unstable.rs, core/node/api_server/src/web3/backend_jsonrpsee/namespaces/unstable.rs, core/node/api_server/src/web3/namespaces/unstable/mod.rs
add endpoint supports_unsafe_deposit_filter
Having this functionality for main nodes is strongly recommended for v26 upgrade. Endpoint allows to check if node is "ready" from outside.
No changes
=> feat(api): add endpoint supports_unsafe_deposit_filter

docker/proof-fri-gpu-compressor-gar/Dockerfile
Hack to make compressor works with setup-data in a different place vs provers.
ref ZKD-2456
=> fix: Hack to make compressor works with setup-data in a different place vs provers

.github/workflows/cargo-license.yaml, .github/workflows/publish-crates.yml, .github/workflows/release-please.yml, core/Cargo.lock, core/bin/custom_genesis_export/Cargo.toml, core/lib/queued_job_processor/Cargo.toml, core/lib/test_contracts/Cargo.toml
Fix crates.io publishing.
To unblock `core` crates.io publishing in CI.
=> chore: fix crates.io publishing

core/lib/contract_verifier/src/lib.rs, core/lib/contract_verifier/src/tests/real.rs, core/lib/types/src/contract_verification/contract_identifier.rs
I've discovered that partial verification doesn't work correctly for EVM contracts, because we expect creation bytecode to be equal for compiled and deployed contracts. This is too strict, because it's OK for them to be different in metadata hash only.
I didn't add any tests for this (it was somewhat tricky), but checked manually that the issue was resolved after that.
=> fix(contract-verifier): Correctly process partial verification for EVM contracts

core/node/eth_watch/src/client.rs
split heavy get logs requests if got error 503
We use proxyd that proxies mostly vanila reth nodes in our setup, some get_logs requests with big block range take a lot of time so they can rejected in proxyd by timeout, in this case 503 is returned. We should split such requests into smaller so they can be processed.
No
=> feat(eth-watch): split heavy get logs requests if 503

core/lib/multivm/src/lib.rs
Exposes `IntoOldVmTracer`
Currently it is impossible to create new multivm tracers outside of this crate
=> chore: make `IntoOldVmTracer` public

prover/crates/bin/prover_fri_gateway/src/rpc_server/mod.rs
Change WS server URL to 0.0.0.0 from 127.0.0.1
For the server to be externally discoverable
=> fix: API URL for prover gateway

core/tests/ts-integration/tests/base-token.test.ts
This was not the case until the chain creation params patch. We already have unit tests for similar behavior in `era-contracts` repo, but it is better to have one here as well, especially considering that it is lightweight
=> test: Test that the wrapped base token has correct metadata

zkstack_cli/crates/zkstack/src/messages.rs, zkstack_cli/crates/zkstack/src/utils/forge.rs
Current prompt for balance check is not clear (it implies that you need 5 ETH in order to proceed; which isn't what it does).
This PR makes it more clear and gives user a choice to exit.
=> feat(zkstack): Clarify prompt for funds check

core/lib/protobuf_config/src/da_client.rs
Make `eigenda_eth_rpc` in Eigen config optional in proto configs
This was incorrectly forced to be "required" despite the actual config field being optional
=> fix: make eigenda_eth_rpc in Eigen config optional in file-based configs

core/node/node_sync/src/data_availability_fetcher/mod.rs
The EN database is populated with the `inclusion_data` received from the DA layer, not from the main node.
In case the main node has no inclusion data, but the DA layer returns some - it is being stored in the DB. Later on it is used in `consistency_checker` which will lead to it failing.
To prevent inconsistency in `inclusion_data` field that will lead to `consistency_checker` failing.
=> fix(data-availability-fetcher): prevent EN database from being populated with unnecessary inclusion data

core/bin/external_node/src/node_builder.rs, core/bin/zksync_server/src/node_builder.rs
- Reuse `eigenda_eth_rpc` from 'required' config in EN
- make DA client wiring more readable
In ENs, the `eigenda_eth_rpc` wasn't replaced with the one from L1 config if it was empty, which deviates from the main node behavior.
=> fix: reuse eigenda_eth_rpc from 'required' config in EN

core/lib/contract_verifier/src/etherscan/errors.rs, core/lib/contract_verifier/src/etherscan/mod.rs, core/lib/contract_verifier/src/etherscan/types.rs, core/lib/dal/migrations/20250321121118_requeue_failed_etherscan_verifications.down.sql, core/lib/dal/migrations/20250321121118_requeue_failed_etherscan_verifications.up.sql
When a contract is not yet indexed by Etherscan and we try to verify it, the following error is returned:
`Unable to locate ContractCode at <address>`. This PR adds proper processing for such errors to give Etherscan time to index the contract.
Currently, `Unable to locate ContractCode` errors are not properly processed, and as a result, the verification requests fail.
=> fix(contract-verifier): handle errors when the contract code is unavailable in Etherscan

core/lib/multivm/src/versions/shadow/tests.rs, core/lib/multivm/src/versions/testonly/evm.rs, core/lib/multivm/src/versions/testonly/simple_execution.rs, core/lib/multivm/src/versions/vm_fast/tests/evm.rs, core/lib/multivm/src/versions/vm_fast/tests/simple_execution.rs, core/lib/multivm/src/versions/vm_latest/tests/evm.rs, core/lib/multivm/src/versions/vm_latest/tests/simple_execution.rs, core/lib/test_contracts/contracts/counter/counter.sol, core/lib/test_contracts/evm-contracts/evm.sol, core/lib/test_contracts/src/contracts.rs
Adds some more unit tests for the EVM emulator, closing some TODOs.
More test coverage is better.
=> test(vm): Test EVM emulator in `multivm` crate (pt. 2)

.github/workflows/build-tee-prover-template.yml, etc/nix/container-tee-prover-tdx.nix, flake.nix
- Added `container-tee-prover-tdx` to supported TEE prover containers.
- Introduced a new Nix derivation for the TDX container image, including dependencies and configuration. This enhances compatibility with Intel TDX environments.
This will enable us to run the `zksync_tee_prover` in the TDX VM.
=> feat(zksync_tee_prover): add TDX support for containerized TEE prover

core/bin/zksync_tee_prover/src/error.rs
- Added `GATEWAY_TIMEOUT` and `INTERNAL_SERVER_ERROR` to retriable errors.
- Enhances resilience by accounting for more transient HTTP errors.
- Ensures better alignment with standard HTTP error handling practices.
Prevents failing the service on retriable errors
=> fix(zksync_tee_prover): refine retriable HTTP error handling

core/lib/state/src/postgres/mod.rs, core/lib/types/src/api/state_override.rs, core/lib/vm_interface/src/storage/overrides.rs, core/node/api_server/src/execution_sandbox/execute.rs, core/node/api_server/src/execution_sandbox/mod.rs, core/node/api_server/src/execution_sandbox/storage.rs, core/node/api_server/src/execution_sandbox/testonly.rs, core/node/api_server/src/execution_sandbox/vm_metrics.rs, core/node/api_server/src/testonly.rs, core/node/api_server/src/tx_sender/tests/call.rs, core/node/api_server/src/tx_sender/tests/send_tx.rs, core/node/api_server/src/utils.rs, core/node/api_server/src/web3/backend_jsonrpsee/metadata.rs, core/node/api_server/src/web3/namespaces/eth.rs, core/node/api_server/src/web3/namespaces/zks.rs
- Refactors state override application in the API server.
- Adds metrics related to state overrides.
Currently, `eth_call` / `eth_estimateGas` will panic if a nonce override is supplied. This is because in this case, storage is read using blocking `ReadStorage` trait in the non-blocking context.
=> fix(api): Fix panic applying nonce override

core/lib/dal/src/tokens_dal.rs
Migrates `add_tokens` from COPY to INSERT to avoid globbing user data into the query. Additionally replaces `\x00` (aka NULL) character with whitespace as Postgres can't handle them in `TEXT` fields.
Robustness
None
=> fix: insert tokens without PG copy

prover/crates/bin/circuit_prover/src/main.rs, prover/crates/bin/circuit_prover/src/metrics.rs
Replace Histogram with Gauge for startup_time/run_time/shutdown_time metrics.
Histogram metric is excessive to report single number from binary and loses  precision.
=> fix(prover): Replace Histogram with Gauge for startup_time/run_time/shutdown_time metrics

core/Cargo.lock, core/lib/dal/.sqlx/query-cf8aaa95e3e8c376b6083c7015753e30af54675ce58273cbb29312e6e88cbdf5.json, core/lib/dal/src/eth_sender_dal.rs, core/node/consistency_checker/src/lib.rs, core/node/node_framework/src/implementations/layers/consistency_checker.rs
Fixes handling of old batches in consistency checker on SL change. Consistency checker will skip old batches if they were committed on a different SL.
Old batches could be sent to different SL, it's ok to skip them, otherwise node will be in crashloop until some amount of new batches are commited.
By design EN should panic and restart on SL change, with this change restart should happen only once per SL change.
No
=> fix(en): handling of old batches in consistency checker on SL change

core/node/node_sync/src/external_io.rs, core/node/state_keeper/src/io/mempool.rs, core/node/state_keeper/src/io/persistence.rs, core/node/state_keeper/src/io/tests/mod.rs, core/node/state_keeper/src/keeper.rs, core/node/state_keeper/src/seal_criteria/io_criteria.rs, core/node/state_keeper/src/seal_criteria/mod.rs, core/node/state_keeper/src/testonly/test_batch_executor.rs, core/node/state_keeper/src/tests/mod.rs, core/node/state_keeper/src/updates/mod.rs
Add protocol upgrade sealer which 
a) seals batch when there is a pending protocol upgrade
b) seals first batch after protocol upgrade with 1 tx
Makes protocol upgrades happen faster for chains with low TPS.
None
=> feat(state-keeper): protocol upgrade sealer

.github/workflows/check-flaky-tests.yml
To have a separate check for flakiness in `main` without interrupting the merge queue tests stability and PRs testing from the main `CI` workflow.
=> ci: add workflow to check core for flaky integration tests

core/bin/external_node/src/config/mod.rs, core/lib/basic_types/src/settlement.rs, core/lib/config/src/configs/contracts/chain.rs, core/lib/config/src/configs/contracts/ecosystem.rs, core/lib/config/src/configs/contracts/gateway.rs, core/lib/contracts/src/lib.rs, core/lib/dal/src/server_notifications.rs, core/lib/eth_client/src/contracts_loader.rs, core/lib/types/src/api/mod.rs, core/lib/types/src/lib.rs, core/lib/types/src/server_notification.rs, core/lib/web3_decl/src/namespaces/unstable.rs, core/node/api_server/src/web3/backend_jsonrpsee/namespaces/unstable.rs, core/node/api_server/src/web3/namespaces/unstable/mod.rs, core/node/api_server/src/web3/state.rs, core/node/api_server/src/web3/tests/mod.rs, core/node/api_server/src/web3/tests/ws.rs, core/node/consensus/src/testonly.rs, core/node/eth_sender/src/eth_tx_aggregator.rs, core/node/eth_sender/src/zksync_functions.rs, core/node/eth_watch/src/event_processors/decentralized_upgrades.rs, core/node/node_framework/src/implementations/layers/base_token/base_token_ratio_persister.rs, core/node/node_framework/src/implementations/layers/eth_watch.rs, core/node/node_framework/src/implementations/layers/web3_api/server/mod.rs, core/tests/revert-test/tests/utils.ts, core/tests/upgrade-test/tests/upgrade.test.ts
- ChainAdmin on SL is not used anymore for watching events. Only L1 is used.
- Added an endpoint for tracking the process of migrating on top of Gateway.
=> feat: Port core changes for gateway the new gateway scripts

core/lib/state/src/rocksdb/recovery.rs, core/node/metadata_calculator/src/recovery/mod.rs
- Fixes the `is_genesis_recovery_needed()` check. It now checks that the genesis is present in Postgres.
- Adds a couple more logs related to genesis recovery.
The `is_genesis_recovery_needed()` check previously checked whether Postgres *only* contains genesis (i.e., has no later batches). This is logically incorrect; if an EN is restored from a Postgres dump, or if the state keeper cache / tree is dropped for whatever reason and is re-synced, then there can be more batches in Postgres.
=> fix(en): Fix chunked genesis recovery

core/lib/contract_verifier/src/compilers/mod.rs, core/lib/contract_verifier/src/compilers/zksolc.rs, core/lib/contract_verifier/src/compilers/zkvyper.rs, core/lib/contract_verifier/src/lib.rs, core/lib/contract_verifier/src/tests/mod.rs, core/lib/types/src/contract_verification/api.rs, core/node/contract_verification_server/src/tests/utils.rs
- addresses issue with evm verification with immutable ref 
- Could not verify contracts with immutable refs as it resulted in bytecode mismatch error 
- No
=> fix: address issue with evm verification with immutable ref 

core/tests/recovery-test/package.json
Increase timeout for recovery tests.
We now run integration tests 10 times on merge into main, so recovery takes longer.
=> test: increase timeout for recovery tests

core/lib/state/src/rocksdb/mod.rs, core/lib/state/src/rocksdb/recovery.rs, core/lib/state/src/rocksdb/tests.rs, core/lib/state/src/test_utils.rs
Takes pruning info into account when initiating state keeper cache recovery.
Just like the Merkle tree previously, SK cache recovery won't work properly if state pruning has occurred (whether on top of genesis, or on top of a snapshot).
=> fix(en): Fix state keeper cache recovery with pruning enabled

.github/workflows/build-prover-template.yml, docker/gpu-checker/Dockerfile, prover/crates/bin/gpu_checker/README.md, prover/crates/bin/gpu_checker/gpu_checker.yaml, prover/crates/bin/prover_autoscaler/src/key.rs
Add support of H100 into provers and gpu-checker.
To allow usage of H100.
=> feat(prover): Add support of H100 into provers and gpu-checker

core/node/proof_data_handler/src/lib.rs
Fix of gateway fail to decode response body. Data handler submits different response to received proof than gateway receives, so gateway tries to push the same proof forward.
=> fix: prover gateway failing to decode response body

.github/workflows/publish-crates.yml, .github/workflows/release-please.yml
To prevent unexpected dependencies failures during publishing.
=> chore: publish crates with with --locked option

core/lib/dal/.sqlx/query-14a1e9bf60809d904c26a757d672d52328dd3aaedf057bf33aa5ff5cf3f36c75.json, core/lib/dal/.sqlx/query-3e2fd6f945c2365388694b338fc36d05708fb879aeb2bba31887b7a9cdf5d465.json, core/lib/dal/src/eth_sender_dal.rs, core/lib/eth_client/src/clients/mock.rs, core/node/eth_sender/src/abstract_l1_interface.rs, core/node/eth_sender/src/aggregator.rs, core/node/eth_sender/src/eth_tx_aggregator.rs, core/node/eth_sender/src/eth_tx_manager.rs, core/node/eth_sender/src/tester.rs, core/node/eth_sender/src/tests.rs, core/node/node_framework/src/implementations/layers/eth_sender/aggregator.rs, zkstack_cli/Cargo.lock
Set `from_addr` for non-blob txs
Makes data in DB less awkward, now it will be possible to get `from_addr` for any eth tx. Also helps with operator key rotation. I have tested locally that all you need to do to change operator (blob or non-blob) is to a) add new validator on L1; b) stop eth manager and wait for all txs to be confirmed; c) change wallet address and pk in config. No manual changes in DB.
Also, I've tested locally that code works with in-flight/unsent txs for which from_addr=null. I initialized server from `main`, created some bacthes so that there were some inflight and some unsent eth txs with from_addr=null. Then launched server from this branch and in-flight txs were confirmed; unsent txs were sent and confirmed.
=> feat(eth-sender): set `from_addr` for non-blob txs

core/lib/mempool/src/mempool_store.rs, core/lib/mempool/src/tests.rs, core/lib/mempool/src/types.rs
Mempool should keep nonces for stashed accounts.
MempoolStore keeps track of nonces. It gets account nonce from mempool actor when it inserts first tx for the particular account. Previously `MempoolStore` dropped info about nonce for stashed account so it was reloaded when mempool actor inserts next tx for the stashed account. Mempool actor gets nonces from storage which doesn't take pending block into account. So if there is a tx from stashed account in pending block then incorrect nonce will be loaded which will effectively "freeze" the account until the next node restart.
The easiest way to fix it is to keep nonce for stashed accounts. This way mempool will load nonces from storage only for "new" accounts i.e. there won't be any tx in pending block for such accounts.
No
=> fix(mempool): keep nonces in memory for stashed accounts

core/lib/multivm/src/versions/vm_latest/constants.rs
With new circuit types, the scheduler capacity has dropped a little.
=> chore: updated max circuits

core/node/state_keeper/src/seal_criteria/criteria/geometry_seal_criteria.rs
do not panic on big circuits limit, instead print warning
limit has decreased and we don't want nodes panic for those how forgot to update their config before the upgrade
=> feat: do not panic on big circuits limit

prover/crates/lib/prover_fri_types/src/lib.rs
Because of custom display implementation, key for the struct is incorrectly formatted.
=> fix: Aux output witness object store key

core/lib/prover_interface/src/legacy.rs
Fixes using `.cbor` file extension instead of `.bin` for bincode-encoded files
=> fix: bincode file extension

core/lib/types/src/tx/execute.rs, core/node/api_server/src/utils.rs
Fixes internal server errors occurring for Web3 RPC methods returning transaction receipts (e.g., `eth_getBlockReceipts`) if the receipt corresponds to a transaction calling `ContractDeployer` with unparseable calldata.
Returning an internal server error is incorrect in this case. Instead, `contractAddress` should be set to `null` for such transactions.
=> fix(api): Fix `contractAddress` in transaction receipts for unparseable deployment calldata

core/tests/ts-integration/src/retry-provider.ts, core/tests/ts-integration/tests/ether.test.ts
force-increase gas limit in retryableDepositCheck
fix flaky tests
=> test: force-increase gas limit in retryableDepositCheck

core/node/gateway_migrator/Cargo.toml, core/node/gateway_migrator/src/lib.rs
Remove handling the errors from gateway migrator. 
We shouldn't fail the whole system if some unexpected behaviour occured on l1.
=> fix(gateway-migrator): Do not fail gateway migrator during the problems with network

core/node/eth_sender/src/eth_tx_aggregator.rs
Allow execute and prove txs to be sent, when we migrate from gateway. 
All blocks should be executed during the migration from gateway to l1. So we have to allow them to be sent.
=> fix(gateway-migration): Allow prove, execute txs to be sent during the migration

core/lib/zksync_core_leftovers/src/lib.rs
Added `tee_proof_data_handler` to the Components mapping in `lib.rs`.
To start `tee_proof_data_handler` via `--component`.
=> feat(zksync-server): add support for tee_proof_data_handler component

core/lib/protobuf_config/src/general.rs, core/lib/protobuf_config/src/proto/config/general.proto
- Updated field name in proto file for consistency and clarity.
- Adjusted references in Rust code to reflect the renamed field. 
This change ensures better readability and aligns naming across components.
=> refactor: rename tee_data_handler to tee_proof_data_handler

zkstack_cli/crates/zkstack/src/commands/dev/commands/test/integration.rs
Increase timeout for integration tests
Tests fail often due to timeout and very flaky. Used value from `jest.config.json`
=> chore: Increase integration tests timeout

core/node/tee_proof_data_handler/src/errors.rs, core/node/tee_proof_data_handler/src/tee_request_processor.rs
- Added fallback logic to deserialize blob store data as `Bincode`.
- Adjusted error handling to accommodate multiple deserialization attempts.
This ensures compatibility with mixed serialization formats in the blob store.
=> fix(tee_proof_data_handler): handle fallback deserialization for blob store data

core/node/da_clients/src/avail/sdk.rs
Refactor the `check_finality` function in Avail GasRelay.
The previous approach to retrying GasRelay requests was invalid, which led to valid requests being dropped before they reached finality.
=> fix(da): gas relay check_finality

core/lib/web3_decl/src/namespaces/zks.rs, core/node/api_server/src/web3/backend_jsonrpsee/namespaces/zks.rs, core/node/api_server/src/web3/namespaces/zks.rs, core/tests/ts-integration/package.json, zkstack_cli/crates/common/src/zks_provider.rs
Removes `getL2ToL1LogProofUntilTarget` in favor of using just `getL2ToL1LogProof`. Additionally points to [kl/interop-ethers-support-real](https://github.com/zksync-sdk/zksync-ethers/tree/kl/interop-ethers-support-real) for integration tests.
Cleaner namespace
=> refactor: clean zks namespace

core/lib/types/src/api/mod.rs
Treat safe status as finalized for rpc
This is the only status we don't support and we have to do it for eth compatibility
=> fix(api): Add safe status

prover/crates/bin/prover_autoscaler/README.md, prover/crates/bin/prover_autoscaler/src/cluster_types.rs, prover/crates/bin/prover_autoscaler/src/config.rs, prover/crates/bin/prover_autoscaler/src/global/manager.rs, prover/crates/bin/prover_autoscaler/src/global/scaler.rs, prover/crates/bin/prover_autoscaler/src/k8s/watcher.rs
Autoscaler detect which pod out of resources and reschedule.
For one run mark a pool as full (`max_pool_size` = number of Running + Pending pods) if there is out of resources pod in it.
Add `priority` config override.
Remove unneeded need_to_move_duration config parameter.
Before all pending pod could be pushed to different cluster if even one of them is out of resources.
Add possibility to quickly switch to backup GPU if the main one is out.
ref ZKD-2682
=> feat(prover): Autoscaler detect which pod out of resources and reschedule

docs/src/guides/external-node/11_setup_for_other_chains.md
Disabling consensus should no longer be recommanded for ENs
=> fix(docs): update external node setup

core/bin/block_reverter/src/main.rs, core/bin/contract-verifier/src/main.rs, core/bin/genesis_generator/src/main.rs, core/bin/merkle_tree_consistency_checker/src/main.rs, core/bin/snapshots_creator/src/main.rs, core/bin/verified_sources_fetcher/src/main.rs, core/bin/zksync_server/src/main.rs, prover/crates/bin/circuit_prover/src/main.rs, prover/crates/bin/proof_fri_compressor/src/main.rs, prover/crates/bin/prover_fri_gateway/src/main.rs, prover/crates/bin/prover_job_monitor/src/main.rs, prover/crates/bin/witness_generator/src/main.rs
Adds `ZKSYNC_` prefix for env vars read by the main node and other binaries (other than the external node).
There may be a collision with non-prefixed vars and vars auto-defined by K8s (e.g., `CONTRACT_VERIFIER_PORT`).
If env-based config is used for the main node, it now needs to be prefixed with `ZKSYNC_`. (Note that we haven't *de facto* supported env-based configs for the main node for some time.)
=> fix: Prefix env vars for `zksync_server`

core/lib/config/src/configs/general.rs, core/lib/config/src/configs/tee_proof_data_handler.rs
Fixes the prefix for TEE proof data handler config.
The prefix was changed while the config integration PR was in progress, and the change was missed during merge.
=> fix: Fix prefix for `TeeProofDataHandlerConfig`

core/bin/zksync_server/src/node_builder.rs, core/lib/config/src/configs/gateway_migrator.rs, core/lib/config/src/configs/general.rs, core/lib/config/src/configs/mod.rs, core/node/gateway_migrator/src/lib.rs, core/node/gateway_migrator/src/node/gateway_migrator_layer.rs, etc/env/file_based/general.yaml
Introduce gateway migrator config 
For consuming less eth calls
=> fix(gateway_migrator): add gateway migrator config

core/lib/web3_decl/src/namespaces/zks.rs, core/node/api_server/src/web3/backend_jsonrpsee/namespaces/zks.rs, core/node/api_server/src/web3/namespaces/zks.rs
Removes `zks_getL2ToL1MsgProof` from our JSON-RPC API. Greenlit by devex, devrel and protocol.
* Has been deprecated for a long time
* Has a direct alternative in the form of `zks_getL2ToL1LogProof`
* No observable usage on any of the envs
* Unused in SDKs
`zks_getL2ToL1MsgProof` can be removed from JSON-RPC whitelist
=> feat: remove `zks_getL2ToL1MsgProof`

.github/workflows/ci-core-reusable.yml, core/lib/contract_verifier/src/tests/real.rs, core/tests/ts-integration/tests/api/contract-verification.test.ts
* update contract verifier era-vm-solc-version to 1.0.2
Contract verifier is unable to download 1.0.1 anymore due to paging issue with GH releases. Use the latest newly released 1.0.2 by default.
=> ci: update contract verifier era-vm-solc-version to 1.0.2

etc/nix/devShell.nix, etc/nix/devShellAll.nix, etc/nix/foundry-zksync.nix, flake.nix
- use foundry-zksync prebuilt binaries
- add `cargo-nextest` to devShellAll
- extend the ZK_LD_LIBRARY_PATH for live development with `cargo`
extend the development capabilities in a nix environment
=> chore(nix): update development environment

core/lib/snapshots_applier/src/lib.rs, core/lib/snapshots_applier/src/tests/mod.rs
Updates snapshot applier health during storage logs recovery.
The snapshot applier health is only updated before and after snapshot logs are recovered, but not during their recovery. This is misleading and can give off impression that recovery got stuck.
=> fix(en): Update snapshot applier health during storage logs recovery

zkstack_cli/crates/config/src/private_proxy_compose.rs
Fix target_rpc address so that it uses `docker.host.internal` instead of `localhost` when run on MacOS
=> fix: target_rpc address in private-rpc docker-compose

flake.nix
- Added missing runtime dependencies (e.g., libclang, openssl, lz4, bzip2, postgresql) to `flake.nix`.
better development shell with nix
=> chore(nix): update dependencies

etc/nix/foundry-zksync.nix, etc/nix/update-foundry-zksync.sh
- added `update-foundry-zksync.sh` to update the hashes
- update foundry-zksync to 0.0.15 for the nix development environment
- up2date nix environment
=> chore(nix): update foundry-zksync to 0.0.15

docker-compose.yml
Increasing ulimit for docker compose spawned containers, used in itegration tests
On new faster runners we recieve error `Too many open files (os error 24)`
=> fix(ci): Increase ulimits in compose for integrationg tests

core/lib/multivm/src/versions/vm_latest/old_vm/memory.rs
Only keep heaps containing decommitted code forever.
(A quick bugfix resulted in us keeping all heaps for the duration of a batch. This wastes memory.)
=> perf: deallocate all heaps that don't need to be kept

private-rpc/Dockerfile
Add migrations to private-rpc Dockerfile
This migrations are really small, they have no impact in the final image size. Adding them allows to do everything needed to run the private rpc in a single image.
- [ x ] No
None
- [ x ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ x ] Tests for the changes have been added / updated.
- [ x ] Documentation comments have been added / updated.
- [ x ] Code has been formatted via `zkstack dev fmt` and `zkstack dev lint`.
=> feat(private-rpc): add migrations to Dockerfile

zkstack_cli/crates/zkstack/src/commands/prover/args/run.rs
Use `latest` for prover component by default.
Label `latest2.0` was deprecated last year.
ref ZKD-2769
=> fix(zkstack): Use `latest` for prover component by default

core/lib/vm_executor/src/shared.rs, core/node/api_server/src/web3/backend_jsonrpsee/metadata.rs, core/node/api_server/src/web3/backend_jsonrpsee/mod.rs, core/node/api_server/src/web3/metrics.rs, core/node/api_server/src/web3/namespaces/eth.rs, core/node/api_server/src/web3/namespaces/unstable/mod.rs, core/node/api_server/src/web3/namespaces/zks.rs
Adds more observability for tx submission errors (which also covers calls and gas estimation).
These errors could be useful in debugging API server issues. RN, we only observe submission errors for tx submission. 
=> chore(api): Observe transaction submission errors

core/node/eth_sender/src/eth_fees_oracle.rs
Before we resent txs only if we are both for blob and base fees. In some cases it means that we will not resend for quite some time, so changed to resend if at least one of the fees is ready to be resent
=> fix(eth sender): fix blob sender fee calculation

core/node/eth_sender/src/eth_fees_oracle.rs, core/node/fee_model/src/l1_gas_price/gas_adjuster/mod.rs, core/node/fee_model/src/l1_gas_price/mod.rs
For gateway using median doesn't make sense since price doesn't change frequently (once per batch).
to prevent tx from being stuck for a long time we are using last value instead.
=> feat(eth-sender): use last value in gas adjuster for gateway txs

core/Cargo.lock, core/Cargo.toml, core/lib/config/src/configs/api.rs, core/lib/config/src/configs/consensus.rs, core/lib/config/src/configs/contracts/chain.rs, core/lib/config/src/configs/da_client/avail.rs, core/lib/config/src/configs/genesis.rs, core/lib/config/src/utils.rs, prover/Cargo.lock, prover/Cargo.toml, prover/crates/bin/prover_autoscaler/src/config.rs
- Fixes parsing null values with units, such as `slow_time_limit_ms: null`.
- Updates `smart-config` to a published version (0.2.0-pre).
- Adds a missing default for the `max_blocks_to_look_back` param.
We want existing Era configs to be parseable.
=> fix(config): Fix parsing null values with units + other config fixes

core/node/consensus/src/registry/tests.rs, core/node/consensus/src/vm.rs
VM calls from the consensus crate were erroring on reverts with custom Error types. This PR fixes that by handling them like general reverts.
None
=> fix(consensus): Handle custom reverts on VM calls

prover/Cargo.lock, prover/crates/bin/circuit_prover/Cargo.toml, prover/crates/bin/circuit_prover/src/main.rs, prover/crates/bin/proof_fri_compressor/Cargo.toml, prover/crates/bin/proof_fri_compressor/src/main.rs
tokio::signal::ctrl_c() doesn't handle SIGTERM. It's replaced with ctrlc crate functionality. 
SIGTERM is not handled in circuit-prover & compressor resulting in immediate killing of binary without graceful shutdown and further requeuing of stuck jobs.
=> feat: SIGTERM handling in circuit-prover & compressor

core/bin/zksync_server/src/node_builder.rs, core/lib/config/src/configs/api.rs, core/lib/types/src/fee_model.rs, core/node/api_server/src/tx_sender/mod.rs, core/node/api_server/src/web3/tests/vm.rs, core/node/fee_model/src/lib.rs, core/node/fee_model/src/node/l1_gas.rs
Apply scaling to the batch fee even if there is an open batch.
When the transaction gas price is estimated at the end of the batch, there is a risk of transaction price being too low if the next batch has a higher gas price
=> feat(fee_model): scale the batch fee unconditionally

prover/crates/lib/keystore/src/compressor.rs
Fixed issue with double initializing setup keys for Compressor.
=> fix(prover): Fixed loading setup for Compressor service 

core/bin/external_node/src/config/tests/consensus-secrets.yaml, core/bin/external_node/src/config/tests/mod.rs, core/bin/external_node/src/main.rs
Fix parsing consensus secrets on the EN if `EN_CONSENSUS_SECRETS_PATH` env var is set.
https://github.com/matter-labs/zksync-era/pull/4104 has incorrectly set the secrets prefix (`secrets.consensus` instead of `consensus`). 
=> fix(en): Fix parsing consensus secrets

core/lib/web3_decl/src/error.rs, core/node/eth_watch/src/client.rs
Handle get_logs timeout in eth watch
In order to split request when timeout is received
=> fix(eth-watcher): handle get_logs timeout in eth watch

.github/workflows/zk-environment-publish.yml, zkstack_cli/Cargo.lock
- Bumps Github Actions in zk-env CI workflow
- Pushes all zk-env images to all 3 registies we are using - ghcr, Dockerhub, GAR
=> chore: Fixes to zk-env images CI

core/lib/web3_decl/src/namespaces/unstable.rs, core/lib/web3_decl/src/namespaces/zks.rs, core/node/api_server/src/web3/backend_jsonrpsee/namespaces/unstable.rs, core/node/api_server/src/web3/backend_jsonrpsee/namespaces/zks.rs, core/node/api_server/src/web3/namespaces/unstable/mod.rs, core/node/api_server/src/web3/namespaces/zks.rs, core/tests/gateway-migration-test/package.json, core/tests/recovery-test/package.json, core/tests/revert-test/package.json, core/tests/ts-integration/package.json, core/tests/ts-integration/tests/contracts.test.ts, core/tests/ts-integration/tests/erc20.test.ts, core/tests/ts-integration/tests/prividium.test.ts, core/tests/upgrade-test/package.json, etc/utils/package.json, private-rpc/src/rpc/rpc-method-handlers.ts, yarn.lock
This PR:
* Stabilizes `unstable_gasPerPubdata` as `zks_gasPerPubdata`
* Makes it never return less than `1` gas per pubdata as such transactions are considered invalid
* Upgrades zksync-ethers to use a [WIP branch](https://github.com/zksync-sdk/zksync-ethers/pull/252) that stops calling `zks_estimateFee` in favour of `zks_gasPerPubdata` (if available)
`zks_estimateFee` is scheduled for deprecation and this is the last missing piece
This is technically a breaking change but realistically `unstable_gasPerPubdata` is unused by the public
=> feat(api): stabilize zks_gasPerPubdata

.github/workflows/ci-core-reusable.yml, core/Cargo.lock, core/bin/external_node/Cargo.toml, core/bin/external_node/src/config/mod.rs, core/bin/external_node/src/config/tests/mod.rs, core/bin/external_node/src/main.rs, core/bin/external_node/src/node_builder.rs, core/bin/external_node/src/tests/mod.rs, core/bin/external_node/src/tests/utils.rs, core/lib/config/src/configs/consensus.rs, core/node/consensus/src/en.rs, core/node/consensus/src/lib.rs, core/node/consensus/src/node/external_node.rs, core/node/consensus/src/storage/mod.rs, core/node/consensus/src/storage/store.rs, core/node/consensus/src/testonly.rs, core/node/consensus/src/tests/mod.rs, core/tests/gateway-migration-test/tests/migration.test.ts, core/tests/revert-test/tests/revert-and-restart-en.test.ts, core/tests/ts-integration/src/env.ts, core/tests/ts-integration/tests/fees.test.ts, core/tests/upgrade-test/tests/upgrade.test.ts, docs/src/guides/external-node/10_decentralization.md, zkstack_cli/crates/zkstack/src/commands/dev/commands/test/args/revert.rs, zkstack_cli/crates/zkstack/src/commands/dev/commands/test/revert.rs, zkstack_cli/crates/zkstack/src/commands/dev/messages.rs, zkstack_cli/crates/zkstack/src/commands/external_node/args/run.rs, zkstack_cli/crates/zkstack/src/commands/external_node/run.rs, zkstack_cli/crates/zkstack/src/external_node.rs, zkstack_cli/crates/zkstack/src/messages.rs
Removes JSON RPC syncing.
Remove deprecated feature.
ENs that still use JSON RPC syncing should follow https://github.com/matter-labs/zksync-era/blob/main/docs/src/guides/external-node/10_decentralization.md.
=> feat(en): remove JSON RPC syncing

private-rpc/src/routes/users-routes.ts
- Introduced a new query parameter `secret` to the user retrieval route.
- Implemented validation to ensure the provided secret matches the expected token, returning a 403 error if it does not.
- Enhance security
=> feat(private-rpc): Add secret query parameter validation for user retrieval

zkstack_cli/crates/zkstack/src/abi.rs, zkstack_cli/crates/zkstack/src/commands/chain/gateway/migrate_to_gateway_calldata.rs
Make GW migration calldata script compatible with pre-v29 contracts
It didn't work with pre-v29 contracts that blocked the GW migrations
=> fix(zkstack): make GW migration script compatible with pre-v29

private-rpc/src/routes/users-routes.ts
Fix a mismatch between secret sending between `private-rpc` and `block-explorer`.
Currently the `block-explorer` sends the secret in the header: https://github.com/matter-labs/block-explorer/blob/prividium-mode/packages/api/src/auth/auth.controller.ts#L227. The mismatch was ocurring due to `private-rpc` sending it as a query param.
=> fix: secret parsing whitelisting private rpc

core/lib/dal/.sqlx/query-b882586949146ef1e7867b133ad6cb00d88e73118347e1f33c041ef27bf62ebc.json, core/lib/dal/src/eth_sender_dal.rs
Execute light query for checking the existance of eth tx with necessary type. If it exists, we can execute statistics query. Which are more expensive
For majority of l2 blocks, the eth transcations doesn't exist. So it leads to extremely expensive queries.
=> fix(eth-sender): Check the existance of eth txs before getting the correct block for statistics

core/lib/dal/src/base_token_dal.rs, core/lib/types/src/fee_model.rs, core/node/base_token_adjuster/src/base_token_ratio_persister.rs, core/node/state_keeper/src/io/tests/mod.rs
Use default base token conversion params for preserving backward compatibility
=> fix(api): Return back fee params backward compatibility for non gateway chains

core/lib/dal/.sqlx/query-a1339010617c0c882029ccd0959c2bfd23e63b4dafe3f65c1f01ec3cc195cc6a.json, core/lib/dal/src/interop_roots_dal.rs, core/lib/vm_executor/src/storage.rs, core/node/eth_sender/src/eth_tx_aggregator.rs, core/node/node_sync/src/external_io.rs, core/node/node_sync/src/fetcher.rs, core/node/state_keeper/src/io/mempool.rs, core/node/state_keeper/src/io/mod.rs
We were not properly attaching interop information on the first block in the batch.
This meant, that if we were sealing only 1 block per batch, interop roots were never included (this happened during manual tests).
This fix is ignored during protocol upgrades, as this could cause the batch to fail. The reason for it is that during v29 protocol upgrade, interop roots cannot be set given that the `L2InteropRootStorage` contract is not yet deployed.
Additionally, this PR introduces a check to skip importing of interop roots if settling on the L1, which can cause batch execution to fail as we do not support L1 interop. This issue was not revealed until after enabling interop roots on first block in a batch.
=> fix(state-keeper): set interop roots on first block in batch

core/lib/config/src/configs/eth_sender.rs, core/node/eth_sender/src/eth_tx_aggregator.rs
=> feat(eth_sender): Allow to use validator timelock from the config

.github/workflows/ci-prover-e2e.yml
Remove legacy prover mode from e2e CI test
Legacy API mode was removed from code
=> feat: Remove legacy prover mode from CI

core/lib/config/src/configs/eth_proof_manager.rs, core/lib/object_store/src/raw.rs, core/node/eth_proof_manager/src/sender/submit_proof_request.rs, core/node/eth_proof_manager/src/tests/mod.rs
Add config variable for ETH proof manager component which defines public bucket url address
Because public URL for reads doesn't match the private one for writes
=> feat: add public bucket address config variable

.github/workflows/ci-core-lint-reusable.yml
To prevent issues with `crates.io` publishing on the later stages caused by missing fields in new `Cargo.toml` files.
Tested in a separate workflow with multiple crates with wrong configuration:
https://github.com/matter-labs/zksync-era/actions/runs/17213648618/job/48831624156
=> chore: add linter for new crates required crates.io fields

core/lib/dal/src/eth_proof_manager_dal.rs
Set `fallbacked` status when fallbacking a batch
Batch can be fallbacked twice
=> fix(eth-proof-manager): use correct status while fallbacking

.github/workflows/build-contract-verifier-template.yml, .github/workflows/build-core-template.yml, docker/zk-environment/22.04_amd64_cuda_11_8.Dockerfile, docker/zk-environment/22.04_amd64_cuda_12.Dockerfile, docker/zk-environment/Dockerfile
This reverts commit ec900ccca2e8c8540172a3330214e1a512aaa358.
Bumping of foundry has caused a different bytecode hashes to be producted, which results a failures in genesis (mismatch hashes) and issues with unittests (hashes not matching era-contract ones).
Rolling back for now, until we can find a better solution.
=> fix: Revert "fix: bump foundry-zksync (#4470)"

.github/workflows/ci.yml, .github/workflows/release-test-stage.yml
What ❔
This change updates the version of tj-actions/changed-files from v39 to v47 to improve the security of the actions
=> fix(ci): tj-actions/changed-files version update

core/node/state_keeper/src/node/state_keeper.rs
Disables statement timeouts for the connection pool used for state keeper cache recovery.
Cache recovery logic incorporates potentially long-running queries, so having the default timeout for it is bogus.
=> fix(en): Fix statement timeout errors during cache recovery

.github/workflows/ci-prover-e2e.yml
Add CUDA_ARCH for prover e2e tests.
This allows to run the tests on any of possible GPUs like L4,A100,H100.
ref ZKD-3043
=> ci: Add CUDA_ARCH for prover e2e tests
