- core/bin/zksync_core/src/state_keeper/keeper.rs
- infrastructure/zk/src/hyperchain_wizard.ts
- infrastructure/zk/src/init.ts
- infrastructure/zk/src/up.ts
- Adds missing execution when creating a new hyperchain
- fixes missing scripts when using an existing hyperchain configuration
- Greatly improves/speeds up the creation of hyperchains with the default configuration
- Add optional command in the end of the wizard to spin up the server (with default or custom components)
> feat(hyperchain): hyperchain script improvements

- .github/release-please/config.json
- .github/release-please/manifest.json
- .github/workflows/release-please.yml
Adds release-please workflow triggered by push into main branch.
Preparing to use the repo for releases.
> chore: Adds release-please workflow.

- .github/release-please/config.json
- .github/release-please/manifest.json
This PR updates the version + bootstrap sha of release please to match our latest releases.
From now on releases are going to be down from the public repo. Release please needs to know where to start.
> chore(release): Update Manifest and Config

- .github/workflows/build-external-node-docker.yml
- .github/workflows/build-gar-reusable.yml
- .github/workflows/build-local-node-docker.yml
- .github/workflows/build-prover-fri-gpu-gar.yml
- .github/workflows/coverage.yml
- .github/workflows/vm-perf-comparison.yml
- .github/workflows/vm-perf-to-prometheus.yml
- .github/workflows/zk-environment-cuda-12-0.publish.yml
- .github/workflows/zk-environment.publish.yml
This will move to more reliable github actions auto-scalling model which officially supports by Github Team.
> ci: Migration from ci-runner to matterlabs-ci-runner

- .github/workflows/zk-environment.publish.yml
> ci: fix zk environment workflow condition

- core/lib/mini_merkle_tree/src/lib.rs
- prover/Cargo.lock
* Fixing compilation error in Cargo
* and clippy warning
* To make CI pass
> chore(ci): Fixing CI

- .github/workflows/build-docker-from-tag.yml
- .github/workflows/release-please.yml
Adds call of build-docker-from-tag.yml from release-please.
Allows manually call of build-docker-from-tag.yml.
To create releases due to issue in github which doesn't allow automatic workflow triggers from workflow.
> ci: Adds call of build-docker-from-tag.yml from release-please.

- docs/setup-dev.md
Removes a leftover code from private repo times.
> chore: remove ssh repos information from setup-dev.md

- .github/workflows/build-prover-template.yml
- .github/workflows/ci.yml
- docker/prover/Dockerfile
Subj
CI should be runnable on PRs triggered from externally contributed code
> chore: Make Prover Docker build work from forks

- .github/release-please/config.json
> chore(ci): update bootstrap

- .github/workflows/ci-docs-reusable.yml
- docs/advanced/01_initialization.md
Re-adds accidentally deleted formatting check for docs CI
> ci: Re-add missing fmt check for docs CI

- .github/workflows/ci-core-lint-reusable.yml
- .github/workflows/ci-core-reusable.yml
- .github/workflows/ci.yml
Refactoring triggers for release-please branches
> ci: fix release-please ci jobs

- .github/workflows/label-extenal-contributions.yml
> ci: Fixing Workflow to label external contributions, take 2

- docs/advanced/prover_keys.md
* article describing different types of prover keys (setup keys, verification keys etc).
* to increase team knowledge about what they do.
> feat(docs): Adding documentation about prover keys

- core/lib/multivm/src/versions/vm_latest/types/l1_batch.rs
- core/lib/multivm/src/versions/vm_virtual_blocks/types/l1_batch_env.rs
> refactor(vm): removes redundant hashmaps introduced in #251

- core/lib/dal/src/transactions_dal.rs
After transferring to vise metrics, `mempool_` transaction stage labels became incorrect (e.g., `mempool_Added` instead of `mempool_added`). This PR changes them back.
These labels are used on some internal Grafana dashboards.
> fix: Fix `TxStage` string representation

- docs/advanced/contracts.md
- fix broken links
- The link is no longer valid and cannot be opened.
- [ ✅ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ✅ ] Tests for the changes have been added / updated.
- [ ✅ ] Documentation comments have been added / updated.
- [ ✅ ] Code has been formatted via `zk fmt` and `zk lint`.
> fix: fix broken links

- README.md
- update Security link in README.MD
- when you click on Security on README. it takes you to invalid link
> chore: Update Security link in README.MD

- docs/advanced/bytecode_compression.md
- fix documentation link
- The link cannot be accessed.
> fix: fix documentation link

- docs/advanced/zk_intuition.md
> chore: Update docs

- docs/advanced/how_l2_messaging_works.md
- update link
- Unable to open, 404
> docs: update link

- docs/external-node/01_intro.md
- Update contact_us link in 01_intro.md
> chore: Update contact_us link in 01_intro.md

- .github/workflows/zk-environment.publish.yml
> ci: Fix zk-env multi-arch Docker images publishing

- .github/workflows/zk-environment.publish.yml
- docker/zk-environment/Dockerfile
- Do not cancel workflows running in main
- Make manual trigger actually work
> ci: zk-env publish workflow tweaks

- .github/workflows/zk-environment.publish.yml
- docker-compose-runner-nightly.yml
> ci: zk-env publish workflow fix, zk-env rust naming fix

- .github/workflows/zk-environment.publish.yml
- docker/zk-environment/Dockerfile
> ci: Fix zk-env Dockerfile stages and tags naming

- prover/prover_fri/src/gpu_prover_job_processor.rs
- prover/prover_fri/src/prover_job_processor.rs
- prover/prover_fri/src/utils.rs
One one setup key exist for all node agg
- [ *] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [* ] Tests for the changes have been added / updated.
- [* ] Documentation comments have been added / updated.
> fix(prover-fri): Update setup loading for node agg circuit

- docs/advanced/how_l2_messaging_works.md
- Update cannot access the link
- Update cannot access the link
> chore: Update cannot access the link

- core/lib/zksync_core/src/metadata_calculator/updater.rs
This PR fixes a small typo in the comment.
> chore: fix a typo in the comment

- docs/external-node/05_troubleshooting.md
- Update the contact_us link to the latest link.
- Update the contact_us link to the latest link.
> feat(docs): Update the contact_us link to the latest link.

- .github/workflows/release-test-stage.yml
Set correct name for release stage runners## Checklist
> ci: Set correct name for release stage runners

- docs/repositories.md
- Removed invalid links
- The current link is inaccessible.
> chore: Removed invalid links

- README.md
- docs/external-node/05_troubleshooting.md
- Add Mirror hyperlink
- Increased visibility and community engagement for zkSync Mirror articles.
> fix: add Mirror hyperlink

- CONTRIBUTING.md
Old: ./github/SECURITY.md
New: ./SECURITY.md
> chore: Update CONTRIBUTING.md - Fix broken link to SECURITY.md

- docs/advanced/gas_and_fees.md
- Fix the broken links in the document.
- Can't open
> chore: fix the broken links in the document.

- docker-compose-gpu-runner.yml
> ci: Fix: add container_name to docker-compose to properly run w\o ci_run

- core/lib/multivm/src/versions/vm_1_3_2/oracles/tracer/utils.rs
- core/lib/multivm/src/versions/vm_latest/bootloader_state/state.rs
- core/lib/multivm/src/versions/vm_latest/tracers/utils.rs
- core/lib/multivm/src/versions/vm_m5/oracles/tracer.rs
- core/lib/multivm/src/versions/vm_m6/oracles/tracer/utils.rs
- core/lib/multivm/src/versions/vm_virtual_blocks/bootloader_state/state.rs
- core/lib/multivm/src/versions/vm_virtual_blocks/tracers/utils.rs
Better VM panics
For convenience
> chore(vm): Better VM panics

- core/lib/state/README.md
-  fix file path
- The file path is incorrect, now it is being changed to the correct path.
> chore: fix file path

- .github/workflows/build-docker-from-tag.yml
- .github/workflows/release-test-stage.yml
- Cargo.lock
> ci: Update setup-keys commit

- .github/release-please/config.json
> chore(release): remove release as

- yarn.lock
> chore: Update boojum contracts

- Cargo.lock
- core/lib/contracts/src/lib.rs
- core/lib/dal/migrations/20230807204005_add_fields_for_system_logs_and_compressed_state_diffs.down.sql
- core/lib/dal/migrations/20230807204005_add_fields_for_system_logs_and_compressed_state_diffs.up.sql
- core/lib/dal/sqlx-data.json
- core/lib/dal/src/blocks_dal.rs
- core/lib/state/Cargo.toml
- core/lib/state/src/rocksdb/mod.rs
- core/lib/types/src/commitment.rs
- core/lib/types/src/fee.rs
- core/lib/types/src/l2_to_l1_log.rs
- core/lib/types/src/tx/tx_execution_info.rs
- core/lib/zksync_core/Cargo.toml
- core/lib/zksync_core/src/api_server/tx_sender/mod.rs
- core/lib/zksync_core/src/api_server/web3/namespaces/zks.rs
- core/lib/zksync_core/src/block_reverter/mod.rs
- core/lib/zksync_core/src/eth_sender/aggregator.rs
- core/lib/zksync_core/src/eth_sender/eth_tx_aggregator.rs
- core/lib/zksync_core/src/eth_sender/zksync_functions.rs
- core/lib/zksync_core/src/eth_watch/event_processors/upgrades.rs
- core/lib/zksync_core/src/eth_watch/tests.rs
- core/lib/zksync_core/src/gas_tracker/mod.rs
- core/lib/zksync_core/src/state_keeper/keeper.rs
- core/lib/zksync_core/src/state_keeper/seal_criteria/criteria/pubdata_bytes.rs
- core/lib/zksync_core/src/state_keeper/seal_criteria/mod.rs
- docker/cross-external-nodes-checker/Dockerfile
Fix comments opened by me in #112
> fix: some fixes for boojum

- core/lib/multivm/src/versions/vm_latest/constants.rs
- core/lib/multivm/src/versions/vm_latest/old_vm/event_sink.rs
Fixes comments by @perekopskiy
> Fix comments in boojum-integration

- .github/workflows/build-docker-from-tag.yml
- .github/workflows/release-test-stage.yml
Fixes broken bash output in CIs.
> ci: Fixes bash in CIs

- docs/advanced/how_l2_messaging_works.md
- Fix errors in documentation
- Inaccessible
> chore(docs): fix errors in documentation

- core/tests/ts-integration/README.md
> chore: fix docs

- .github/workflows/ci.yml
Subj
We don’t want to bring the planet’s heat death closer
> ci: Exclude markdown from all non-doc related CI jobs

- core/lib/multivm/src/versions/vm_refunds_enhancement/vm.rs
Return correct `storage_refunds` in `vm_refunds_enhancement`
Return correct `storage_refunds` in `vm_refunds_enhancement`
> fix(vm): storage_refunds for `vm_refunds_enhancement`

- docker/zk-environment/20.04_amd64_cuda_11_8.Dockerfile
- docker/zk-environment/20.04_amd64_cuda_12_0.Dockerfile
- docker/zk-environment/Dockerfile
> ci: add cuda build deps to docker images

- .github/workflows/ci-core-reusable.yml
Disables a flaky test suite for EN.
Test suite is flaky.
> chore(CI): Disable bridge tests for EN

- prover/proof_fri_compressor/README.md
Changes README for module
Current title is wrong
> chore(Fri-compressor): Update README.md for FRI compressor

- core/lib/types/src/protocol_version.rs
vks should be updated if any vk is update
contract were changed, changing server as well
> fix: change vks upgrade logic

- core/lib/zksync_core/src/proof_data_handler/request_processor.rs
> fix(proof-data-handler): Check commitments only for post-boojum (again)

- core/lib/zksync_core/src/lib.rs
> fix(core): add tree url to jsonrpsee server on main node

- Cargo.lock
> fix(deps): Update zk evm abstraction

- .github/workflows/release-test-stage.yml
- core/lib/dal/sqlx-data.json
- core/lib/dal/src/fri_prover_dal.rs
> chore(ci): rebuild provers if we have changes in library

- .github/workflows/build-core-template.yml
- docker/circuit-synthesizer/Dockerfile
- docker/contract-verifier/Dockerfile
- docker/cross-external-nodes-checker/Dockerfile
- docker/external-node/Dockerfile
- docker/proof-fri-compressor/Dockerfile
- docker/prover-fri-gateway/Dockerfile
- docker/prover-fri/Dockerfile
- docker/prover-gpu-fri/Dockerfile
- docker/prover/Dockerfile
- docker/server-v2/Dockerfile
- docker/witness-generator/Dockerfile
- docker/witness-vector-generator/Dockerfile
- docker/zk-environment/20.04_amd64_cuda_11_8.Dockerfile
- docker/zk-environment/20.04_amd64_cuda_12_0.Dockerfile
- docker/zk-environment/Dockerfile
- prover/proof_fri_compressor/README.md
- prover/prover_fri/README.md
- prover/vk_setup_data_generator_server_fri/README.md
- prover/witness_vector_generator/README.md
> fix(ci): Use the same nightly rust

- .github/workflows/ci-core-reusable.yml
- core/tests/ts-integration/hardhat.config.ts
- core/tests/ts-integration/tests/api/contract-verification.test.ts
- docker/contract-verifier/Dockerfile
Adds zkvyper 1.3.13 to contract verifier
People need it!
> feat(contract-verifier): Add zkvyper 1.3.13

- .github/workflows/release-please.yml
Adds manual trigger for release-please.
> ci: Adds manual trigger for release-please

- core/lib/multivm/src/lib.rs
- core/lib/multivm/src/versions/vm_refunds_enhancement/mod.rs
Add more pubs for previous vm
For updating era testnode we need to expose some additional data
> fix(vm): Expose additional types and traits

- .github/workflows/check-spelling.yml
Runs spellcheck in merge queue.
> ci: Runs spellcheck in merge queue.

- infrastructure/local-setup-preparation/README.md
- infrastructure/local-setup-preparation/src/index.ts
Improve documentation by including the command to create rich L2 wallets.
Save other people time figuring out the exact invocation.
- [] Tests for the changes have been added / updated.
> docs: Include command to create rich L2 wallets.

- Cargo.lock
- core/bin/snapshots_creator/src/tests.rs
- core/lib/dal/sqlx-data.json
- core/lib/object_store/Cargo.toml
- core/lib/object_store/src/objects.rs
- core/lib/types/Cargo.toml
- core/lib/types/build.rs
- core/lib/types/src/lib.rs
- core/lib/types/src/proto/mod.proto
- core/lib/types/src/proto/mod.rs
- core/lib/types/src/snapshots.rs
- core/tests/ts-integration/tests/api/snapshots-creator.test.ts
- infrastructure/zk/package.json
- yarn.lock
Change of serialization format from json to protobuf for snapshots creator. 
**I still need to update the integration tests.**
> feat: proto serialization/deserialization of snapshots creator objects

- .github/workflows/ci-core-reusable.yml
- core/tests/revert-test/tests/revert-and-restart.test.ts
Restores revert test
Restores revert test
> chore(tests): restore revert test

- docs/guides/advanced/zk_intuition.md
Removed unwanted letter.
Removed a letter in the sentence.
Because sentence was incorrect.
> docs: corrected spelling in zk_intuition.md file

- core/tests/loadnext/README.md
> chore: fix doc

- .github/workflows/build-docker-from-tag.yml
- .github/workflows/build-prover-template.yml
- .github/workflows/release-test-stage.yml
- core/lib/dal/src/contract_verification_dal.rs
- infrastructure/zk/src/docker.ts
Add CUDA_ARCH params to build images
For add all kind of CUDA arches to docker image
> ci: add CUDA_ARCH arg to build prover template

- .github/workflows/build-docker-from-tag.yml
- .github/workflows/build-prover-template.yml
- .github/workflows/release-test-stage.yml
- infrastructure/zk/src/docker.ts
Reverts matter-labs/zksync-era#730
> ci: revert adding CUDA_ARCH arg to build prover template

- .github/workflows/build-docker-from-tag.yml
- .github/workflows/build-prover-template.yml
- .github/workflows/release-test-stage.yml
- core/lib/dal/src/contract_verification_dal.rs
- infrastructure/zk/src/docker.ts
> ci: add cuda arch param for prover-fri-gpu

- docs/guides/repositories.md
* Updated list of repositories in repositories.md
* Since last update, we moved everything to opensource and introduced boojum (with its own set of repositories).
> chore(docs): Update list of repositories

- docs/guides/advanced/how_l2_messaging_works.md
> chore: Update how_l2_messaging_works.md

- docs/guides/advanced/compression.md
> chore: fix link

- docs/specs/blocks_batches.md
- Addresses typo in link
- link was incorrect
> chore: fix dev discussions link

- docs/guides/advanced/how_call_works.md
> fix: fix path

- infrastructure/zk/src/status.ts
corrected spelling in `status.ts` file
Spelling was incorrect
> chore(docs): corrected spelling in `status.ts` file

- docs/guides/advanced/01_initialization.md
Remove the comma after "doc": "The goal of this doc is to show you some more details on how zkSync works internally."
> docs: Update 01_initialization.md

- docs/guides/advanced/contracts.md
> chore: update contracts.md

- docs/guides/advanced/03_withdrawals.md
> fix: fix error link

- docs/guides/advanced/deeper_overview.md
- docs/guides/advanced/how_l2_messaging_works.md
> chore(docs): fix typo

- .github/workflows/build-docker-from-tag.yml
- .github/workflows/ci.yml
- .github/workflows/release-test-stage.yml
Fix CI workflows for build core components
Broken CI for core components
> ci: fix job dependecies

- .github/workflows/build-contracts.yml
- .github/workflows/build-local-node-docker.yml
- .github/workflows/ci-core-reusable.yml
- core/tests/ts-integration/hardhat.config.ts
- core/tests/ts-integration/scripts/compile-yul.ts
- core/tests/ts-integration/tests/api/contract-verification.test.ts
- docker/contract-verifier/Dockerfile
- added zksolc v1.3.19 for contract verifier
- zksolc v1.3.19 is now latest
> feat(contract-verifier): add zksolc v1.3.19

- core/lib/env_config/src/database.rs
Fixes parsing statement timeout from the environment for the main node.
Without a statement timeout, we may have long-running DB queries for API servers.
> fix(db): Fix parsing statement timeout from env

- core/lib/config/src/configs/chain.rs
- core/lib/config/src/configs/mod.rs
- core/lib/config/src/lib.rs
- core/lib/env_config/src/chain.rs
It wasn't used anywhere.
Dead code bad.
> refactor(config): Remove ChainConfig structure

- .github/workflows/zk-environment-publish.yml
- docker/zk-environment/20.04_amd64_cuda_11_8.Dockerfile
- docker/zk-environment/20.04_amd64_cuda_12_0.Dockerfile
- docker/zk-environment/Dockerfile
> ci: Fixed zk-environment workflow typos and npm issues.

- core/lib/multivm/src/versions/vm_boojum_integration/old_vm/oracles/precompile.rs
- core/lib/multivm/src/versions/vm_boojum_integration/tests/circuits.rs
- core/lib/multivm/src/versions/vm_boojum_integration/tracers/circuits_tracer.rs
- core/lib/multivm/src/versions/vm_boojum_integration/tracers/default_tracers.rs
- core/lib/multivm/src/versions/vm_latest/old_vm/oracles/precompile.rs
- core/lib/multivm/src/versions/vm_latest/tests/circuits.rs
- core/lib/multivm/src/versions/vm_latest/tracers/circuits_tracer.rs
- core/lib/multivm/src/versions/vm_latest/tracers/default_tracers.rs
`finish_cycle` method of circuit tracer wasn't called and there were bugs in it.
Fix tracer
> fix(vm): fix circuit tracer

- .github/workflows/build-core-template.yml
Reverts matter-labs/zksync-era#828
> ci: Revert fix merge manifest job

- docs/guides/advanced/how_l2_messaging_works.md
> chore: fix unreachable link

- docs/guides/development.md
- Adds relevant docs related to spellchecker
- Provides devs with info related to the tool and how it is used
> chore: adds development guide for zk spellcheck

- .github/workflows/build-core-template.yml
- .github/workflows/ci.yml
Fix job for merge released docker manifest 
For multi-platform builds
> ci: fix merge manifest

- core/lib/multivm/src/versions/README.md
* Adding a list with the current VM versions
* To make it easy to see what is the chronological order (and what was changed).
> chore(docs): Adding a README with a list of VM versions

- Cargo.lock
> chore(deps): bumps h2 to avoid vulnerability alert

- Cargo.lock
- prover/Cargo.lock
Update era-zkevm_test_harness
It has a fix for witness generation
> fix(witness-generator): Update era-zkevm_test_harness

- prover/Cargo.lock
> fix(prover): Update shivini

- Cargo.lock
- prover/Cargo.lock
Update zkevm_test_harness
Fix witness_generation
> fix(witness-generator): Update zkevm_test_harness

- core/lib/types/src/protocol_version.rs
- core/lib/zksync_core/src/eth_sender/eth_tx_aggregator.rs
- core/lib/zksync_core/src/eth_sender/tests.rs
- core/lib/zksync_core/src/eth_sender/zksync_functions.rs
- core/lib/zksync_core/src/lib.rs
Integrates new ValidatorTimelock functions such as `commitBatchesSharedBridge`.
Removes an obsolete flag to support pre-boojum contracts.
> feat(shared bridge): integrate updated validator timelock

- core/tests/ts-integration/src/env.ts
- core/tests/ts-integration/tests/api/web3.test.ts
- etc/env/configs/dev.toml
- yarn.lock
> [WIP] Fix Integration tests for the shared bridge

- core/lib/zksync_core/src/state_keeper/io/seal_logic.rs
- core/lib/zksync_core/src/state_keeper/metrics.rs
- yarn.lock
We want to track the avergae/median time users' transactions spend in the mempool
To be able to reason about UX.
Note: I also track the time it takes to produce this tracking just to make sure it's negligible.
> feat(state-keeper): track the time that individual transactions spend in mempool

- docker/build-base/Dockerfile
> chore(ci): adds a pre-packaged docker build image

- core/lib/zksync_core/src/eth_sender/eth_tx_manager.rs
- core/lib/zksync_core/src/eth_sender/metrics.rs
- core/lib/zksync_core/src/eth_sender/tests.rs
https://linear.app/matterlabs/issue/PLA-751/metrics-for-l1-block-heights
> feat(eth-sender):  metrics for finalized and safe L1 block numbers

- core/lib/contracts/src/lib.rs
- Removes dead code
- Reduces the visibility for some (unnecessary) public functions
- Dead code bad
- Excessive public APIs bad
> refactor: Remove dead code from zksync_contracts

- core/lib/dal/src/blocks_web3_dal.rs
Fix ordering
for tests to pass
> fix: get_block_receipts test

- docker/build-base/Dockerfile
- docker/contract-verifier/Dockerfile
- docker/external-node/Dockerfile
- docker/proof-fri-compressor/Dockerfile
- docker/prover-fri-gateway/Dockerfile
- docker/prover-fri/Dockerfile
- docker/server-v2/Dockerfile
- docker/snapshots-creator/Dockerfile
- docker/witness-generator/Dockerfile
- docker/witness-vector-generator/Dockerfile
> chore(docker): use zksync-build-base as a builder image

- Cargo.lock
- core/bin/external_node/src/config/mod.rs
- core/bin/external_node/src/main.rs
- core/lib/config/src/configs/database.rs
- core/lib/config/src/testonly.rs
- core/lib/dal/src/basic_witness_input_producer_dal.rs
- core/lib/dal/src/blocks_dal.rs
- core/lib/dal/src/blocks_web3_dal.rs
- core/lib/dal/src/connection/mod.rs
- core/lib/dal/src/connection/processor.rs
- core/lib/dal/src/events_web3_dal.rs
- core/lib/dal/src/fri_prover_dal.rs
- core/lib/dal/src/instrument.rs
- core/lib/dal/src/snapshots_creator_dal.rs
- core/lib/dal/src/snapshots_dal.rs
- core/lib/dal/src/storage_logs_dal.rs
- core/lib/dal/src/storage_web3_dal.rs
- core/lib/dal/src/sync_dal.rs
- core/lib/dal/src/transactions_dal.rs
- core/lib/dal/src/transactions_web3_dal.rs
- core/lib/env_config/src/database.rs
- core/lib/protobuf_config/src/database.rs
- core/lib/protobuf_config/src/proto/database.proto
- core/lib/zksync_core/src/lib.rs
- core/lib/zksync_core/src/state_keeper/batch_executor/tests/mod.rs
- core/lib/zksync_core/src/state_keeper/batch_executor/tests/tester.rs
- core/lib/zksync_core/src/state_keeper/io/tests/mod.rs
- core/lib/zksync_core/src/state_keeper/mempool_actor.rs
- etc/env/ext-node.toml
- Makes instrumentation-related DB timings configurable.
- Outputs DB connection tags for slow / errored queries.
Improves DevEx.
> chore(db): Instrument db connection lifecycle (follow-ups)

- docs/guides/advanced/fee_model.md
* Documentation about our new fee model
* With 1.4.1 we changed the fee model, and added more flexibility.
> chore(docs): Update documentation about our new fee model

- core/bin/contract-verifier/src/verifier.rs
Fixes https://github.com/matter-labs/zksync-era/issues/1072
Bug fix
> fix(contract-verifier): Use optimizer mode in solidity-single-file verification

- core/bin/external_node/src/main.rs
EN runs tree in light mode.
Full tree mode is no longer required for EN as commitment generation is moved to a new component.
> feat(en): switch to tree light mode

- docker-compose-zkstack-common.yml
- infrastructure/zk/src/hyperchain_wizard.ts
> fix(zk_stack): fix docker compose and prover setup 

- core/tests/ts-integration/src/context-owner.ts
- core/tests/ts-integration/src/helpers.ts
Make tests send transactions subsequently, use Promise.all() only on waiting receipt.
Add more logging
Increase gas price by 30% to prevent test timeout
Integrationg tests for L1 are not working properly.
> feat: Integration tests enhancement for L1

- prover/prover_fri/README.md
- yarn.lock
- Fixes/clarifies GPU requirements for GPU provers, after the [latest changes to VRAM requirements](https://github.com/matter-labs/zksync-era/pull/1189)
- Also fixes some other minor issues in the same docs
There are no L4/T4 GPU instances with 6GB RAM, people might be confused with GPU requirements
> chore(docs): Clarify GPU reqs for Provers, other minor doc tweaks

- infrastructure/zk/src/hyperchain_wizard.ts
> fix(zk_stack): set correct database prover url

- .gitmodules
Updates the commit for `era-contracts` submodule.
Validium changes are in the branch
> fix(Validium): Update `contracts/` submodule commit

- core/tests/revert-test/tests/revert-and-restart.test.ts
Increases max wait time for commitBatches in revert test
> chore(test): Increase max wait time for commitBatches in revert test

- core/lib/zksync_core/src/native_token_fetcher/mod.rs
Replace `unwraps()` with better error handling.
Upon failure, current request failures will bring down the whole system.
> feat(Gas Oracle): Improve Fetcher Error Handling

- docs/guides/launch.md
- infrastructure/zk/src/down.ts
- infrastructure/zk/src/hyperchain_wizard.ts
- infrastructure/zk/src/init.ts
- infrastructure/zk/src/up.ts
- prover/prover_fri/src/gpu_prover_job_processor.rs
Add a new parameter --run-observability to zk and zk stack commands that allows to run dockprom stack alongside other containers. The command also provisions grafana with Era dashboards.
> feat: add run-observability to zk

- core/lib/zksync_core/src/l1_gas_price/gas_adjuster/mod.rs
Do not unwrap in gas-adjuster
Avoid panics
> fix(gas-adjuster): Do not unwrap in gas-adjuster

- core/node/node_framework/examples/main_node.rs
- core/node/node_framework/src/implementations/layers/commitment_generator.rs
- core/node/node_framework/src/implementations/layers/mod.rs
> feat(node-framework): Add commitment generator layer

- core/tests/revert-test/tests/revert-and-restart.test.ts
- core/tests/ts-integration/package.json
- core/tests/ts-integration/tests/custom-erc20-bridge.test.ts
- core/tests/ts-integration/tests/fees.test.ts
- core/tests/upgrade-test/tests/upgrade.test.ts
Lower timeouts, after our optimization in CI time
> chore(tests): lower timeouts

- core/bin/verified_sources_fetcher/src/main.rs
Use correct `contact_name` for `SolSingleFile `
Fix panic in verified sources fetcher.
> fix(verified sources fetcher): Use correct `contact_name` for `SolSingleFile`

- infrastructure/zk/src/down.ts
> fix(zk): check if file actually exists

- core/lib/zksync_core/src/api_server/contract_verification/api_impl.rs
> feat(contract-verifier): Allow sc code reverification

- core/node/node_framework/examples/main_node.rs
- core/node/node_framework/examples/showcase.rs
- core/node/node_framework/src/resource/mod.rs
- core/node/node_framework/src/service/error.rs
- core/node/node_framework/src/service/mod.rs
- core/node/node_framework/src/service/tests.rs
- core/node/node_framework/src/wiring_layer.rs
- Split ZkStackService into the main struct and builder for ease of use.
- Introduce strong typing for ZkStackErrors.
- Add a showcase example.
Quality of life improvements.
> feat(node_framework): Ergonomic improvements

- .gitmodules
- infrastructure/zk/src/init.ts
Change the branch of the contracts submodule to use `main` in Rollup mode and `feat_validium_mode` in Validium mode.
> fix(validium): Modify checkout commit  contracts

- core/node/node_framework/examples/main_node.rs
Adds missing layer that prevented main node example from running
Main node example works now.
> fix(node_framework): Fix main node example

- prover/Cargo.toml
- prover/proof_fri_compressor/Cargo.toml
- prover/prover_dal/Cargo.toml
- prover/prover_fri/Cargo.toml
- prover/prover_fri_gateway/Cargo.toml
- prover/prover_fri_types/Cargo.toml
- prover/prover_fri_utils/Cargo.toml
- prover/tools/Cargo.toml
- prover/vk_setup_data_generator_server_fri/Cargo.toml
- prover/witness_generator/Cargo.toml
- prover/witness_vector_generator/Cargo.toml
Prover follow-up to https://github.com/matter-labs/zksync-era/pull/1485
Same reasons
> refactor(prover): Switch prover workspace to workspace deps

- core/tests/ts-integration/tests/contracts.test.ts
Fix `contracts.test.ts`
To verify, `cd` into `ts-integration` and run:
```bash
yarn test contracts.test.ts
```
> fix(kl-factory): fix contracts tests

- Cargo.lock
- core/bin/external_node/src/main.rs
- core/lib/zksync_core/src/consensus/era.rs
- core/lib/zksync_core/src/consensus/fetcher.rs
- core/lib/zksync_core/src/consensus/mod.rs
- core/lib/zksync_core/src/consensus/testonly.rs
- core/lib/zksync_core/src/lib.rs
- core/lib/zksync_core/src/sync_layer/mod.rs
- core/node/node_framework/Cargo.toml
- core/node/node_framework/examples/main_node.rs
- core/node/node_framework/src/implementations/layers/consensus.rs
- core/node/node_framework/src/implementations/layers/mod.rs
- core/node/node_framework/src/implementations/resources/action_queue.rs
- core/node/node_framework/src/implementations/resources/main_node_client.rs
- core/node/node_framework/src/implementations/resources/mod.rs
- Moves consensus-related logic to the consensus module (so that all the logic in its own dedicated task).
- Creates a layer for the consensus task.
mhm
> feat(node-framework): Add consensus support

- etc/env/base/house_keeper.toml
> fix(config):  add correct name to the toml

- docs/guides/advanced/02_deposits.md
- docs/guides/advanced/how_transaction_works.md
Fix links since eth watch has been moved
> chore: Fix links

- core/lib/contracts/src/lib.rs
- core/tests/ts-integration/src/context-owner.ts
Update branch to latest commit of `contracts` submodule.
This PR also fixes some issues regarding `zk test i server`:
- ETH deposit failing due to not being waited properly.
- Base token not being distributed across accounts.
Fixes `zk init --base-token-name BAT`
> fix(kl-factory): update contracts submodule

- core/bin/external_node/src/main.rs
Do not log error when whitelisted_tokens_for_aa is not supported
Old main node doesn't have this method and EN shouldn't spam errors in this case.
> fix(en): do not log error when whitelisted_tokens_for_aa is not supported

- core/lib/zksync_core/src/api_server/tx_sender/mod.rs
Logs some info about estimated fee in API
To be able to check how some transactions are estimated
> feat(api): Log info about estimated fee

- Cargo.lock
- Cargo.toml
- prover/Cargo.lock
- prover/Cargo.toml
bumped consensus and vise deps
> chore: bumped consensus and vise deps

- core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
Add `div`, `sdiv`, `mod` and `smod` opcodes, as well as their tests
> [EVM-Equivalent-YUL] Add div, sdiv, mod, smod opcodes

- core/tests/ts-integration/package.json
- core/tests/ts-integration/tests/contracts.test.ts
- yarn.lock
Add secp256r1, transient storage, code oracle integration tests
Better integration test coverage
> test: Add secp256r1, transient storage, code oracle integration tests

- core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
This PR adds `jump` and `jumpi` opcodes tests
> [EVM-Equivalent-YUL] Add jump and jumpi opcodes

- core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
Implement tests for dup opcodes.
> [EVM-Equivalent-YUL] Add tests for dup opcodes

- core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
Implement tests for `swap` opcodes.
> [EVM-Equivalent-YUL] Add swap opcodes

- Cargo.lock
- Cargo.toml
- prover/Cargo.lock
includes https://github.com/matter-labs/era-consensus/pull/92
> chore: bumped consensus deps

- core/lib/commitment_utils/src/lib.rs
- core/lib/multivm/src/utils.rs
> fix compile for kl-factory

- core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
This PR adds sload, sstore and msize opcodes, including cold/warm cases for gas handling
> [EVM-Equivalent-YUL] Stack/Memory instructions sload, sstore and msize

- core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
This PR adds `gas`, `address`, `pc`, `balance` and `origin` opcodes tests
> [EVM-Equivalent-Yul] Add some environment opcodes

- .envrc
- core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
This PR adds `CALLER`, `CALLVALUE`, `CALLDATALOAD`, `CALLDATASIZE`, `CALLDATACOPY` tests
> [EVM-Equivalent-Yul] Add more environment opcodes

- .github/workflows/ci-core-reusable.yml
- core/lib/basic_types/src/protocol_version.rs
- core/lib/zksync_core/src/state_keeper/io/common/tests.rs
- core/lib/zksync_core/src/state_keeper/tests/mod.rs
* Fixes failing unittests and enables them back into CI
> fix: Fixes EVM-556 - unitests

- core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
This PR adds dynamic gas handling for balance opcode, including address warming
> [EVM-Equivalent-Yul] Dynamic gas for balance

- core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
Add tests for `SHR`, `SHL` and `SAR` opcodes.
> [EVM-Equivalent-YUL]  Evm yul byte opcodes

- core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
Implement tests for log opcodes
> [EVM-Equivalent-YUL]  Implement tests for log opcodes

- yarn.lock
> fix(yarn.lock): zksync-ethers commit fix

- core/tests/ts-integration/package.json
- core/tests/upgrade-test/package.json
- package.json
- yarn.lock
> fix: zksync-ethers branch changed to sb-old-sdk

- Cargo.lock
> chore(kl-factory): Fix cargo deny

- .github/workflows/ci-core-reusable.yml
- core/tests/loadnext/src/executor.rs
- core/tests/loadnext/src/sdk/ethereum/mod.rs
- infrastructure/zk/src/contract.ts
- infrastructure/zk/src/init.ts
- yarn.lock
> fix(shared bridge): fix loadtest

- core/lib/zksync_core/src/genesis.rs
> chore: Fix comments from mishap

- .github/workflows/build-contract-verifier-template.yml
- .github/workflows/build-docker-from-tag.yml
- .github/workflows/ci.yml
- .github/workflows/release-test-stage.yml
Separates contract verifier release
> ci: Separate contract verifier release

- core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
Add tests for EXTCODESIZE EXTCODECOPY 
RETURNDATASIZE RETURNDATACOPY tests need the opcode `STATICCALL`.
> [EVM-Equivalent-YUL] Evm yul env4

- core/lib/zksync_core/src/eth_sender/eth_tx_aggregator.rs
> chore(eth_sender): refactor commit txn encoding

- core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
> [EVM-Equivalence-Yul] Add delegatecall opcode tests

- core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
Add tests for `EXTCODEHASH`.
Tests Ignore for now.
There are some inconsistencies between the `bytecodehash` obtained from the yul EVM and the precomputed `bytecodehashes` located at `era-contracts -> system-contracts/SystemContractsHashes.json`.
> [EVM-Equivalent-YUL] Evm yul extcodehash

- core/lib/zksync_core/src/eth_sender/eth_tx_aggregator.rs
> fix: Weaker assert for protocol version for operations

- docker/contract-verifier/Dockerfile
Adds zksolc vm1.5.0 to contract verifier image
To verify system contract that were compiled with this version
> feat(contract-verifier): Add zksolc vm1.5.0

- Cargo.lock
- core/bin/external_node/src/main.rs
- core/lib/zksync_core/src/lib.rs
- core/node/commitment_generator/Cargo.toml
- core/node/commitment_generator/src/input_generation.rs
- core/node/commitment_generator/src/lib.rs
- core/node/node_framework/examples/main_node.rs
- core/node/node_framework/src/implementations/layers/commitment_generator.rs
> chore(node): remove is_validium flag and make it more extensible

- infrastructure/zk/src/init.ts
> Fix local bridge testing

- core/node/node_framework/src/service/tests.rs
Due to the fact that the task wrapper has a `tokio::select`  [waiting for either ](https://github.com/matter-labs/zksync-era/blob/main/core/node/node_framework/src/task.rs#L69) barrier or stop signal, the second task in the test may not be started at all. This is highly unlikely, but it happened at least 2 times on CI.
This PR fixes it by introducing an additional barrier that makes sure that both tasks have started.
The fix is somewhat clunky, but it should do the job, and the tests there warrant a refactoring anyways, so let's keep it like that for the time being.
Flaky tests bad.
> chore(node_framework): Fix flaky test

- core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
This PR fixes tests gas after codecopy was fixed, the +3 in the tests is because we re-added the gas cost for `ISZERO`
> [EVM-Equivalent_YUL] Fix codecopy gas

- .github/workflows/release-please-cargo-lock.yml
Adds workflow to automatically update Cargo.lock in release-please PR
> ci: Update Cargo.lock in release-please PR

- core/lib/basic_types/src/protocol_version.rs
Update current version of provers
> feat: Update provers current version

- prover/prover_cli/src/cli.rs
- prover/prover_cli/src/commands/mod.rs
- prover/prover_cli/src/commands/restart.rs
Implements `restart` command for Prover CLI to restart the proving of a batch or a prover job.
> feat(Prover CLI): `restart` cmd

- .github/workflows/build-core-template.yml
Fix IMAGE_TAG_SUFFIX in create_manifest
> ci: Fix IMAGE_TAG_SUFFIX in create_manifest

- docker/zk-environment/Dockerfile
> ci: Fix docker build for zk-enviroment image

- core/lib/zksync_core/src/utils/mod.rs
Fixes call error detection in `ensure_l1_batch_commit_data_generation_mode()`. 
Ethereum client is still broken fort the mainnet EN (where the L1 contracts are not updated yet).
> fix(eth-client): Fix call error detection

- prover/Cargo.lock
Updates prover cargo lock
Wasn't updated in one of recent PRs which broke CI
> fix: Update prover cargo lock

- core/tests/ts-integration/package.json
- etc/ERC20/package.json
- etc/contracts-test-data/package.json
- infrastructure/protocol-upgrade/package.json
- infrastructure/zk/package.json
- yarn.lock
I think the source for flakiness might be caused by https://github.com/NomicFoundation/hardhat/commit/45025fbbb3381351f9f3cf4cdaf0afd39aa3d77b so I am trying to bump hardhat to resolve
Because CI is FUBAR
> chore: bump hardhat version to decrease flakiness

- .github/workflows/ci-core-reusable.yml
- core/lib/zksync_core/src/lib.rs
Temporary disable validium, which got broken over the weekend due to emergency. 
The fix is coming in PR 1910.
> chore: Temporary disable validium in CI until PR/1910

- docker-compose-cpu-runner.yml
- docker-compose-gpu-runner-cuda-12-0.yml
- docker-compose-gpu-runner.yml
- docker-compose.yml
Upgrade reth to latest version
> chore: upgrade reth to latest version

- core/tests/ts-integration/src/context-owner.ts
fixes awaiting base token transfers
> test: fix awaiting base token transfers

- core/lib/multivm/src/versions/vm_latest/oracles/storage.rs
Change comment and local variable names to better explain pubdata.
> chore: clarify pubdata logic

- .github/workflows/ci.yml
Requires build-contract-verifier stage to pass CI
> ci: Require build-contract-verifier

- docker/zk-environment/Dockerfile
- Adds foundry installation to zk-environment Dockerfile
- This is necessary for adding CI to zk_toolbox
> feat: add foundry installation to zk-environment Dockerfile

- Cargo.lock
- prover/Cargo.lock
> chore(vm): Mirror changes from zk_evm

- core/lib/multivm/src/versions/vm_fast/glue.rs
- core/lib/multivm/src/versions/vm_fast/vm.rs
> fixes to logs deduplication and tx number tracking

- zk_toolbox/README.md
> chore(zk_toolbox): Add installation guide

- zk_toolbox/crates/common/src/forge.rs
> fix(zk_toolbox): Fix error with balances

- zk_toolbox/README.md
> fix(zk_toolbox): Fix installation guide

- core/tests/recovery-test/tests/genesis-recovery.test.ts
Returns consistency checker checks to the genesis recovery test.
These checks were previously too slow because of commitment generation, but now it is sped up.
> test(en): Add consistency checker checks to recovery test

- .gitignore
- ZkStack.yaml
- chains/era/ZkStack.yaml
- core/tests/ts-integration/package.json
- core/tests/ts-integration/src/env.ts
- core/tests/ts-integration/src/jest-setup/global-setup.ts
- yarn.lock
> feat(test): Add filebased config support for integration tests

- core/node/house_keeper/src/prover/queue_reporter/fri_witness_generator_queue_reporter.rs
Emit correct values for metric
> fix: fix metrics reporting wrong values

- core/tests/ts-integration/package.json
- core/tests/ts-integration/src/helpers.ts
- core/tests/ts-integration/tests/api/contract-verification.test.ts
- core/tests/ts-integration/tests/api/web3.test.ts
- core/tests/ts-integration/tests/base-token.test.ts
- core/tests/ts-integration/tests/contracts.test.ts
- core/tests/ts-integration/tests/custom-account.test.ts
- core/tests/ts-integration/tests/erc20.test.ts
- core/tests/ts-integration/tests/ether.test.ts
- core/tests/ts-integration/tests/fees.test.ts
- core/tests/ts-integration/tests/l1.test.ts
- core/tests/ts-integration/tests/mempool.test.ts
- core/tests/ts-integration/tests/paymaster.test.ts
- core/tests/ts-integration/tests/system.test.ts
- yarn.lock
Migrate to `zksync-ethers:v6.8.0-beta.5` which fixes issues occurred in integration tests.
> test(ts-integration): migrate tests to `zksync-ethers:v6.8.0-beta.5`

- Cargo.lock
> chore(vm): Update zk_evm 

- .github/workflows/build-prover-template.yml
fix CI for protocol version binary
CI is not working
> fix: fix CI for protocol version binary

- .github/workflows/build-prover-template.yml
Fix protocol_version between jobs propagation in build-prover-template.yml.
> ci: Fix protocol_version between jobs propagation

- zk_toolbox/Cargo.lock
- zk_toolbox/crates/config/src/forge_interface/deploy_ecosystem/input.rs
- zk_toolbox/crates/config/src/genesis.rs
- zk_toolbox/crates/types/Cargo.toml
- zk_toolbox/crates/types/src/lib.rs
- zk_toolbox/crates/types/src/protocol_version.rs
Fix zk toolbox for using semantic protocol version
> fix(zk_toolbox): Fix protocol version

- core/lib/multivm/src/versions/vm_fast/vm.rs
Changes to go with matter-labs/vm2#43
> chore: updates to newest vm2 code

- etc/env/file_based/general.yaml
> fix(config): Add necessary config

- docker/contract-verifier/Dockerfile
> feat(contract-verifier): Add zksolc v1.5.0

- flake.lock
- flake.nix
update the nix flake
to reproducibly build the zksync-era server and to develop easily with the help of nix
> chore(nix): update flake to support new rust toolchain

- core/node/state_keeper/src/keeper.rs
- core/node/state_keeper/src/metrics.rs
- core/node/state_keeper/src/updates/mod.rs
Adds metrics to state keeper for better observability
> chore: Add more state keeper metrics

- prover/Cargo.lock
- prover/prover_cli/src/commands/debug_proof.rs
* Now prover_cli will also debug recursive circuits (for example recursion tip)
> feat: support debugging of recursive circuits in prover_cli

- zk_toolbox/crates/zk_inception/src/config_manipulations.rs
> fix(zk_toolbox): Use the same l2 address for shared and erc20 bridge

- core/node/node_framework/src/implementations/layers/l1_gas.rs
Adds a check that would prevent gas adjuster task from actually running if there are no users of `GasAdjuster`.
`GasAdjuster` is provided as a resource for anyone to use, but its support task uses RPC (which has usage limits), so it doesn't make sense to run it if nobody uses `GasAdjuster`.
> fix(node_framework): Run gas adjuster task only if necessary

- Cargo.lock
- prover/Cargo.lock
https://rustsec.org/advisories/RUSTSEC-2024-0344
> chore: bumped curve25519

- core/lib/multivm/src/versions/vm_latest/old_vm/oracles/decommitter.rs
> fix(vm): fix insertion to `decommitted_code_hashes`

- .github/release-please/config.json
> chore: remove release override

- core/node/eth_sender/src/eth_fees_oracle.rs
- core/node/fee_model/src/l1_gas_price/gas_adjuster/mod.rs
- core/node/fee_model/src/l1_gas_price/mod.rs
This PR implements point (1) from
https://www.notion.so/matterlabs/Eth-sender-blob-fees-problem-b84e1715248944559a0a656a6c9da320
> feat(eth-sender): separate gas calculations for blobs transactions

- docs/guides/advanced/docker_and_ci.md
* Documentation explaining how to use docker to debug the CI issues.
> chore: documentation about docker

- docker/contract-verifier/Dockerfile
> feat(contract-verifier): Add new compilers

- zk_toolbox/Cargo.lock
- zk_toolbox/crates/common/Cargo.toml
- zk_toolbox/crates/common/src/cmd.rs
- zk_toolbox/crates/common/src/docker.rs
- zk_toolbox/crates/common/src/forge.rs
- zk_toolbox/crates/zk_inception/src/commands/chain/initialize_bridges.rs
- zk_toolbox/crates/zk_inception/src/commands/ecosystem/init.rs
- zk_toolbox/crates/zk_inception/src/commands/prover/gcs.rs
- zk_toolbox/crates/zk_inception/src/commands/prover/generate_sk.rs
- zk_toolbox/crates/zk_inception/src/commands/prover/init.rs
- zk_toolbox/crates/zk_inception/src/external_node.rs
> feat(zk_toolbox): use low level command for running verbose command"

- docs/guides/setup-dev.md
> fix(docs): Update nodejs and sqlx version

- core/lib/dal/.sqlx/query-4570e9ffd0b2973d0bc2986c391d0a59076dda4aa572ade2492f37e537fdf6ed.json
- core/lib/dal/src/eth_sender_dal.rs
This PR should have been part of: https://github.com/matter-labs/zksync-era/pull/2404
> fix(eth-sender): missing fix in second query calculating txs unsent txs

- Cargo.lock
- Cargo.toml
- core/node/consensus/src/storage/store.rs
- deny.toml
- prover/Cargo.lock
- prover/Cargo.toml
- zk_toolbox/Cargo.lock
Changes all the git dependencies we have (prover included) to ones published on crates.io
Part of release cycle.
> feat: Switch to using crates.io deps

- core/bin/external_node/src/config/observability.rs
- core/bin/snapshots_creator/src/main.rs
- core/bin/zksync_tee_prover/src/main.rs
- core/lib/config/src/configs/utils.rs
- core/lib/env_config/src/api.rs
- core/lib/protobuf_config/src/utils.rs
- core/tests/loadnext/src/main.rs
- prover/witness_generator/src/main.rs
> feat(config): Make getaway_url optional

- prover/prover_fri_types/src/lib.rs
Bump prover protocol patch
Prepare for upcoming upgrade
> feat(prover)!: Bump prover protocol patch

- core/node/consensus/src/en.rs
- core/node/consensus/src/era.rs
- core/node/consensus/src/mn.rs
Adds debug logs to show whether the new attester key has been parsed.
On stage2 the main node doesn't seem to run attestations, while the external node does, even though both have the correct secret keys mapped to the containers. This is just a sanity check to see whether the values are present in the parsed configs, it's not an attempt to solve anything.
> test: Log whether we have attester key

- Cargo.lock
- deny.toml
> chore: fix cargo deny check

- .github/workflows/ci-common-reusable.yml
- .github/workflows/ci-core-lint-reusable.yml
- .github/workflows/ci-core-reusable.yml
- .github/workflows/ci-prover-reusable.yml
- .github/workflows/ci-zk-toolbox-reusable.yml
- .github/workflows/ci.yml
Add docker login
Fix rate limit for docker pull
> ci: add docker login for ci steps

- .github/workflows/build-prover-fri-gpu-gar.yml
- .github/workflows/build-prover-template.yml
Fixes with docker login
Failed jobs in CI/CD
> ci: fixes with docker login

- .github/workflows/build-docker-from-tag.yml
- .github/workflows/build-prover-fri-gpu-gar.yml
- .github/workflows/release-test-stage.yml
Fix workflow with missed docker auth
Broken prover build workflow
> ci: fix docker auth with prover gar gpu

- docs/guides/external-node/09_decentralization.md
This way building the binary locally is no longer necessary.
> chore: Changed the instruction in documentation to use docker commands

- infrastructure/zk/src/database.ts
Right now, we're running `cargo sqlx prepare --check` for local databases always.
It's justified for `zk db setup`, because we compile with `SQLX_OFFLINE = true` to prevent stale `.sqlx-data`, but it makes no sense for unit tests.
Recompilations are long.
> fix(zk): Do not cause recompilation when running 'zk test rust'

- etc/env/file_based/general.yaml
- zk_toolbox/crates/common/src/git.rs
> feat(zk_toolbox): improve git pull function 

- core/lib/contract_verifier/src/lib.rs
> fix(contract verifier): Fix config values 

- .github/workflows/zk-environment-publish.yml
- docker/zk-environment/20.04_amd64_cuda_11_8.Dockerfile
- docker/zk-environment/20.04_amd64_cuda_12_0.Dockerfile
- docker/zk-environment/Dockerfile
Additionally push zk-environment Docker images to ghcr.io
One more public mirror with no rate limits in Github Actions
> ci: Add zk-environment to ghcr.io

- .github/workflows/zk-environment-publish.yml
Fix permissions for GH container registry in Workflows
> ci: Fix permissions for GH container registry

- docker/zk-environment/Dockerfile
Switch zk-environment foundry profile to release
Reduce errs in foundry install
> ci: Switch zk-environment foundry profile to release

- docker/contract-verifier/Dockerfile
> feat(contract-verifier): Add some compilers

- docs/guides/external-node/09_decentralization.md
- docs/guides/external-node/10_treeless_mode.md
Documents the treeless operation mode.
Part of preparations for the feature release.
> docs(en): Document treeless mode

- core/bin/external_node/src/main.rs
- core/bin/external_node/src/tests/mod.rs
- core/bin/zksync_server/src/main.rs
- core/bin/zksync_tee_prover/src/main.rs
- core/lib/config/src/configs/fri_prover.rs
- core/lib/config/src/testonly.rs
- core/lib/env_config/src/fri_prover.rs
- core/lib/protobuf_config/src/prover.rs
- core/lib/vlog/src/lib.rs
- core/lib/vlog/src/opentelemetry/mod.rs
- core/node/node_framework/examples/showcase.rs
- core/node/node_framework/src/service/mod.rs
- core/node/node_framework/src/service/tests.rs
- prover/crates/bin/prover_fri_gateway/src/traits.rs
- prover/crates/lib/prover_fri_utils/src/region_fetcher.rs
- zk_toolbox/crates/zk_inception/src/commands/prover/args/init.rs
- zk_toolbox/crates/zk_inception/src/messages.rs
I've promised to fix a bunch of comments in the follow-up PR. This is the follow-up PR.
Acting on the postponed comments.
> chore: Minor follow-ups

- .github/release-please/config.json
> chore(release-please): Fix release-type

- .github/release-please/config.json
> chore(release-please): Move plugin to the zk_toolbox

- zk_toolbox/crates/common/Cargo.toml
- zk_toolbox/crates/config/Cargo.toml
- zk_toolbox/crates/types/Cargo.toml
- zk_toolbox/crates/zk_inception/Cargo.toml
- zk_toolbox/crates/zk_supervisor/Cargo.toml
> chore(release-please): Set zk_toolbox version to the default one

- zk_toolbox/crates/zk_supervisor/src/commands/test/mod.rs
- zk_toolbox/crates/zk_supervisor/src/commands/test/prover.rs
- zk_toolbox/crates/zk_supervisor/src/messages.rs
Add zk_supervisor test prover command
> feat(zk_toolbox): Add zk_supervisor test prover command

- zk_toolbox/crates/zk_inception/src/commands/ecosystem/args/create.rs
> chore(zk_toolbox): zk fmt

- Cargo.lock
- Cargo.toml
- prover/Cargo.lock
- prover/Cargo.toml
- Bumps harness. It has changes needed to speed up proving. No changes for the sequencer.
- Bumps crypto deps. They've been updated to use the modern harness.
Optimizations & dependency graph improvements.
> feat: Bump harness & gpu deps

- docs/guides/external-node/docker-compose-examples/mainnet-external-node-docker-compose.yml
- docs/guides/external-node/docker-compose-examples/testnet-external-node-docker-compose.yml
- docs/guides/external-node/prepared_configs/mainnet_consensus_config.yaml
- docs/guides/external-node/prepared_configs/testnet_consensus_config.yaml
Add more consensus nodes for testnet and mainnet into config example.
Bumps External Node image version in docker example.
> docs: Add more consensus nodes.

- docker/zk-environment/Dockerfile
> chore(docker): Use foundry-zksync

- zk_toolbox/README.md
> docs(zk_toolbox): Add zks lint and fmt docs

- .github/workflows/zk-environment-publish.yml
> chore(ci): update runner for zk_environment_multiarch_manifest

- .github/workflows/release-test-stage.yml
Same changes as in https://github.com/matter-labs/zksync-era/pull/2687, but for stage release workflow
> chore(prover): Add avx512 bwg build to stage release workflow

- prover/docs/01_gcp_vm.md
A few reports have shown that using spot instances is very luck-dependent, so it's not worth trying at the cost of flow disruption.
> docs(prover): Recommend standard provisioning over spot

- .github/workflows/build-witness-generator-template.yml
> chore: Remove unneeded step from avx512-BWG build flow

- docker/contract-verifier/Dockerfile
Adds zksolc 1.5.3, zkvyper 1.5.4
> feat(contract-verifier): Add compilers to contract-verifier

- CODEOWNERS
Uses a dedicated team for release management in CODEOWNERS.
Better configurability.
> chore: Use a team in CODEOWNERS

- zk_toolbox/crates/zk_inception/README.md
- zk_toolbox/crates/zk_supervisor/README.md
> chore(zk_toolbox): Update readme

- .github/workflows/check-pr-title.yml
Updates the CI for PR title validation.
- Old action is unmaintained, switching to the modern one.
- New workflow would leave a helpful comment if check fails (and removes it once it passes).
DevEx
> ci: Update PR title CI

- etc/lint-config/ignore.yaml
- zk_toolbox/Cargo.lock
- zk_toolbox/crates/zk_supervisor/Cargo.toml
- zk_toolbox/crates/zk_supervisor/src/commands/fmt.rs
- zk_toolbox/crates/zk_supervisor/src/commands/lint_utils.rs
> fix(lint): Move ignore files out from the code

- .github/workflows/ci-core-lint-reusable.yml
- .github/workflows/ci-zk-toolbox-reusable.yml
- zk_toolbox/crates/zk_supervisor/src/commands/database/args/mod.rs
- zk_toolbox/crates/zk_supervisor/src/commands/database/check_sqlx_data.rs
- zk_toolbox/crates/zk_supervisor/src/commands/database/drop.rs
- zk_toolbox/crates/zk_supervisor/src/commands/database/migrate.rs
- zk_toolbox/crates/zk_supervisor/src/commands/database/mod.rs
- zk_toolbox/crates/zk_supervisor/src/commands/database/new_migration.rs
- zk_toolbox/crates/zk_supervisor/src/commands/database/prepare.rs
- zk_toolbox/crates/zk_supervisor/src/commands/database/reset.rs
- zk_toolbox/crates/zk_supervisor/src/commands/database/setup.rs
- zk_toolbox/crates/zk_supervisor/src/dals.rs
- zk_toolbox/crates/zk_supervisor/src/messages.rs
> feat(zk_toolbox): Move check sql to the lint step

- core/node/external_proof_integration_api/src/lib.rs
- etc/env/file_based/genesis.yaml
> chore(configs): Update protocol version

- core/lib/protobuf_config/src/observability.rs
> fix(config): Do not panic for observability config

- docker/witness-vector-generator/Dockerfile
Follow-up to #2784 
Forgot to update one dockerfile.
> chore: Fix keys paths for wvg docker image

- core/bin/verified_sources_fetcher/README.md
Adds README for verified sources fetcher
> chore: Add README for verified sources fetcher

- Cargo.lock
- core/bin/external_node/Cargo.toml
- core/lib/circuit_breaker/Cargo.toml
- core/lib/contract_verifier/Cargo.toml
- core/lib/da_client/Cargo.toml
- core/lib/db_connection/Cargo.toml
- core/lib/tee_verifier/Cargo.toml
- core/lib/utils/Cargo.toml
- core/lib/zksync_core_leftovers/Cargo.toml
- core/node/consistency_checker/Cargo.toml
- core/node/db_pruner/Cargo.toml
- core/node/fee_model/Cargo.toml
- core/node/node_framework/Cargo.toml
- core/node/proof_data_handler/Cargo.toml
- prover/Cargo.lock
Resolves https://github.com/matter-labs/zksync-era/issues/2783
> chore: clean up dependencies

- prover/crates/bin/prover_cli/src/cli.rs
- prover/crates/bin/prover_cli/src/commands/status/batch.rs
Do not use envs inside Prover Cli
> fix(prover): do not get max attempts from config

- docker/build-base/Dockerfile
Adding installation of sccache to build-base Dockerfile
To speed-up docker builds
> feat(build-base): Add sccache to build-base Dockerfile

- etc/lint-config/ignore.yaml
- etc/utils/src/index.ts
- zk_toolbox/crates/zk_inception/src/commands/containers.rs
- zk_toolbox/crates/zk_inception/src/commands/ecosystem/mod.rs
> fix(zk_toolbox): Clone era observability

- .github/workflows/ci-core-reusable.yml
- core/tests/ts-integration/hardhat.config.ts
- core/tests/ts-integration/tests/api/contract-verification.test.ts
- zk_toolbox/crates/zk_supervisor/src/commands/test/integration.rs
> chore: update solc in tests

- .github/workflows/ci-common-reusable.yml
- .github/workflows/ci-core-lint-reusable.yml
- .github/workflows/ci-core-reusable.yml
- .github/workflows/ci-docs-reusable.yml
- .github/workflows/ci-prover-reusable.yml
- .github/workflows/vm-perf-comparison.yml
- .github/workflows/vm-perf-to-prometheus.yml
Enable full usage of sccache in CI tests
Speed up tests
> feat(ci): Fully use sccache in CI tests

- .github/workflows/vm-perf-to-prometheus.yml
> fix(ci): vm perf to prometheus

- .github/workflows/build-base.yml
Workflow to build base-image
Added ability to push to ghcr.io
> feat(ci): Add building base docker image

- .github/workflows/build-base.yml
Fix multiarch command for build-base-image CI
> fix(ci): Fix multiarch for build-base CI

- .github/workflows/build-runtime-base.yml
- docker/runtime-base/Dockerfile
Adding image which will be used as runtime-base for services
As a workaround for dockerhub ratelimits
> feat(ci): Add runtime-base image

- .github/workflows/build-runtime-base.yml
Proper type of var for platforms in docker build action
> fix(ci): Proper type of var for platforms in docker build action

- .github/workflows/vm-perf-to-prometheus.yml
- zk_toolbox/crates/common/src/cmd.rs
- zk_toolbox/crates/common/src/term/logger.rs
> fix(zk_toolbox): show readable log

- core/lib/vm_executor/src/storage.rs
- core/node/node_sync/src/external_io.rs
- core/node/state_keeper/src/io/common/tests.rs
- core/node/state_keeper/src/io/mempool.rs
- core/node/tee_verifier_input_producer/src/lib.rs
- core/node/vm_runner/src/storage.rs
Refactors `L1BatchParamsProvider`, in particular its construction.
To have more intuitive DevEx.
> refactor(vm): Refactor L1 batch params provider

- .github/workflows/ci-core-reusable.yml
- core/lib/l1_contract_interface/src/i_executor/structures/commit_batch_info.rs
- core/lib/multivm/src/versions/vm_latest/types/internals/pubdata.rs
- core/node/api_server/src/web3/namespaces/zks.rs
- core/node/fee_model/src/l1_gas_price/gas_adjuster/mod.rs
- core/node/genesis/src/lib.rs
- core/tests/ts-integration/src/context-owner.ts
- core/tests/ts-integration/src/modifiers/balance-checker.ts
- core/tests/ts-integration/tests/base-token.test.ts
- core/tests/ts-integration/tests/ether.test.ts
- zk_toolbox/crates/zk_inception/src/accept_ownership.rs
- zk_toolbox/crates/zk_inception/src/commands/chain/init.rs
- zk_toolbox/crates/zk_inception/src/commands/chain/migrate_to_gateway.rs
> feat(gateway): Improve variety of chains for sync layer stable

- .github/workflows/build-prover-fri-gpu-gar-and-circuit-prover-gpu-gar.yml
Copy setup keys to be available for docker/circuit-prover-gpu-gar.
To build circuit-prover-gpu image with keys.
> ci: Copy setup_keys to docker/circuit-prover-gpu-gar

- core/node/eth_watch/src/tests.rs
- zk_toolbox/crates/config/src/ecosystem.rs
- zk_toolbox/crates/zk_inception/src/commands/chain/build_transactions.rs
- zk_toolbox/crates/zk_inception/src/commands/chain/deploy_l2_contracts.rs
- zk_toolbox/crates/zk_inception/src/commands/chain/deploy_paymaster.rs
- zk_toolbox/crates/zk_inception/src/commands/chain/genesis.rs
- zk_toolbox/crates/zk_inception/src/commands/chain/init.rs
- zk_toolbox/crates/zk_inception/src/commands/chain/set_token_multiplier_setter.rs
- zk_toolbox/crates/zk_inception/src/commands/consensus.rs
- zk_toolbox/crates/zk_inception/src/commands/contract_verifier/run.rs
- zk_toolbox/crates/zk_inception/src/commands/explorer/backend.rs
- zk_toolbox/crates/zk_inception/src/commands/external_node/init.rs
- zk_toolbox/crates/zk_inception/src/commands/external_node/prepare_configs.rs
- zk_toolbox/crates/zk_inception/src/commands/external_node/run.rs
- zk_toolbox/crates/zk_inception/src/commands/prover/compressor_keys.rs
- zk_toolbox/crates/zk_inception/src/commands/prover/init.rs
- zk_toolbox/crates/zk_inception/src/commands/prover/run.rs
- zk_toolbox/crates/zk_inception/src/commands/server.rs
- zk_toolbox/crates/zk_supervisor/src/commands/config_writer.rs
- zk_toolbox/crates/zk_supervisor/src/commands/prover/info.rs
- zk_toolbox/crates/zk_supervisor/src/commands/prover/insert_batch.rs
- zk_toolbox/crates/zk_supervisor/src/commands/prover/insert_version.rs
- zk_toolbox/crates/zk_supervisor/src/commands/snapshot.rs
- zk_toolbox/crates/zk_supervisor/src/commands/test/fees.rs
- zk_toolbox/crates/zk_supervisor/src/commands/test/integration.rs
- zk_toolbox/crates/zk_supervisor/src/commands/test/loadtest.rs
- zk_toolbox/crates/zk_supervisor/src/commands/test/recovery.rs
- zk_toolbox/crates/zk_supervisor/src/commands/test/revert.rs
- zk_toolbox/crates/zk_supervisor/src/commands/test/wallet.rs
- zk_toolbox/crates/zk_supervisor/src/dals.rs
> chore(zk_toolbox): Use load current chain function

- zk_toolbox/crates/zk_inception/src/commands/update.rs
> fix(zk_toolbox): Correct secrets

- core/node/eth_watch/src/client.rs
> feat(eth-watch): catch another reth error

- zk_toolbox/crates/common/src/term/logger.rs
- zk_toolbox/crates/zk_supervisor/src/commands/status.rs
Add component boxes to status page
> feat(zkstack_cli): Add component boxes to status page

- zk_toolbox/Cargo.lock
- zk_toolbox/crates/common/src/lib.rs
- zk_toolbox/crates/common/src/prerequisites.rs
- zk_toolbox/crates/zk_inception/Cargo.toml
- zk_toolbox/crates/zk_inception/src/commands/contract_verifier/args/releases.rs
- zk_toolbox/crates/zk_inception/src/commands/contract_verifier/init.rs
- zk_toolbox/crates/zk_inception/src/commands/prover/compressor_keys.rs
Replace curl and wget with reqwest
> refactor(zkstack_cli): Replace curl and wget with reqwest

- docker/Makefile
- docker/zk-environment/20.04_amd64_cuda_11_8.Dockerfile
- docker/zk-environment/20.04_amd64_cuda_12_0.Dockerfile
- docker/zk-environment/Dockerfile
> feat(zkstack_cli): Add more folders to containers' PATH

- docker/Makefile
- docker/zk-environment/20.04_amd64_cuda_11_8.Dockerfile
- docker/zk-environment/20.04_amd64_cuda_12_0.Dockerfile
- docker/zk-environment/Dockerfile
Update PATH extension command in containers
> feat(zkstack_cli): Update PATH extension command in containers

- .github/workflows/release-test-stage.yml
> ci: Switch `Build and release Stage` to new build workflows.

- .github/workflows/release-test-stage.yml
> ci: Remove unneeded ERA_BELLMAN_CUDA_RELEASE

- .github/workflows/ci-core-reusable.yml
- core/tests/ts-integration/tests/fees.test.ts
> ci: Fix folder for fee tests

- .github/workflows/new-build-prover-template.yml
> ci: Fix new stage build CI

- .github/workflows/vm-perf-to-prometheus.yml
> fix(ci): install zkstack at the correct time

- .github/workflows/build-core-template.yml
> fix(ci): Do not build test contracts

- .github/workflows/build-core-template.yml
> fix(ci): Don't build zkstack if it's not necessary

- docker/contract-verifier/Dockerfile
> feat(contract-verifier): add compiler 1.5.6

- zkstack_cli/zkstackup/install
- zkstack_cli/zkstackup/zkstackup
> fix(zkstack): Move installation always to .local/bin

- infrastructure/protocol-upgrade/src/transaction.ts
> feat(upgrade): update tool to generate calldata for setting new chain creation params

- docker/contract-verifier/Dockerfile
> feat(contract-verifier): add zkvyper 1.5.6

- prover/crates/bin/prover_autoscaler/src/global/scaler.rs
Do not exit on missing watcher data.
To fix always exiting in `scaler_period` after start due to missing data.
ref ZKD-1855
> fix(prover): Do not exit on missing watcher data.

- core/node/state_keeper/src/keeper.rs
save call trace for upgrade txs
save call trace for upgrade txs
> fix(state-keeper): save call trace for upgrade txs

- core/bin/zksync_tee_prover/src/metrics.rs
- core/bin/zksync_tee_prover/src/tee_prover.rs
Fix counter metric type to be Counter.
To have correct calculation of network errors across restarts.
> fix: Fix counter metric type to be Counter.

- prover/crates/bin/prover_autoscaler/src/global/watcher.rs
Fix error found by Doc lint.
ref ZKD-1855
> fix: Fix Doc lint.

- zkstack_cli/README.md
Add manual installation instruction for zkstack_cli.
Using `curl | bash` could be problematic, we should provide better way.
> docs: Add manual installation instruction for zkstack_cli

- .github/workflows/build-prover-fri-gpu-gar-and-circuit-prover-gpu-gar.yml
Move keys from prover to circuit-prover as the build sequentially.
Remove prover-gar image after it being uploaded.
To allow running this on a machine with 100G disk.
> ci: Reduce GAR builder disk usage by moving keys around.

- .github/workflows/ci-prover-reusable.yml
prover ci should check formatting with zkstack_cli
> ci: unify fmt check

- .github/workflows/build-prover-fri-gpu-gar-and-circuit-prover-gpu-gar.yml
There is no need to remove local docker image.
> ci: Remove invalid step from GAR build workflow

- core/bin/zksync_tee_prover/src/main.rs
Add a prometheus pull listener.
To get the metrics out of the zk_tee_prover
> fix(tee_prover): add prometheus pull listener

- docker/contract-verifier/Dockerfile
add compilers 1.5.7 to contract verifier
> feat(contract-verifier): add compilers 1.5.7

- prover/crates/bin/prover_autoscaler/README.md
> chore: Add README.md with basic information about Prover Autoscaler

- core/lib/types/src/debug_flat_call.rs
- core/node/api_server/src/web3/namespaces/debug.rs
> fix(tracer): Add error to flat tracer

- zkstack_cli/crates/config/src/zkstack_config.rs
- zkstack_cli/crates/zkstack/src/commands/containers.rs
- zkstack_cli/crates/zkstack/src/commands/ecosystem/create.rs
- zkstack_cli/crates/zkstack/src/messages.rs
> feat(zkstack): Run containers with either chain or ecosystem

- Cargo.lock
- deny.toml
> fix: Fixed cargo deny

- Cargo.lock
- Cargo.toml
- ZkStack.yaml
- core/node/api_server/src/execution_sandbox/execute.rs
- core/node/zkos_state_keeper/src/keeper.rs
- rust-toolchain
Use main branch of zk_ee and fixes to make it works.
to integrate newest zk_ee changes
> feat(zk_os): works with main zk_ee branch

- Cargo.lock
- core/lib/contracts/src/lib.rs
- core/lib/eth_client/src/clients/http/query.rs
- core/lib/l1_contract_interface/Cargo.toml
- core/lib/l1_contract_interface/src/i_executor/methods/commit_batches.rs
- core/lib/mini_merkle_tree/Cargo.toml
- core/lib/multivm/src/versions/shadow/tests.rs
- core/lib/types/Cargo.toml
- core/lib/types/src/abi.rs
- core/lib/types/src/protocol_upgrade.rs
- core/lib/types/src/storage/mod.rs
- core/lib/vm_interface/src/storage/in_memory.rs
- core/node/api_server/src/web3/metrics.rs
- core/node/base_token_adjuster/src/base_token_l1_behaviour.rs
- core/node/consensus/Cargo.toml
- core/node/genesis/src/utils.rs
- core/node/node_framework/src/implementations/layers/base_token/base_token_ratio_persister.rs
- core/node/node_sync/Cargo.toml
- prover/Cargo.lock
- zkstack_cli/Cargo.lock
> chore: sync layer stable clean up

- core/lib/dal/.sqlx/query-18e351067537a6fc5d837f01778eeb89dcf134f97acb695e7f232cbd3839e81b.json
- core/lib/dal/.sqlx/query-a8cc4da6200478a72a1b490d302b8a0949212bf66c602024aaa9843b4c66f965.json
- core/lib/dal/src/eth_sender_dal.rs
- core/lib/types/src/abi.rs
- core/lib/types/src/protocol_upgrade.rs
- core/node/eth_watch/src/client.rs
- core/node/eth_watch/src/event_processors/decentralized_upgrades.rs
- core/node/eth_watch/src/tests/client.rs
> feat: sync with main

- core/lib/dal/src/transactions_dal.rs
- core/lib/mempool/src/mempool_store.rs
- core/node/state_keeper/src/mempool_actor.rs
- core/node/state_keeper/src/metrics.rs
> feat: Add logging & metrics for mempool

- zkstack_cli/crates/zkstack/completion/zkstack.fish
> chore: re-generate zkstack-cli autocompletion

- docker-compose-gpu-runner-cuda-12-0.yml
- docker-compose-gpu-runner.yml
Fix for GPU forwarding in docker compose
Docker update broke old way of forwarding GPU
> fix(ci): Proper GPU forwarding in docker compose

- bin/run_loadtest_from_github_actions
make script work after Cargo.toml was moved
> ci: Update run_loadtest_from_github_actions

- .github/workflows/protobuf.yaml
- .github/workflows/vm-perf-comparison.yml
- .github/workflows/vm-perf-to-prometheus.yml
Fix CI jobs after core workspace refactoring:
> ci: fix jobs after core workspace refactoring

- .github/workflows/release-please-cargo-lock.yml
Fixing broken release please script after cargo files changed location
> fix(ci): Fixing broken release please script after cargo files changed location

- .github/workflows/protobuf.yaml
Update github-hosted runner label
Github update runner OS version
> fix(ci): Update github-hosted runner label

- docker/external-node/Dockerfile
- docker/server-v2/Dockerfile
include l1 zkout in images
it's required for genesis
> fix(docker): include l1 zkout in images

- core/tests/upgrade-test/tests/upgrade.test.ts
Explicit nonces for upgrade test
Test is flaky, sometimes incorrect nonce is used
> ci: explicit nonces for upgrade test

- .github/workflows/publish-crates.yml
- .github/workflows/release-please.yml
> ci: fix typo in param and return to release token

- core/node/api_server/src/execution_sandbox/mod.rs
- core/node/api_server/src/web3/namespaces/debug.rs
- core/node/node_storage_init/src/lib.rs
- docs/src/guides/external-node/01_intro.md
This PR contains EN improvements and fixes based on most often asked partner's questions
> chore(en): better EN documentation and minor fixes

- core/lib/basic_types/src/protocol_version.rs
> feat: update FFLONK protocol version

- core/bin/system-constants-generator/src/utils.rs
- core/lib/contracts/src/lib.rs
`zksync_contracts` is some spilled spaghetti.
> fix: Support newer versions of foundry-zksync

- core/Cargo.lock
- core/lib/types/Cargo.toml
- core/lib/types/src/fee_model.rs
- prover/Cargo.lock
- zkstack_cli/Cargo.lock
Leftovers after #3574 
Even less dependencies
> chore: remove `bidgecimal` from `zksync_types`

- .github/pull_request_template.md
This PR enhances the PR Template to be more external-entities-friendly.
With more ZK Chains run by non-Matter Labs entities, we need to scale the way we transfer knowledge and give external entities a better experience.
> docs: Improve PR Template

- core/lib/object_store/src/retries.rs
- core/node/external_proof_integration_api/src/types.rs
- prover/crates/bin/witness_generator/src/rounds/mod.rs
- prover/crates/lib/prover_dal/migrations/20250207111830_simplify_prover_jobs_indices.down.sql
- prover/crates/lib/prover_dal/migrations/20250207111830_simplify_prover_jobs_indices.up.sql
> Apply Emil's cherrypicked changes

- core/lib/multivm/src/versions/testonly/evm_emulator.rs
- core/lib/test_contracts/contracts/mock-evm/mock-evm.sol
- core/lib/types/src/storage/mod.rs
Fixes unit tests for EVM emulator.
> test(vm): Fix EVM emulator tests

- core/lib/basic_types/src/protocol_version.rs
- core/lib/basic_types/src/vm.rs
- core/lib/multivm/src/utils/mod.rs
- core/lib/multivm/src/versions/vm_fast/version.rs
- core/lib/multivm/src/versions/vm_latest/bootloader/utils.rs
- core/lib/multivm/src/versions/vm_latest/constants.rs
- core/lib/multivm/src/versions/vm_latest/types/vm_state.rs
- core/lib/multivm/src/versions/vm_latest/vm.rs
- core/lib/multivm/src/vm_instance.rs
Updates VM versions throughout the codebase.
> chore(vm): Update VM versions

- zkstack_cli/crates/zkstack/src/commands/chain/gateway_upgrade.rs
- zkstack_cli/crates/zkstack/src/commands/dev/commands/events_gatherer.rs
- zkstack_cli/crates/zkstack/src/commands/dev/commands/gateway.rs
- zkstack_cli/crates/zkstack/src/commands/dev/commands/gateway_finalize_preparation.rs
- zkstack_cli/crates/zkstack/src/commands/dev/commands/gateway_register_l2_tokens.rs
- zkstack_cli/crates/zkstack/src/commands/dev/commands/mod.rs
Do not rely on `zks_confirmedTokens` endpoint
> feat(gateway): Full indexing for token migration

- docs/src/SUMMARY.md
- docs/src/guides/advanced/17_batch_reverter.md
- docs/src/guides/advanced/README.md
Lets have a publicly facing documentation about block_reverter. It is not ideal and fully checked, but it has allowed a partner to perform this procedure successfully.
We should be documenting our tools.
> feat: batch reversion doc

- core/bin/genesis_generator/src/main.rs
- core/lib/contracts/src/lib.rs
- core/lib/types/src/system_contracts.rs
- yarn.lock
- zkstack_cli/crates/zkstack/src/commands/chain/init/configs.rs
- zkstack_cli/crates/zkstack/src/commands/dev/commands/genesis.rs
- zkstack_cli/crates/zkstack/src/commands/dev/commands/status/mod.rs
- zkstack_cli/crates/zkstack/src/commands/explorer/init.rs
- zkstack_cli/crates/zkstack/src/commands/external_node/prepare_configs.rs
- zkstack_cli/crates/zkstack/src/utils/ports.rs
Support the new zksync foundry paths
Foundry changed the compiled paths
> fix(foundry): Support modern foundry paths 

- docs/src/guides/external-node/02_configuration.md
- docs/src/guides/external-node/05_troubleshooting.md
Documents requirements for RocksDB volumes of the node.
Violating these requirements is a somewhat common issue.
> docs(en): Document RocksDB volume requirements

- core/lib/prover_interface/src/inputs.rs
- core/node/external_proof_integration_api/src/types.rs
Reverts matter-labs/zksync-era#3589
> revert "fix: Serialization issues"

- core/node/contract_verification_server/src/api_impl.rs
System contracts can be in Yul as well
> fix(contract-verifier): Allow reverification of system contracts in Yul

- core/lib/contract_verifier/src/compilers/mod.rs
Needed for https://github.com/zkSync-Community-Hub/zksync-developers/discussions/834
For old compiler versions (e.g. zksolc 1.5.4), `suppressedErrors` wasn't a part of compiler settings, so we cannot easily pass it to the contract verifier without changing a lot of components. Moreover, it's not a "real" error but a "heavy warning". If the contract was compiled and deployed with this warning, we should still allow verifying it.
> fix(contract-verifier): Ignore suppressable errors during compilation

- docs/src/guides/development.md
> docs: add How to generate the `genesis.yaml` file section

- core/lib/dal/src/tokens_dal.rs
> docs(zk_toolbox): Loadtest

- core/Cargo.lock
- core/Cargo.toml
- prover/Cargo.lock
- prover/Cargo.toml
> feat: Update zksync-protocol deps to 0.151.5

- .github/workflows/ci-core-reusable.yml
- bin/run_on_all_chains.sh
- core/tests/ts-integration/.gitignore
- core/tests/ts-integration/evm-contracts/Counter.sol
- core/tests/ts-integration/hardhat-evm.config.ts
- core/tests/ts-integration/package.json
- core/tests/ts-integration/tests/evm.test.ts
- zkstack_cli/crates/zkstack/src/commands/dev/commands/test/args/integration.rs
- zkstack_cli/crates/zkstack/src/commands/dev/commands/test/fees.rs
- zkstack_cli/crates/zkstack/src/commands/dev/commands/test/integration.rs
- zkstack_cli/crates/zkstack/src/commands/dev/commands/test/utils.rs
- zkstack_cli/crates/zkstack/src/commands/dev/messages.rs
Add integration tests for EVM contracts.
We don't currently have this kind of tests, and additional test coverage looks useful.
> test: Add integration tests for EVM contracts

- .github/workflows/release-please.yml
- core/Cargo.toml
It was wrongly removed by one of the last updates.
> chore: return crates.io release token

- core/Cargo.lock
- core/Cargo.toml
- prover/Cargo.lock
- prover/Cargo.toml
To remove git dependencies and unlock crates.io publishing.
> chore: update vise to 0.3.0, remove patch section

- .github/workflows/ci.yml
> ci: rework what runs for relase-please

- .github/workflows/ci.yml
run only lints for release please PRs
It's enough for release please PRs
> ci: run only lints for release please PRs

- .github/workflows/ci-prover-e2e.yml
- core/Cargo.lock
- core/Cargo.toml
- prover/Cargo.lock
- prover/Cargo.toml
Update respective crates
Patch has to be applied
> feat!: update zksync-protocol and zksync-crypto-gpu deps

- prover/crates/lib/prover_dal/src/fri_prover_dal.rs
> fix: number of chunks for inserting prover jobs

- prover/crates/lib/prover_fri_types/src/lib.rs
> fix: Fix e2e CI for reduced interop

- core/node/da_clients/src/avail/sdk.rs
> feat(avail-gas-relay): add empty json check

- core/lib/types/src/lib.rs
- core/node/state_keeper/src/keeper.rs
> fix(deplpoyment_filter): Allow protocol upgrade

- core/Cargo.lock
- core/lib/web3_decl/src/node/mod.rs
- core/lib/web3_decl/src/node/resources.rs
- core/node/gateway_migrator/Cargo.toml
- core/node/gateway_migrator/src/gateway_urls.rs
- core/node/gateway_migrator/src/lib.rs
- core/node/gateway_migrator/src/node/gateway_migrator_layer.rs
- core/node/gateway_migrator/src/node/settlement_layer_data.rs
Hardcode default gateway urls.
Fix the initialization strategy
> feat(en): Introduce a fallback for gateway url

- docs/src/guides/external-node/02_configuration.md
- docs/src/guides/external-node/03_running.md
Documents recommendations to reduce RAM consumption by the node.
This is a frequently asked question.
> docs(en): Document optimizing RAM consumption

- .github/workflows/ci-core-reusable.yml
- zkstack_cli/crates/zkstack/src/commands/chain/gateway/finalize_chain_migration_from_gw.rs
- zkstack_cli/crates/zkstack/src/commands/chain/gateway/migrate_from_gateway_calldata.rs
- zkstack_cli/crates/zkstack/src/commands/chain/gateway/migrate_to_gateway_calldata.rs
- zkstack_cli/crates/zkstack/src/commands/chain/gateway/notify_server_calldata.rs
- zkstack_cli/crates/zkstack/src/commands/chain/set_da_validator_pair.rs
- zkstack_cli/crates/zkstack/src/messages.rs
> fix(zkstack): Add param for setting da validation pair

- core/Cargo.lock
- core/Cargo.toml
- core/bin/external_node/src/config/mod.rs
- core/lib/config/src/cli.rs
- core/lib/config/src/configs/api.rs
- core/lib/config/src/sources.rs
- prover/Cargo.lock
- prover/Cargo.toml
Fixes `max_response_body_size_overrides` deserialization, so that it's compatible with the existing file-based format.
We want backward compatibility for configs.
> fix(config): Fix `max_response_body_size_overrides` deserialization

- core/Cargo.lock
- core/Cargo.toml
- core/lib/config/src/configs/consensus.rs
- prover/Cargo.lock
- prover/crates/bin/prover_autoscaler/src/global/scaler.rs
- zkstack_cli/Cargo.lock
- zkstack_cli/Cargo.toml
Updates consensus dependencies to 0.11.3.
That version contains a needed fix.
None
> chore(consensus): Update dependencies

- core/bin/external_node/src/config/mod.rs
- core/lib/config/src/configs/contracts/chain.rs
- core/lib/config/src/configs/contracts/ecosystem.rs
- core/lib/multivm/src/versions/vm_fast/version.rs
- core/lib/vm_interface/src/storage/snapshot.rs
- core/lib/vm_interface/src/storage/view.rs
- core/node/eth_sender/src/aggregated_operations.rs
- core/node/eth_sender/src/eth_tx_aggregator.rs
- core/node/eth_sender/src/publish_criterion.rs
- core/node/eth_watch/src/client.rs
- core/node/eth_watch/src/node.rs
- core/tests/ts-integration/tests/erc20.test.ts
> fix: lagging interop todos

- core/Cargo.lock
- core/Cargo.toml
- prover/Cargo.lock
- zkstack_cli/Cargo.lock
- zkstack_cli/Cargo.toml
Contains a needed fix to allow several instances of consensus to use the same TCP port.
None
> fix(consensus): Update consensus dependencies

- prover/crates/bin/prover_autoscaler/src/global/scaler.rs
Use hysteresis to calculate amount of pod to be taking down, better debugging.
This allows for pods stay a bit longer when they can be useful.
ref ZKD-2230
> fix(prover): Improve autoscaler hysteresis logic

- core/node/zksync_os_sequencer/src/execution/block_executor.rs
- core/node/zksync_os_sequencer/src/lib.rs
- core/node/zksync_os_sequencer/src/main.rs
- core/node/zksync_os_sequencer/src/storage/in_memory_account_properties.rs
- core/node/zksync_os_sequencer/src/tx_conversions.rs
Small improvements to the new sequencer
Make it reusable from external crates
> feat(zksync-os-sequencer): create a reusable lib

- core/node/api_server/src/execution_sandbox/execute.rs
- core/node/api_server/src/tx_sender/mod.rs
- core/node/api_server/src/web3/namespaces/eth.rs
- prover/Cargo.lock
- prover/crates/bin/witness_generator/src/tests.rs
- zkstack_cli/crates/zkstack/src/commands/args/run_server.rs
- zkstack_cli/crates/zkstack/src/commands/server.rs
> use zkos flag properly 

- .github/workflows/ci-core-reusable.yml
- core/lib/dal/.sqlx/query-228aa5ec4c4eb56143823b96a8190ded732839b9f5bf16042205a730fac07c3a.json
- core/lib/dal/.sqlx/query-3ee6c2a87c65eaece7048da53c9f98ded0ad3e59e6de69c2b13d92d8ab1a07dd.json
- core/lib/dal/.sqlx/query-c2c40d5aae2e0276de453c78a39ce5a6cca1524adfe99b0cb35662746479dcc1.json
- core/lib/dal/migrations/202601016134308_message_roots.up.sql
- core/lib/dal/src/eth_watcher_dal.rs
- core/node/eth_watch/src/event_processors/appended_chain_batch_root.rs
- core/node/eth_watch/src/event_processors/appended_chain_batch_root_interop.rs
- core/node/eth_watch/src/event_processors/mod.rs
- core/node/eth_watch/src/lib.rs
> fix: add InteropBatchRootProcessor

- zkstack_cli/crates/config/src/contracts.rs
> fix(zkstack): make proving network contracts config optional

- .github/workflows/ci-core-reusable.yml
- .github/workflows/update-verification-keys.yml
- zkstack_cli/Cargo.lock
- zkstack_cli/Cargo.toml
- zkstack_cli/crates/config/src/commitment_keys.rs
- zkstack_cli/crates/config/src/genesis.rs
- zkstack_cli/crates/config/src/lib.rs
- zkstack_cli/crates/zkstack/Cargo.toml
- zkstack_cli/crates/zkstack/src/commands/prover/mod.rs
- zkstack_cli/crates/zkstack/src/commands/prover/snark_keys.rs
- zkstack_cli/crates/zkstack/src/consts.rs
- zksync_os_snark_prover/Cargo.lock
- zksync_os_snark_prover/Cargo.toml
- zksync_os_snark_prover/src/main.rs
> fix(generate-keys): Update genesis 

- core/lib/dal/src/consensus/tests.rs
- core/lib/multivm/Cargo.toml
- core/lib/multivm/src/versions/vm_latest/bootloader/utils.rs
- core/node/state_keeper/Cargo.toml
> fix: fix unit tests CI

- core/tests/highlevel-test-tools/tests/en-integration-test.test.ts
- core/tests/highlevel-test-tools/tests/main-node-integration-test.test.ts
- core/tests/ts-integration/tests/interop.test.ts
> chore: interop tests improvements

- docs/src/specs/contracts/bridging/asset_tracker/asset_tracker.md
Clean the AssetTracker docs page in preparation to pass to security to familiarize with the component.
> docs: clean the AssetTracker docs

- core/lib/types/src/l2_to_l1_log.rs
- prover/crates/lib/prover_fri_types/src/lib.rs
> fix: fix e2e prover components CI for v30 bundles

- core/node/gateway_migrator/src/node/settlement_layer_data.rs
> fix(contracts): force load the contracts for sl

- core/node/eth_sender/src/eth_tx_aggregator.rs
> fix(eth_sender): Do not fail if execution delay function is absent

- core/node/state_keeper/src/io/mempool.rs
> fix(mempool): remove redundant connections

- etc/env/file_based/genesis.yaml
- yarn.lock
- zkstack_cli/crates/config/src/forge_interface/deploy_ecosystem/input.rs
> feat: contracts for zksync os genesis

- zkstack_cli/crates/zkstack/src/commands/prover/run.rs
> fix(zkstack): Fix prover run and shell

- core/lib/settlement_layer_data/Cargo.toml
Add description field for `zksync_settlement_layer_data`.
To fix crates.io publishing for `core`.
> chore: add description for zksync_settlement_layer_data

- core/node/node_sync/src/transaction_finality_updater/mod.rs
> fix(en): Proper error handling for transaction updater

- .github/workflows/release-test-stage.yml
> ci: change deployer

- core/node/eth_proof_manager/src/lib.rs
- core/node/eth_proof_manager/src/sender/mod.rs
- core/node/eth_proof_manager/src/watcher/events/proof_request_proven.rs
> fix(eth-proof-manager): don't fail component if proof was incorrect

- core/Cargo.lock
> chore(deps): Update tracing subscriber

- core/node/eth_sender/src/eth_tx_aggregator.rs
Use the correct encoding function for execute transaction
> fix(eth-sender): Fix selector for old batches

- core/node/reorg_detector/src/lib.rs
> fix(en): Add check for commitment in diverged batch

- prover/crates/bin/prover_autoscaler/src/global/scaler.rs
Split scale errors per pool.
This fixes bug when scale error for one pool affects all pools in the namespace (for example L4 scale errors affects H100 pool in the same namespace).
ref ZKD-3046
> fix(prover): Split scale errors per pool
